### ISSUE TITLE
Iot Edge is not working with DPS TPM on Windows Host

### ISSUE THREAD

**Issue by piyushsharma2512** [Azure/iotedge#1074]
Hi Team,
    I am trying to use DPS On Windows Host with TPM based authentication with IoT Edge and facing below issue. Edge service is just starting and stoping and throwing below error. 
Please suggest me the fix for this on priority as I am stuck because of this..

A module runtime error occurred
        caused by: Could not initialize module client
        caused by: Invalid URL "unix:///C:/ProgramData/iotedge/mgmt/sock": Socket file could not be found

**Comment by piyushsharma2512** [comment]
I have create sock folder then I am getting below error 
A module runtime error occurred
        caused by: Could not list modules
        caused by: an error occurred trying to connect: An invalid argument was supplied. (os error 10022)

**Comment by StefanSchoof** [comment]
Have you enabled hyperv and the container feature? The message is similar to the I got in #1068

**Comment by sachidanand** [comment]
Yes HyperV is enabled on the VM ..

**Comment by arsing** [comment]
Please uninstall and ensure that `C:\ProgramData\iotedge` is deleted. Then rerun the installer. If you still see the "Invalid URL ... Socket file could not be found" error, then give us the output of the installer plus the full logs of the iotedge service.

---

>I have create sock folder then I am getting below error

You should not create a directory named `sock` - it's supposed to be a UDS file created by iotedged. The second error you got (10022 == `WSAEINVAL`) is to be expected if it was a directory instead of a socket file.

**Comment by ancaantochi** [comment]
Closing, please reopen if you can still reproduce this issue.
