### ISSUE TITLE
IoT Edge v1.0.6.1 not working on ARM32???

### ISSUE THREAD

**Issue by xymeet** [Azure/iotedge#1083]
Deployed the sample CSharp Module and tempSensor Module on the Raspberry Pi following this guide - https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module. 

The modules seem to be up and running. 
![image](https://user-images.githubusercontent.com/24821646/56012488-513f8f00-5d1f-11e9-9301-9bb701d3fdc9.png)

However, the CSharpModule is not working. 
![image](https://user-images.githubusercontent.com/24821646/56012640-fce8df00-5d1f-11e9-8074-40a48632f9a1.png)

Furthermore, the edgeHub module keeps posting "Out Of Memory" errors... 
![image](https://user-images.githubusercontent.com/24821646/56012587-b72c1680-5d1f-11e9-8316-94a36d530259.png)

IoT Edge Runtime is the latest: v1.0.6.1.
![image](https://user-images.githubusercontent.com/24821646/56012671-1d189e00-5d20-11e9-890b-435d503c80dc.png)

Is it an known issue? When are expecting a fix?

**Comment by myagley** [comment]
For resource constrained devices, you can restrict the memory use by following this guide: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#stability-issues-on-resource-constrained-devices

This setting will be the default on arm32v7 platforms starting with 1.0.7

**Comment by xymeet** [comment]
@myagley I am pretty sure that this is not a resource issue. I actually tried the same codes on both ARM32 and ARM64 platform and got different results. In my case, ARM32 is Raspberry Pi with Raspbian Stretch; ARM64 is DB410c with Debian. The result suggests this is an issue of IoT Edge Runtime v1.0.6.1. 

Below is the comparison result, just FYI.
![DB410-Rpi IoT Edge](https://user-images.githubusercontent.com/24821646/56074839-aea11200-5deb-11e9-9748-95d9a1ffb08e.jpg)

**Comment by myagley** [comment]
We run the full E2E test suite on a raspberry pi 3 as part of our CI and release process and do not see this issue.

Is it possible there is an issue with your network setup on these devices? It may help to specify a DNS server in the Docker config. This section in the documentation discusses how to do this: https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities#specifying-dns-servers

**Comment by arsing** [comment]
>However, the CSharpModule is not working.

For the "Resource temporarily unavailable" from `System.Net.Dns.GetHostAddresses`, it means `getaddrinfo` returned `EAI_AGAIN` which gets mapped to that string in corefx. Presumably the request to your DNS server failed in some way. (I can't find the code in corefx to confirm, but [this issue](https://github.com/dotnet/corefx/issues/17434#issuecomment-302126716) implies so.)

Now, the module / device client *should* retry, and indeed it seems to me that the `CSharpModule` logs in the your screenshot indicate that the client did retry and was able to connect after the first failure. So you can check your device's DNS server to investigate why the first request failed, but otherwise it's functional.

>Furthermore, the edgeHub module keeps posting "Out Of Memory" errors...

For the `OutOfMemoryException`s in Edge Hub, it is as @myagley said.

**Comment by ancaantochi** [comment]
Closing, please reopen if you are still running into this issue.
