### ISSUE TITLE
Cannot alter logging setting edgeAgent container

### ISSUE THREAD

**Issue by Toofle** [Azure/iotedge#1084]
When settings container logging settings for the edgeAgent the settings won't be used by the container. I can set the logconfig size and max files but it won't be used by the edgeAgent. It does work for the other containers
## Expected Behavior

The EdgeAgent should log but use the max-size and max-files settings in the createOptions of the container
## Current Behavior

The EdgeAgent ignores the settings from the createoptions and keeps logging until the disk is full.
## Steps to Reproduce

1. Create an Edge device
2. Add the following to the edgeAgent create options:
```
{
  "HostConfig": {
    "LogConfig": {
      "Type": "json-file",
      "Config": {
        "max-size": "5m",
        "max-file": "2"
      }
    }
  }
}
```
3. On the system go to docker container files (C:\ProgramData\iotedge-moby-data\containers\<container>\
4. Notice that the files while logging will grow beyond 5m as specified in the config and will not rollover.
5. In hostconfig.json the LogConfig is not specified and remains empty. (The other modules will be filled if specified in the createOptions)

### Device (Host) Operating System

Microsoft Windows Server 2019 Datacenter
(Using the Azure Windows VM: 2019-Datacenter-Core-with-Containers)
### Architecture

x64
### Container Operating System

Windows containers
#### iotedged

iotedge 1.0.6.1
#### Edge Agent

1.0
#### Edge Hub

1.0
#### Docker

18.09.2
## Logs

Current hostconfig.json for my edgeAgent
```
{"Binds":["C:\\ProgramData\\iotedge\\mgmt:C:\\ProgramData\\iotedge\\mgmt","C:\\ProgramData\\iotedge\\workload:C:\\ProgramData\\iotedge\\workload"],"ContainerIDFile":"","LogConfig":{"Type":"json-file","Config":{}},"NetworkMode":"default","PortBindings":null,"RestartPolicy":{"Name":"","MaximumRetryCount":0},"AutoRemove":false,"VolumeDriver":"","VolumesFrom":null,"CapAdd":null,"CapDrop":null,"Dns":null,"DnsOptions":null,"DnsSearch":null,"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":0,"ConsoleSize":[0,0],"Isolation":"process","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":null,"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":null,"DeviceCgroupRules":null,"DiskQuota":0,"KernelMemory":0,"KernelMemoryTCP":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":null,"OomKillDisable":null,"PidsLimit":0,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":null,"ReadonlyPaths":null}
```

**Comment by veyalla** [comment]
Thanks for the report @Toofle. Which container engine are you using? You mention "18.09.2", so is that Docker Desktop? Can you share the settings in the `moby_runtime:` section of `C:\ProgramData\iotedge\config.yaml`

**Comment by Toofle** [comment]
> Thanks for the report @Toofle. Which container engine are you using? You mention "18.09.2", so is that Docker Desktop? Can you share the settings in the `moby_runtime:` section of `C:\ProgramData\iotedge\config.yaml`

The settings are as follows:
`moby_runtime:
  uri: 'npipe://./pipe/iotedge_moby_engine'
  network: 'nat'`

**Comment by varunpuranik** [comment]
@Toofle - how did you set the create options for EdgeAgent? In the deployment (via SetModules option in portal), or in the config.yaml on the device? 

Currently EdgeAgent updates itself only if the deployed image changes in the deployment. For example, if you have mcr.microsoft.com/azureiotedge-agent:1.0.5, and you deploy mcr.microsoft.com/azureiotedge-agent:1.0.6, then the edgeAgent will update itself. If you only change something in its config (such as create options), then the change will not be picked up. 

So, in your case, if the create options were set in the deployment json, and the EdgeAgent version was not updated (which seems to be the case since your version is 1.0), then I think the edgeAgent might not have picked it up. Can you try specifying the actual EdgeAgent version (1.0.6 is the latest) - that should do it.

**Comment by varunpuranik** [comment]
EdgeAgent handles the deployment - so updating the EdgeAgent works slightly differently. 
Basically, when the EdgeAgent updates, it loses all its state, so it has to rely on externally available information, which is the docker image. Otherwise it is impossible for it to detect whether to update, or it has just been updated.
We are looking at improving the behavior, but I don't have a timeline on that yet.

**Comment by varunpuranik** [comment]
If your problem is resolved, can I go ahead and close this issue? Feel free to re-open it if you feel this is still a problem.
