### ISSUE TITLE
Can we do bulk device provision in Azure Edge?

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1093]
Hi,

Can we do bulk device provision in Azure Edge using any mechanism? Right now DPS is possible using TPM but it supports individual provisioning. Can we do bulk provision using TPM?

How can we do DPS for downstream devices?

Thanks,
Prateek

**Comment by myagley** [comment]
Version 1.0.7 is introducing support for the SAS key attestation method. This method will support group enrollments. I don't believe group enrollment is possible with TPM.

We are working on integrating the x.509 attestation method currently. We plan to have this available in the 1.0.8 release.

There is currently no built in support for provisioning downstream devices, but we understand the need and are working on features to make this easier. Do you have an specific expectations for this how this should work so that we can incorporate the feedback into our design process?

**Comment by pratson20** [comment]
Hi @myagley Thanks for update.

I am able to do individual enrolment using SAS key. I can see device registration is happening in DPS.

But facing issue while doing group enrolment. Is there any documentation for Group enrolment using SAS key. 

Thanks,

**Comment by pratson20** [comment]
Hi @myagley 

Is there any way to do DPS for leaf device? We are adding connection-string along with GatewayHostname to communicate with edgeHub.

Is there any way to rid of adding the connection string manually?

**Comment by veyalla** [comment]
Please file or vote for additional feature enhancements at https://feedback.azure.com/forums/907045-azure-iot-edge
