### ISSUE TITLE
iotedged is starting before TPM is in ready state

### ISSUE THREAD

**Issue by saikovvuri** [Azure/iotedge#1107]
Working with a customer who is using TPM 2.0 on edge device.  They have an existing issue with their device hardware that causes TPM to fail when the device goes through a power cycle.  When TPM is not ready, understandably iotedge daemon would not start.
## Expected Behavior

systemd should start iotedged only after TPM is in a ready state.  
## Current Behavior

When the customer detects that TPM (after power recycle) is not ready, They will issue a "reboot" command, that will bring up the TPM, however iotedge will still be in failed state. However when they do issue a reboot command, TPM comes back bit not iotedged

After conversing with @darobs this is our initial findings/conclusions - 
- Iotedged is coming up after a reboot in a failed state.  Our current suspicion is that the system (systemd) is starting iotedge before the TPM is in a ready state.  This may either be because UDEV has not yet set permissions to allow iotedge to read the TPM, or the TPM itself is taking time to become ready. 
- Currently, default settings in the daemon’s systemd configuration are used.  The default is (from memory) restart every 100ms, allow a burst of 5 retries in 10 seconds.  The iotedged process fails almost immediately if the TPM can’t be initialized.
- May be leverage systemd Unit settings. (i.e. StartLimitIntervalSec, StartLimitBurst, After)
## Steps to Reproduce

Difficult to reproduce :) as can't make the TPM to fail on the client edge device. and systemd start order of processes is probably not deterministic.

## Context (Environment)
Production
### Device (Host) Operating System

Ubuntu 18.04
### Architecture

amd64
### Container Operating System

Linux Containers
#### iotedged

1.0.6.1

**Comment by darobs** [comment]
Thank you for reporting this @saikovvuri, I made a task in the backlog to investigate this.

**Comment by myagley** [comment]
If the TPM is being managed by udev, it may be possible to start `iotedged` after the device is ready. This is technically feasible with systemd. You can add a device as a dependency for starting a service.

The lead developer of systemd talks about this briefly here: https://lists.fedoraproject.org/pipermail/devel/2012-January/160917.html

There's also another example of this here: https://unix.stackexchange.com/questions/186899/how-to-wait-for-a-dev-video0-before-starting-a-service

We can certainly make the timeouts for our base unit file longer and is something we should look at. It's going to be a little more difficult for us to ship a unit file that depends on tpm being available because IoT Edge does not take a hard dependency on a tpm. The right way to handle this is to at an override (under `/etc/systemd/`) to add the tpm dependency to the iotedge service unit.

**Comment by saikovvuri** [comment]
Thanks Mike, David.  

I chose the path of using systemd.unit and systemd.service overrides on the iotedge.service file
[Service]
Restart=always
RestartSec=3s
StartLimitBurst=5
StartLimitInterval=30

and it worked fine for our use case.
