### ISSUE TITLE
Restart IoT device from Module docker image

### ISSUE THREAD

**Issue by abouroubi** [Azure/iotedge#1150]
## Expected Behavior

I'm developing an IoT Edge module that needs to access the underlying system to shut down the IoT device it's running on, is there a way to do that with Pyhton module ?

The restart code
```python
def poweroff():
    from subprocess import call
    call("sudo shutdown -h now", shell=True)
```

I tried to add, in my deployment template

```json
"HostConfig": {
    "Privileged": true
  }
```

So the docker image can access the underlying system but it didn't work, I have this error message

```bash
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
```
## Current Behavior

The underlying system doesn't restart.

## Steps to Reproduce

1.
2.
3.
4.

### Device (Host) Operating System

Raspberry Pi 3 Linux

### Architecture

arm32

### Container Operating System

Linux container

#### iotedged

iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent

azureiotedge-agent:1.0

#### Edge Hub

azureiotedge-hub:1.0

#### Docker

Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm

**Comment by myagley** [comment]
This is going to be tricky to achieve from within the context of IoT Edge. By design, the host is hidden from the container. Technically, you can mount `/proc/sys/kernel/sysrq` into the container and send it a shutdown signal. However, this is undesirable for a number of reasons:

1. It requires the `privileged` flag to be set to true. This not only runs the container as root but strips all of the seccomp and apparmor/selinux protections that are in place. This is not secure and dangerous.
2. It makes assumptions about the host device that may not be always valid.

Your best bet is to run something on the host device, outside of a container that manages reboot. We understand this need and are doing some work to make rebooting the device easy (and other host management tasks), but this is not expected to be released for a little while.

**Comment by veyalla** [comment]
Please file or vote for additional feature enhancements at https://feedback.azure.com/forums/907045-azure-iot-edge
