### ISSUE TITLE
Can't update system module ($edgeAgent) twin via Restful API

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#1162]
I am OK to get $edgeAgent twin by : GET https://fully-qualified-iothubname.azure-devices.net/twins/{id}/modules/{mid}?api-version=2018-06-30

But, when I try to update it via PATCH https://fully-qualified-iothubname.azure-devices.net/twins/{id}/modules/{mid}?api-version=2018-06-30, I get below return:
Status code: 401
{
    "Message": "ErrorCode:SystemModuleModifyUnauthorizedAccess;Unauthorized to modify reserved module.",
    "ExceptionMessage": "Tracking ID:189caf67c58a4e6f856c98eb86b6001b-G:16-TimeStamp:05/02/2019 14:26:54"
}

Doesn't Restful API support to update system module ? 
Any suggestion to update system module via program code?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by myagley** [comment]
Hello. Thanks for the issue.

Patching the twin of "system" modules is not supported by design. The reason for this is that these twins have specific schema in their body and need to be validated by the service.

For this specific case, you can use the [Apply Configuration](https://docs.microsoft.com/en-us/rest/api/iothub/service/applyconfigurationonedgedevice) api to update the edge agent twin. The contents of the body are the same contents you see in the 3rd step of the "Set Modules" wizard in the Azure Portal.

**Comment by KevinKao809** [comment]
It works. 

Thanks a lot, Mike.
