### ISSUE TITLE
IoT Edge Agent pulls unsigned images even if DOCKER_CONTENT_TRUST is enabled

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#1173]
Hi,

I have got a device which is behind proxy with following details:
OS: RHEL 7.6
Moby from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-engine-3.0.2-centos.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-cli-3.0.2-centos.x86_64.rpm

IoT Edge runtime from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/libiothsm-std-1.0.6.1-1.el7.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/iotedge-1.0.6.1-1.el7.x86_64.rpm

Proxy configured by following link: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support

Now, I have configured DOCKER_CONTENT_TRUST to 1 so that module can consume only signed images. Or is there any other way to instruct IoT Edge runtime to pull signed image?

When I deploy a unsigned modules from Azure portal it still pull that unsigned image. 

Can you guys please help on this?

Thanks,
Muhammad Masood

**Comment by myagley** [comment]
Unfortunately, Docker Content trust is only implemented in the Docker CLI tool, which IoT Edge does not integrate with.

We are aware of this and are working to improve the content trust story. However, I don't have a definite timeline for when this will be addressed at this point.

**Comment by aresmaverick** [comment]
+1

**Comment by veyalla** [comment]
Please file or vote for additional feature enhancements at https://feedback.azure.com/forums/907045-azure-iot-edge

**Comment by carlo-quinonez** [comment]
Here is a specific enhancement request for this issue.

https://feedback.azure.com/d365community/idea/495d5283-f524-ec11-b6e6-000d3a4f0da0

**Comment by GrantAnt** [comment]
Has anyone found a solution as a workaround? I am evaluating, if a local docker registry might help.

**Comment by carlo-quinonez** [comment]
You can setup a local docker registry and enable Docker content trust on that registry. Configure iotedge to pull from the local registry - iotedge will ignore the trust settings, but none the less, all of the images in the repository are signed. Of course, now you have to populate the local docker registry on your own.

In our use case, this was probably the way to go. Long-term vision is peer-to-peer updates. So if one machine gets updated at a disconnected site, then all of the machines at that site should also get the updates.

IoTEdge team was actually running a Private Preview for Docker Content Trust, but ultimately they decided against rolling it out. We reached out to our MS account team about this but I never got a clear answer why they weren't moving forward with it.... Of course, since it was in private preview, all of the code to make it work again is in the repo. I've looked into the PRs and commits where DCT was removed and there's no mention of a bug. My guess is the feature got pull because DCT is complicated and didn't work for some key customers/architecture/OS/etc.

**Comment by dguidali** [comment]
Whats the state of this? We could need it also.
