### ISSUE TITLE
DeviceClient ReceiveAsync() using Amqp_WebSocket_Only Throws IotHubCommunicationException

### ISSUE THREAD

**Issue by AMCN41R** [Azure/iotedge#1216]
## Expected Behavior
According to the documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d), when calling the `ReceiveAsync()` method on the `DeviceClient`, the message or null should be returned after the specified timeout...

_"The ReceiveAsync method asynchronously returns the received message at the time that it is received by the device. It returns null after a specifiable timeout period "_

This should happen when the `DeviceClient` is configured with transport settings as either `Amqp_WebSocket_Only` or `Mqtt_WebSocket_Only`.

## Current Behavior
If the `DeviceClient` is configured to use `Mqtt_WebSocket_Only`, the expected behaviour is observed. However, is the transport protocol is set to `Amqp_WebSocket_Only`, null is never returned. Instead, an `IotHubCommunicationException` is thrown consistently every 4 minutes. Despite this, C2D messages can still be received.

the exception is...
```csharp
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.ReceiveAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
--- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass17_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync()
```

## Additional Information
This issue was not being observed until Friday, 10th May 2019, before which the expected behaviour was observed. Since this time, the issue has persisted across multiple devices on different IoT Hubs. 

At the time the issue was noticed, we were running runtime version v1.0.6.1 and hub and agent version v1.0.0. We upgraded to runtime version 1.0.7 and hub and agent versions to 1.0.7 and the issue persisted. 

We are also experiencing this issue on the iotedgehubdev simulator.

### Device (Host) Operating System
Ubuntu Server 16.04, Ubuntu Core 16, iotedgehubdev simulator on Windows

### Architecture
amd64

### Container Operating System
Linux containers

### Runtime Versions
v1.0.7

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0.7

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0.7

#### Docker
Docker version 18.06.1-ce

**Comment by varunpuranik** [comment]
Thanks for the issue. I will investigate and get back to you.

**Comment by petermillsacumentive** [comment]
I am getting this problem too @GregTerrell & @AMCN41R - note that the default time out for a ReceiveAsync is 4 minutes:

public const uint DefaultOperationTimeoutInMilliseconds = 240000;
(in Microsoft.Azure.Devices.Client.DeviceClient)

I've found if I set my timeout to something lower like 30 seconds on the .ReceiveAsync method overload - the problem seems to stop.

**Comment by petermillsacumentive** [comment]
If I set the timeout by hand to 240 seconds manually (which is the same), it seems to behave:

ReceiveAsync(TimeSpan.FromSeconds(240));

**Comment by GregTerrell** [comment]
Thanks @petermillsacumentive I will try that since the forcing to MQTT did not 100% fix the issue.

**Comment by and-rewsmith** [comment]
I can reproduce this issue via amqp_web_sockets_only, however it **also** appears with amqp_tcp_only.  The IoTHubCommunication is not seen when using the ReceiveAsync(timeout) overload because of [this catch](https://github.com/Azure/azure-iot-sdk-csharp/blob/4cbd08a59bfb67e0a2cf6549a43d70d5339e10f0/iothub/device/src/InternalClient.cs#L404). 


I found it confusing how [ReceiveAsync() and ReceiveAsync(timeout)](https://github.com/Azure/azure-iot-sdk-csharp/blob/4cbd08a59bfb67e0a2cf6549a43d70d5339e10f0/iothub/device/src/InternalClient.cs#L374) differ with respect to exceptions, so I looked at the blames for these two functions. The catch for IoTHubCommunicationException in receiveAsync(timeout) was added in [this PR](https://github.com/Azure/azure-iot-sdk-csharp/pull/741) which changed the way timeouts worked over amqp. This PR did not touch the implementation of ReceiveAsync(), which I find **extremely suspicious** as it throws a timeout exception (I'm guessing at the 4 minute mark when the problem is reported). 


My intuition is a change is required in the C# - sdk to implement the same catch logic (would also be worth checking if issue exists in other language sdks and also the moduleClient). What makes me slightly hesitant to make sdk changes is that I do not yet understand exactly how [this timeout exception](https://github.com/Azure/azure-iot-sdk-csharp/blob/4cbd08a59bfb67e0a2cf6549a43d70d5339e10f0/iothub/device/src/InternalClient.cs#L387)  percolates to [this exception](https://github.com/Azure/azure-iot-sdk-csharp/blob/78f410cc0799a2949ad9e278821d0240f2339c33/iothub/device/src/Transport/ErrorDelegatingHandler.cs#L181). It is likely that this this is the old way amqp timeouts were handled prior to the above PR and that making exception logic consistent across ReceiveAsync() and ReceiveAsync(timeout) will fix the issue. This can be done by catching the IoTHubCommunicationException as ReceiveAsyncTimeout(timeout) does.


For reference, [here](https://github.com/Azure/azure-iot-sdk-csharp/blame/2ccb7d1226a3bdc757467a51930a96650f626350/iothub/device/src/InternalClient.cs#L378) is the state of ReceiveAsync() methods before the PR. I don't understand how ReceiveAsync() was supposed to return null as specified in the documentation if this TimeoutException has been the mechanism for cancellation. ReceiveAsync(timeout) has previously handled timeouts differently w.r.t cancellation tokens, which I'm guessing is why it never threw TimeoutExceptions like ReceiveAsync().

**Comment by and-rewsmith** [comment]
I was advised by @CIPop that [this pull request](https://github.com/Azure/azure-iot-sdk-csharp/pull/973/files#) likely solves this issue. I will investigate further just to be sure. If it doesn't fix it, then I will open an issue in [the sdk repo](https://github.com/Azure/azure-iot-sdk-csharp).

**Comment by and-rewsmith** [comment]
I never tested the PR branch as it is more efficient for SDK team to test this themselves. See the issue linked above ^
