### ISSUE TITLE
Add DNS name validation for Edge device host name to "iotedge check"

### ISSUE THREAD

**Issue by avranju** [Azure/iotedge#1224]
If the host name configured in `config.yaml` is not a _valid_ DNS name (valid as per RFC 1035 -- though the RFC does not _require_ adherence to said rules) then `iotedge check` should flag that as an error. This is because some edge modules (especially those that use the IoT Hub C# SDK to connect to Edge Hub) have trouble with TLS validation during connection.

The rules for a "valid" name are:
  - length must be <= 63 characters
  - must be all lower case alphanumeric characters or '-'
  - must start with an alphabet
  - must end with an alphanumeric character

For the "lower case" requirement, Edge already automatically converts the host name to lowercase so that may not be a problem.

**Comment by veyalla** [comment]
PTAL @arsing

**Comment by myagley** [comment]
> For the "lower case" requirement, Edge already automatically converts the host name to lowercase so that may not be a problem.

I think we should still call it out in the check tool. I'd rather be explicit in this case and the use the lower-casing as a last resort.

**Comment by arsing** [comment]
RFC 1035 was superseded by other RFCs a long time ago (eg RFC 2121 in 1997). Domain names can start with digits ( https://01.org/ being a very famous example) and are not even limited to ASCII characters (alphanumeric or otherwise).

Only the 63-octet length for individual labels and the 255-octet length for the whole name still apply today.

However if the C# SDK has problems with the full breadth of valid domain names, we need to figure out what rules *it* follows and implement checks for *those* rules.

**Comment by arsing** [comment]
Talked with Raj offline. He specifically mentioned RFC 1035 because Kubernetes uses it for the validation of service names, etc. The case of the C# SDK was with a hostname containing an `_`.

We decided to make it a warning if the device hostname does not fit RFC 1035 with a note mentioning that adhering to RFC 1035 would offer "maximum compatibility" with other software. That way the user can ignore it if their software doesn't in fact have this problem.
