### ISSUE TITLE
IoT edge runtime not installing on Windows version 1809 when using TPM DPS mode

### ISSUE THREAD

**Issue by saikovvuri** [Azure/iotedge#1229]
Attempted to install latest 1.0.7 of IoT edge runtime on Windows 10 enterprise version 1809 Build 17763.503. Using TPM as the attestation method.
## Expected Behavior

IoT edge runtime should be successfully install
## Current Behavior

followed the documentation on https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows. 

However tried several times and keep erroring out when the ps script tries to start the iotedge service 
## Steps to Reproduce

1.
2.
3.
4.

### Device (Host) Operating System

Windows 10 enterprise version 1809 build 17763.503
### Architecture

amd64
### Container Operating System

Windows
#### iotedged

1.0.7
## Logs

PS C:\WINDOWS\system32> . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
>> Install-SecurityDaemon -ContainerOs Windows -Dps

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Initialize-IoTEdge, Insta...

cmdlet Install-IoTEdge at command pipeline position 1
Supply values for the following parameters:
ScopeId: XXXXX
RegistrationId: XXXXX
The container host is on supported build version 17763.
WARNING: One or more batteries were detected on this device.

A known Windows operating system issue prevents transition to sleep and hibernate power states when IoT Edge modules
(process-isolated Windows Nano Server containers) are running. This issue impacts battery life on the device.

As a workaround, use the command "Stop-Service iotedge, iotedge-moby -Force" to stop any running IoT Edge modules
before using these power states.

Confirm
Do you want to continue with installation?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
Skipping VC Runtime installation because it is already installed.
Downloading IoT Edge...
Using IoT Edge from C:\Users\sakovvu\AppData\Local\Temp\microsoft-azure-iotedge.cab
The container host is on supported build version 17763.
Generating config.yaml...
Configured device for DPS provisioning.
Configured device with hostname 'MININT-HPDSUR6'.
Configured ProgramData directory.
Configured device with Moby Engine URL 'npipe://./pipe/iotedge_moby_engine' and network 'nat'.
Updated system PATH.
Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start
service iotedge on computer '.'.
At line:1328 char:9
+         Start-Service $EdgeServiceName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
## Additional Information

Verified the hyper-v and containers windows features are enabled. 
Am i missing an environment variable. ?
Using TPM as the attestation method.

**Comment by veyalla** [comment]
@mrohera is taking a look.

**Comment by saikovvuri** [comment]
Hello @mrohera @veyalla  ,  Quick update.  
i tried to go back one version and was able to install iotedge 1.0.6  successfully and verify all system modules were operating just fine
. {Invoke-WebRequest -useb https://raw.githubusercontent.com/Azure/iotedge/1.0.6/scripts/windows/setup/IotEdgeSecurityDaemon.ps1 } | Invoke-Expression; Install-SecurityDaemon -Dps -ContainerOs Windows

Still not able to get the same work with 1.0.7

**Comment by veyalla** [comment]
@saikovvuri - it does seem like a regression. 

As a temporary workaround, can you check if using the aka.ms link like below helps?

`. {Invoke-WebRequest -useb https://aka.ms/iotedge-wininstall-dps107} | Invoke-Expression; Initialize-IoTEdge.... `

(You'll need to execute `Deploy-IoTEdge` before)

**Comment by saikovvuri** [comment]
@veyalla  , followed your instructions and it worked fine this time :)
I did notice one thing , when i execute this command
. {Invoke-WebRequest -useb https://aka.ms/iotedge-wininstall-dps107} | Invoke-Expression; Initialize-IoTEdge -Dps .  it should technically prompt me for scopeid and registrationid.   It only prompted for scopeid and then when i typed that in and hit enter,  it failed with the message "Registration Id is required ...." but it still created a config.yaml file.   

So only way to get around was to provide scopeid and registrationid inline. 

Post that it worked fine,

**Comment by veyalla** [comment]
@saikovvuri 

Actually, now that I am seeing your original report, you are using the old cmdlets. Please use updated (for 1.0.7) instructions at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#option-2-install-and-automatically-provision

But change the aka.ms link to https://aka.ms/iotedge-wininstall-dps107 and please let me know if it works. Thanks!

**Comment by saikovvuri** [comment]
@veyalla  actually I was not using the old cmdlets. Below are the tests I did - 

**_1st iteration_**
Followed instructions from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#option-2-install-and-automatically-provision
TEST FAILED - that is when i logged the issue

**_2nd Iteration_**
Just to validate if my windows environment had all the prequisites, I tried to install a previous stable version of Iotedge using - https://raw.githubusercontent.com/Azure/iotedge/1.0.6/scripts/windows/setup/IotEdgeSecurityDaemon.ps1
TEST SUCCEEDED

**_3rd Iteration_**
Based on your suggestion, changed the aka.ms link to https://aka.ms/iotedge-wininstall-dps107
TEST SUCCEEDED

Hope this clarifies

**Comment by ppavanm** [comment]
@veyalla - I was receiving the same issue mentioned in the description, so I tried using the temporary workaround that you specified above, using https://aka.ms/iotedge-wininstall-dps107, which successfully initialized iotedge.

But when I did Get-Service iotedge, it showed that iotedge service is in stopped status.
Following is the complete log provided by the Get-IoTEdgeLog.  Could you please let me what could be the problem here.

TimeCreated          Message
-----------          -------
5/28/2019 3:29:19 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:19 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:19 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:19 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:19 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:19 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:19 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:21 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:21 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:21 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:21 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:21 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:21 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:21 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:26 PM info: iotedged -- Change to configuration file detected.
5/28/2019 3:29:26 PM info: iotedged -- Removing all modules...
5/28/2019 3:29:26 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:26 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:26 PM info: iotedged -- Finished removing modules.
5/28/2019 3:29:29 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:29 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:29 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:29 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:29 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:30 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:30 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:30 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:30 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:30 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:30 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:30 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:30 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:30 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:30 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:30 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:30 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:30 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:30 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:30 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:30 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:30 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:30 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:30 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:30 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:30 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:30 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:30 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:31 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:31 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:31 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:31 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:31 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:31 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:31 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:31 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:31 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:31 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:31 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:31 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:31 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:31 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:31 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:31 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:31 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:31 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:31 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:31 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:31 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:31 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:31 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:32 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:32 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:32 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:32 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:32 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:32 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:32 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:32 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:32 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:32 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:32 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:32 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:32 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:32 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:32 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:32 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:32 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:32 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:32 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:32 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:32 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:32 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:32 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:33 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:33 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:33 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:33 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:33 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:33 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:33 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:33 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:33 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:33 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:33 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:33 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:33 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:33 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:33 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:33 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:33 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:33 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:33 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:33 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:33 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:33 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:33 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:34 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:34 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:34 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:34 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:34 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:34 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:34 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:34 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:34 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:34 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:34 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:34 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:34 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:34 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:34 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:34 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:34 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:34 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:34 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:34 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:34 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:34 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:34 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:35 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:35 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:35 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:35 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:35 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:35 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:35 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:35 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:35 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:35 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:35 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:35 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:35 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:35 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:35 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:35 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:35 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:35 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:35 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:35 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:35 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:35 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:35 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 3:29:36 PM info: iotedged -- Using runtime network id nat
5/28/2019 3:29:36 PM info: iotedged -- Initializing the module runtime...
5/28/2019 3:29:36 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 3:29:36 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 3:29:36 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 3:29:36 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 3:29:36 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 3:29:36 PM info: iotedged -- Configuring certificates...
5/28/2019 3:29:36 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 3:29:36 PM info: iotedged -- Finished configuring certificates.
5/28/2019 3:29:36 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 3:29:36 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 3:29:36 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 3:29:36 PM info: iotedged -- Initializing hsm...
5/28/2019 3:29:36 PM info: iotedged -- No change to configuration file detected.
5/28/2019 3:29:36 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 3:29:36 PM info: iotedged -- Finished initializing hsm.
5/28/2019 3:29:36 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 3:29:36 PM info: iotedged -- Provisioning edge device...
5/28/2019 3:29:36 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 3:29:36 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 3:29:36 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 3:29:36 PM error: iotedged::windows -- Error while running service. Quitting.

**Comment by veyalla** [comment]
The workaround should no longer be required with [1.0.7.1](https://github.com/Azure/azure-iotedge/releases/tag/1.0.7.1) release last week. Please uninstall and try with the official instructions.

**Comment by ppavanm** [comment]
@veyalla - I tried uninstalling and using the official instruction from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows but I am seeing same error logs

Following is the IoTEdgeLog
TimeCreated          Message
-----------          -------
5/28/2019 4:16:11 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 4:16:11 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 4:16:11 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 4:16:11 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 4:16:11 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 4:16:11 PM info: iotedged -- Initializing the module runtime...
5/28/2019 4:16:11 PM info: iotedged -- Using runtime network id nat
5/28/2019 4:16:12 PM info: iotedged -- Configuring certificates...
5/28/2019 4:16:12 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 4:16:12 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 4:16:12 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 4:16:12 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 4:16:12 PM info: iotedged -- Initializing hsm...
5/28/2019 4:16:12 PM info: iotedged -- Finished configuring certificates.
5/28/2019 4:16:17 PM info: iotedged -- Change to configuration file detected.
5/28/2019 4:16:17 PM info: iotedged -- Removing all modules...
5/28/2019 4:16:17 PM info: iotedged -- Finished initializing hsm.
5/28/2019 4:16:17 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 4:16:17 PM info: iotedged -- Finished removing modules.
5/28/2019 4:16:19 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 4:16:19 PM info: iotedged -- Provisioning edge device...
5/28/2019 4:16:19 PM error: iotedged::windows -- Error while running service. Quitting.
5/28/2019 4:16:19 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
5/28/2019 4:16:19 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 4:16:20 PM info: iotedged -- Using runtime network id nat
5/28/2019 4:16:20 PM info: iotedged -- Initializing the module runtime...
5/28/2019 4:16:20 PM info: edgelet_docker::runtime -- Initializing module runtime...
5/28/2019 4:16:20 PM info: iotedged::windows -- Starting iotedged service.
5/28/2019 4:16:20 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/28/2019 4:16:20 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/28/2019 4:16:20 PM info: iotedged::app -- Version - 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
5/28/2019 4:16:20 PM info: iotedged -- Finished initializing the module runtime.
5/28/2019 4:16:20 PM info: edgelet_docker::runtime -- Successfully initialized module runtime
5/28/2019 4:16:20 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/28/2019 4:16:20 PM info: iotedged -- Configuring certificates...
5/28/2019 4:16:20 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/28/2019 4:16:20 PM info: iotedged -- Initializing hsm...
5/28/2019 4:16:20 PM info: iotedged -- Finished configuring certificates.
5/28/2019 4:16:20 PM info: iotedged -- Obtaining workload CA succeeded.
5/28/2019 4:16:20 PM info: iotedged -- Provisioning edge device...
5/28/2019 4:16:20 PM info: iotedged -- Starting provisioning edge device via TPM...
5/28/2019 4:16:20 PM info: iotedged -- Finished initializing hsm.
5/28/2019 4:16:20 PM info: iotedged -- Detecting if configuration file has changed...
5/28/2019 4:16:20 PM info: iotedged -- No change to configuration file detected.
5/28/2019 4:16:20 PM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize
                     DPS provisioning client
5/28/2019 4:16:20 PM error: iotedged::windows -- Error while running service. Quitting.

**Comment by ppavanm** [comment]
@veyalla - Is it because the latest iotedge runtime (1.0.7.1) expecting actual TPM device versus TPM simulator?

**Comment by saikovvuri** [comment]
verified the fix in latest release 1.0.7.1
