### ISSUE TITLE
Module twin reported properties update

### ISSUE THREAD

**Issue by ahmet-kara** [Azure/iotedge#1252]
Updating module twin reported properties by using ModuleClient.UpdateReportedPropertiesAsync always notifies event hub even the data/value does not change. I am not sure this expected or not but also with this context there is no big difference with telemetry as usage perspective.

## Expected Behavior
Cloud should be notified when only data/value changed.

## Current Behavior
Cloud is always notified when update method called indepedendet from the value/data.

## Steps to Reproduce

1. Call UpdateReportedPropertiesAsync method with valid key:value json.
2. See events on event hub.
3. Call again UpdateReportedPropertiesAsync with the same data.
4. See again events on event hub

## Context (Environment)
Azure iot edge module container

### Device (Host) Operating System
Raspbian on Raspberry Pi

### Architecture
arm32v7

### Container Operating System
IoT Edge template module

**Comment by myagley** [comment]
This is by design. The expectation is that the client wouldn't send the update if the value hasn't changed. The API doesn't take into account the current state of the twin. 

What is your scenario? Reported properties shouldn't typically be used in scenarios that require high throughput. The twin (and report properties) is best used for config and reporting the current state of this config. If you have a valid that is rapidly changing, it is probably best to implement this with device to cloud messages (telemetry).

**Comment by ahmet-kara** [comment]
With this context it is hard to understand why I need twin if I manage the data. What is the benefit to use twin instead of telemetry, even the data not require high throughput?

**Comment by myagley** [comment]
The Twin is used for configuration. It's best used when you want to manage settings for the device from the cloud. In this case, the desired properties and reported properties are usually mirrors of each other. The desired properties contain the settings that the device *should* use and the reported properties list the *current* settings in use by the device.

Measurements of some piece of data that constitutes the function of the device is best served using telemetry (device to cloud messages).
