### ISSUE TITLE
Turning off log message for simulated temperature sensor?

### ISSUE THREAD

**Issue by forkjoseph** [Azure/iotedge#1281]
Hi,

I'm currently interning at MNR, MSR in Redmond. 

I was looking at simulated temperature sensor to generate some high frequency message (> 30K msg / sec). Currently, when I run a bench, the max rate is ~2.4K msg / MINUTE. 

I suspect that the verbose log of the simulated sensor is a bottleneck. Can you guys give a tip to turn off the log message to iotedge service (iotedge logs Sensor -f) without building a custom docker image? 

Thanks!
Joseph

**Comment by myagley** [comment]
You are unfortunately going to have to modify the code to turn of the logs. Most of our code using the Asp.Net logging extension and can have the log level set. However, since the temp sensor is just a sample it looks like it is using `Console.WriteLine` and not the logging extension.

Can I ask a little more about your scenario? Are you trying to get this throughput with IoT Edge (and the Edge Hub) or IoT Hub? For both scenarios, it is unlikely that you will be able to get 30k/sec for a single identity. This is because message ordering must be maintained per identity so message processing is essentially single threaded. You will need to use many identities to get parallelism to get high throughput.

**Comment by myagley** [comment]
Also, Go Blue!

**Comment by ancaantochi** [comment]
Closing issue since there were no comments for a while. Please reopen if you have questions related to this.
