### ISSUE TITLE
Dockerized Edge

### ISSUE THREAD

**Issue by smoms** [Azure/iotedge#1420]
Hi,
I would like dockerize IoT Edge so that I can run on my OS platform. Something similar to what has been done here (but) for V1: https://github.com/maxtheaviator/resin-azure-iotedge-multicontainer

My question is: what modules are required? Just edge-agent and edge-hub? Is it enough to use their provided Dockerfiles (e.g. https://github.com/Azure/iotedge/blob/master/edge-agent/docker/linux/arm32v7/Dockerfile) ? Which configuration file(s) should I use?

thanks

**Comment by arsing** [comment]
The Dockerfile you linked to is for Edge Agent, which already runs inside a container.

If you want to run the IoT Edge Security Daemon itself (ie the thing you get from the `iotedge.deb` / `iotedge.rpm` packages), you can create a base container using one of the OSes in https://docs.microsoft.com/en-us/azure/iot-edge/support#tier-1 , install the package into it, and set up the entrypoint + config to run it without systemd. Also ensure the Docker socket from the host is mounted inside the container.

**Comment by smoms** [comment]
@arsing thanks. Just to be sure I understand your message: you are saying that _iotedge.deb_ contains the Edge Security Daemon, right? And the Edge Security Daemon is the **only** component I need to containerize Edge, right?
Also, I know where to find _iotedge.deb_ for arm _https://aka.ms/iotedged-linux-armhf-latest_ but where can I find the packages for other/AMD platforms?

thanks.

**Comment by arsing** [comment]
>you are saying that iotedge.deb contains the Edge Security Daemon, right?

Yes.


>And the Edge Security Daemon is the only component I need to containerize Edge, right?

Yes. The other components (Edge Agent, Edge Hub, modules) are already containerized.


>Also, I know where to find iotedge.deb for arm https://aka.ms/iotedged-linux-armhf-latest but where can I find the packages for other/AMD platforms?

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux

**Comment by smoms** [comment]
@arsing thanks again. Few more things pls. 

> Yes. The other components (Edge Agent, Edge Hub, modules) are already containerized.

Do you mean that I need to containerize Security Daemon **and** then download also the containers Edge Agent, Edge Hub **as well**? Then Edge Agent, Edge Hub are still required (sorry if my previous question was not clear) ?

> https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux

Here I do not see a link to a  _iotedge.deb_ package!?

**Comment by arsing** [comment]
>Do you mean that I need to containerize Security Daemon and then download also the containers Edge Agent, Edge Hub as well? Then Edge Agent, Edge Hub are still required (sorry if my previous question was not clear) ?

Edge Agent is a required component of IoT Edge. It is spawned as a container by the Security Daemon, and Edge Agent in turn then looks at your deployment manifest and spawns additional containers (via iotedge) for Edge Hub and any edge modules you want.

This is why I said in my first post that you will need to mount the Docker socket from the host inside your iotedge container, so that the containerized iotedge can spawn additional containers on the host.


>Here I do not see a link to a iotedge.deb package!?

The page shows you how to use `apt-get` to install the package.


>Just to re-state my problem: I am trying to containerize Edge on runtime that is NOT Moby but balena-engine..

Sure. As long as balena-engine exposes the same HTTP API as Moby does, the Security Daemon will not care.

**Comment by smoms** [comment]
@arsing so the Security Daemon contained in _iotedge.deb_ package will automatically download (and create containers from) the images of Agent and Hub? thanks.

**Comment by arsing** [comment]
Correct.

You may want to follow the tutorial on a regular device to understand how it works. That'll also help you to troubleshoot any issues from when you put it in a container.

**Comment by veyalla** [comment]
Note, while running iotedged in a container is possible and fine for a development scenario, this is not a configuration recommended or supported in production. The primary reason being lowered security standards due to the inability to use Unix Domain Sockets in this environment.

This is however supported in our Kubernetes integration where we'll use facilities native to the Kubernetes (e.g. Service Accounts) to maintain security standards. See https://aka.ms/iotedge-on-kubernetes for more details.

**Comment by arsing** [comment]
>The primary reason being lowered security standards due to the inability to use Unix Domain Sockets in this environment.

Why would you not be able to use UDS? As I said in my first post, the `homedir` should be mounted from the host, so the sockets would be created inside it and can be mounted inside modules.

**Comment by veyalla** [comment]
Oh, I missed that. I guess it can be made to work but I doubt we'd support it as we don't test this setup.

**Comment by smoms** [comment]
@arsing 

> (*) Specifically, you want to mount the homedir on the host so that it can be remounted inside modules, and you want to use UDS unix:// URIs for the listen.* endpoints instead of fd:// since it won't be running under systemd.

In which module (Security Daemon) should I mount the homedir?
Also, once mounted the _unix://_ should refer to a path inside that dir?

thanks

**Comment by iAmoric** [comment]
Hi @arsing 

This is my base Dockerfile:

```
FROM amd64/debian

RUN apt-get update
RUN apt-get install --y curl

RUN curl -L https://github.com/Azure/azure-iotedge/releases/download/1.0.8-rc3/iotedge_1.0.8.rc3-1_amd64.deb -o iotedge.deb && dpkg -i ./iotedge.deb

WORKDIR /etc/iotedge

RUN sed -i '/device_connection_string/c\  device_connection_string : \"'$DEVICE_CONNECTION_STRING'\"' ./config.yaml
```

I don't understand what you explained:

> set up the entrypoint + config to run it without systemd (\*). Also ensure the Docker socket from the host is mounted inside the container.
> 
> (\*) Specifically, you want to mount the homedir on the host so that it can be remounted inside modules, and you want to use UDS unix:// URIs for the listen.* endpoints instead of fd:// since it won't be running under systemd.

For the moment I have the following error, that I think is normal because I hadn't do what wou suggested:

```
ERROR: No container runtime detected.
Please install a container runtime and run this install again.
```

Could you help me to update this Dockerfile to dockerise iotedge? 

Thanks

**Comment by arsing** [comment]
@iAmoric

>For the moment I have the following error, that I think is normal because I hadn't do what wou suggested:
>
>```
>ERROR: No container runtime detected.
>Please install a container runtime and run this install again.
>```

That particular error is because the package install wants to enforce that you have some kind of container runtime running, and it does that by checking for the existence of the `docker` group. The group gets created when you install a Docker package, but of course you don't want to do that inside the `iotedged` container (since it's supposed to use Docker running on the host). So instead just create a dummy group with that name.

**Comment by iAmoric** [comment]
> create a dummy group with that name.

Like adding in my Dockerfile `groupadd docker` ?

**Comment by iAmoric** [comment]
hi @arsing 
Thanks it works, I can install iotedge. Now I have to make it running. Could you please give more details about that:

> In which module (Security Daemon) should I mount the homedir?
> Also, once mounted the _unix://_ should refer to a path inside that dir?

Thanks

**Comment by arsing** [comment]
The daemon creates some files under the `homedir` config value (default `/var/lib/iotedge`), including the UDS sockets for the management and workload endpoints (default `unix:///var/lib/iotedge/mgmt.sock` and `workload.sock`).

These endpoints are mounted inside the edge agent and other module containers so that they can talk to `iotedged`, so they must be on the host filesystem rather than remain inside the `iotedged` container filesystem. Thus you must mount the `homedir` on the host.

**Comment by smoms** [comment]
@arsing are you sure that is 

> /var/lib/iotedge

and not

> /var/run/iotedge

?

Please check this thread: https://forums.balena.io/t/dockerize-iot-edge-v2-for-balenaos/18870/40 from inspecting the _edgeAgent_ container

Also, would it be possible to modify this location (_/var/lib/iotedge_) ? SInce you said that is _default_ then i expect we can modify it..

thanks

**Comment by arsing** [comment]
If balena doesn't support mounting host filesystem paths inside containers, then you need to use HTTP as Venkat suggested in that thread. Even if you mounted a named volume inside the iotedged container at the homedir, `iotedged` would still try to spawn module containers with a `$homedir:$homedir` mount and fail.

Anyway since discussion is happening in that thread, I'll close it here. (This issue tracker isn't the right place for this discussion anyway.)
