### ISSUE TITLE
iotedge restart [MODULE] fails with 'Hyper error'

### ISSUE THREAD

**Issue by chriswaters78** [Azure/iotedge#15]
***Windows 10 with linux containers, GA release***

I am trying to restart individual module with the command iotedge restart [module]. This just returns the error:

_An error in the management http client occurred.
        caused by: Hyper error
        caused by: No connection could be made because the target machine actively refused it. (os error 10061)_

**Comment by myagley** [comment]
This is most likely because the `IOTEDGE_HOST` environment variable is not set properly or you are running into a firewall. To resolve, you can run through the [Configure the Azure IoT Edge Security Daemon](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-windows#configure-the-azure-iot-edge-security-daemon) section in the documentation again.

We've heard that this env variable can get reset on a reboot. We are working on a proper installer for windows that should help here.

**Comment by chriswaters78** [comment]
Thanks @myagley , seems the environment variable had gone missing. Once I set it again and rebooted I could use the iotedge commands.

**Comment by damonbarry** [comment]
Excellent. The documentation was recently updated to show how to persist the `IOTEDGE_HOST` environment variable (see MicrosoftDocs/azure-docs@f85c944) so I'll close this issue.

**Comment by nkolchakov** [comment]
In my case with the same error, the `Get-Service iotedge` showed that it stopped, and running `Start-Service iotedge` did the work for me.
