### ISSUE TITLE
edgeHub enqueues same message twice

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#1538]
We have a custom module that is pushing data to edgeHub using ModuleClient.
During one second period we send around 3 messages from this custom module.
To be sure that there is no race condition the sending logic is using semaphore.

            await this.semaphore.WaitAsync(token);
            try
            {
                await this.client.SendEventAsync(message, token);
            }
            finally
            {
                this.semaphore.Release();
            }

Each message is marked with trid (which is tracking id) so we know that module actually pushed message only once to edgeHub.

## Expected Behavior
Only one message arrives to iothub in cloud if there are no exceptions found in the custom module nor edgeHub.

If same message is enqueued twice by edgeHub it should be somehow logged so we know why it is happening.

## Current Behavior

EdgeHub enqueus sometimes same message twice.
It happens around once a day. 

Examplary duplicate message that was delivered twice to azure iothub:

epoc$637000749025939191
devid21228-00016**trid9152**seq
45726kit E3Flex0100-DIMC 
$connectionDeviceId jpmeiot-meij-01$connectionModuleId DispatcherModule(connectionAuthMethodœ{"scope":"module","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}8connectionDeviceGenerationId$636934407835424595**enqueuedTime82019-07-30T09:15:17.9710000Z** [1]Úþ98,0,41.2
99,0,41

epoc$637000749025939191
devid21228-00016**trid9152**seq
45726kit E3Flex0100-DIMC 
$connectionDeviceId jpmeiot-meij-01$connectionModuleId DispatcherModule(connectionAuthMethodœ{"scope":"module","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}8connectionDeviceGenerationId$636934407835424595**enqueuedTime82019-07-30T09:15:21.2520000Z** [1]Úþ98,0,41.2
99,0,41

edgeHub enqueued same message 4 seconds later ([2019-07-30T09:15:21.2520000Z - 2019-07-30T09:15:17.9710000Z]) after first message was enqueued.

## Steps to Reproduce

1. Create custom module that output 3 messages a second using ModuleClient. Add trid to each message and increment it for each message that is sent. Each message body should contain around 64kb of csv content.
2. Configure iothub to dump data to blob storage
3. Check after 2 days if in the blob storage message that arrives have same trid header.

### Device (Host) Operating System

CentOs

### Architecture

amd64
### Container Operating System

Linux containers

#### iotedged

iotedge 1.0.5

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0.7.1 

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0.7.1

#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       8ecd530
  Built:            Fri Jan 25 01:45:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.2
  GitCommit:        9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        96ec2177ae841256168fcf76954f7177af9446eb
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs
[edgeHub30072019.txt](https://github.com/Azure/iotedge/files/3480786/edgeHub30072019.txt)

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by sebader** [comment]
can you post your routing configuration from your deployment.json?

**Comment by AdamMachera** [comment]
"$edgeHub": {
			"properties.desired": {
				"schemaVersion": "1.0",
				"routes": {
					"DispatcherModuleToIotHub": "FROM /messages/modules/DispatcherModule/* INTO $upstream"
				},
				"storeAndForwardConfiguration": {
					"timeToLiveSecs": 7200
				}
			}
		},

**Comment by lt72** [comment]
@sebader sorry for the late answer. Did you manage to solve your issue or do you still need help?

**Comment by AdamMachera** [comment]
We added to all outgoing messaged unique identifier on the module level, so
even when edgeHub was sending it twice we were able to filter them on data
lake level.

Regards,
Adam.

pt., 8 lis 2019 o 02:22 Lorenzo Tessiore <notifications@github.com>
napisał(a):

**Comment by vipeller** [comment]
@AdamMachera - thank you for your reports and logs. Can you confirm that your custom module is set up to use MQTT protocol to talk to EdgeHub?

My current theory is the following:

- authentication tokens expire regularly. In case of MQTT, the protocol (3.x) doesn't give a way to reauthenticate, so the current solution is that the module disconnects and reconnects again with the fresh authentication token.
- when the custom module disconnects, Edge Hub will drop the related connection to IoT Hub, too.
- it can happen that a message was sent out to IoT Hub, but the ACK hasn't been received yet.
- Because of the dropped connection, EdgeHub cannot be sure that the sent out message has arrived
- Because of this, it resents the message

Although the odds are little for this bad timing, you mentioned your relatively high message rate (3/sec?) which long term increases the chance that it ultimately would happen.

If this is the case, it is something we need to improve. I am starting to investigate that this can happen at all, however I need to be sure that you use MQTT. This doesn't happen with AMQP as it is able to re-authenticate without dropping the connection. This also can be a solution to your problem, to switch protocol.

**Comment by AdamMachera** [comment]
We are using Mqtt for custom module to edgeHub authentication.

**Comment by lt72** [comment]
@varunpuranik @vipeller did we reach any conclusion on this one?

**Comment by vipeller** [comment]
@lt72 we've been working on higher priority issues - it is something we probably could improve, however we support "at least once" delivery, which can result duplicated messages. Because of this, we don't treat it as a bug but as an improvement point. We have a bug ticket recorded for the issue - but as said, always there is something with higher priority.

**Comment by vipeller** [comment]
Ticketed this issue as enhancement and closing it for now

**Comment by Vic152** [comment]
This is still an issue.

**Comment by nainesh72** [comment]
Hi
I have the same issue please read the following 
Azure IoT Hub Generates Duplicate Events #22905
https://github.com/Azure/azure-sdk-for-net/issues/22905#

please replay
