### ISSUE TITLE
Payload for collecting logs using Direct Method

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#1596]
Hi Team,
    We are using 1.09. RC 1 and as per your release note you have implemented log collection using direct method. So could you please send me the document around it so that we can try this feature. Also please send me the request model what I need to pass to Direct Method. 

Regards
Sachidanand Sharma

**Comment by arsing** [comment]
I think we don't have docs on MSDN yet. @veyalla ?

**Comment by veyalla** [comment]
This is an experimental feature so we don't have official docs for it. UploadLogs is available in 1.0.8 and here are the dev docs for it: https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md

1.0.9 adds a GetLogs method which returns the logs inline with the response instead of uploading to blob store, we'll update the doc above with usage for it when 1.0.9 transitions to stable (presuming feature testing goes fine).
