### ISSUE TITLE
Environment Variables in deployment.template.json

### ISSUE THREAD

**Issue by DoychinDoychev** [Azure/iotedge#1756]
## Expected Behavior
```
"modules": {
          "MODULE-NAME": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "env": {
              "VAR": {
                "value": "$VAR"
              },
              "VAR_ONE": {
                "value": "${VAR}"
              },
              "VAR_TWO": {
                "value": "$(VAR)"
              }
            },
            "settings": {
              "image": "some-image",
              "createOptions": {
                "Env": [
                  "VAR=$VAR",
                  "VAR_ONE=${VAR}",
                  "VAR_TWO=$(VAR)"
                ]
              }
            }
          }
        }
```
The expected behaviour is that the deployment template can pick environmental variables when they are requested from either the `env` for the iot module OR from `Env` in the create options for the docker container. However, neither of these options work.
## Current Behavior
References to environment variables are treated as string values

## Steps to Reproduce
Use the sample module template referenced in the `Expected Behavior` section
## Context (Environment)
IoT Edge Simulator running on VSCode
### Device (Host) Operating System
MacOSX

### Container Operating System
node:lts-alpine

### Runtime Versions
Version - 1.0.8.1.24554792
#### iotedged
Version - 1.0.8.1.24554792
#### Edge Agent
1.0.0

#### Edge Hub
1.0.0

**Comment by arsing** [comment]
Are you asking that the VSCode extension should expand env var references from the host environment when it generates the deployment file from the template? ie if your host has defined `VAR=5` and you have a deployment template with `{ "env": { "VAR": "$VAR" } }`, you want the resulting deployment.json to contain `{ "env": { "VAR": { "value": "5" } } }` ? cc @shizn in that case.

Or are you asking for the references to be resolved from the module's environment? ie if the deployment template has `{ "env": { "VAR": { "value": "5" }, "VAR2": { "value": "$VAR" } } }` then a process inside the running container should see `VAR2=5` ?

**Comment by DoychinDoychev** [comment]
Hi @arsing, thank you for the quick response.

I guess you are correct - I have a few questions.
Let me try and explain my ultimate goal and then see what are the other questions.

Ultimately, I'd like to have an azure devops release pipeline with 3 stages - DEV, STG, PROD.
I need each stage to be connected with its own pipeline library, where I specify variables related to each of the environments. Then I can reference these variables in my template and pass the info to my modules. So this is the high level goal.

I know that I can achieve that with a template engine like [mustache](https://www.npmjs.com/package/mustache). However, this is not an optimal solution to my issue.

To answer your first question (_"...you want the resulting deployment.json to contain { "env": { "VAR": { "value": "5" } } }..."_) - Yes I'd like the resolved template to pick up the host environment variable.  @shizn if you can assist with this, that'll be great.  I'd like this to work for both IoT simulator, which I use with VSCode as well as for pipeline deployments.

I'd played a bit with the `env` attribute of the module VS the `Env` attribute under `createOptions`. My understanding is that if I define a variable under `env` it will be pass to the container when i run it. Also if I pass a variable under `Env` it will be passed to the container. However, if i define a variable under `env` and i reference it under `Env` the variable is not resolved. I guess I don't fully understand the difference between `env` of a module and `createOptions.Env`. What is the difference between the 2 options and when one should be used vs the other?

Thanks

**Comment by arsing** [comment]
>My understanding is that if I define a variable under `env` it will be pass to the container when i run it. Also if I pass a variable under `Env` it will be passed to the container. [...] I guess I don't fully understand the difference between `env` of a module and `createOptions.Env`. What is the difference between the 2 options and when one should be used vs the other?

There is no difference. `createOptions` follows [Docker's spec,](https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate) so it has an `Env` key. The top-level `env` is just a convenient shortcut we created so that you don't have to type `"createOptions": { }` if the only customization you want to do is set some env vars.

Regardless of which one you set or whether you set both, they will be applied to the container's env when it is created.


>However, if i define a variable under `env` and i reference it under `Env` the variable is not resolved.

That is independent of whether you use `env` or `createOptions.Env`. Docker does not resolve `$` references within the env values like a shell would.

**Comment by DoychinDoychev** [comment]
Hi @arsing Thank you for your answer - it really clarifies things.

So just to confirm - if i want to have host dependent variables in my deployment.template.json i have to use template engine. Is this correct?

**Comment by arsing** [comment]
You have to generate the deployment.json with the values filled out. Whether you use a template engine for it, or just `jq`, or something else, is up to you.

**Comment by DoychinDoychev** [comment]
Thank you @arsing I'll close the issue now

**Comment by Gordonby** [comment]
Is there not a feature request here @DoychinDoychev ?

I'm authoring a deployment.template.json file, and wanting to make use of variables in the .env file as described in this issue, and as already implemented for the CONTAINER_REGISTRY_USERNAME and CONTAINER_REGISTRY_PASSWORD variables in the .env file.
The ability to make use of the existing templating build when "Generate IoT Edge Deployment Manifest" would be great, rather than the suggestion of using another templating engine for the new variables.

**Comment by heikki0** [comment]
@Gordonby, now when you mention feature requests, it would be helpful that one could use environment variables with some kind of simple logic so that one could at least combine strings, lets say VAR1=foo VAR2=bar and in the process of converting "${VAR1+VAR2}" from the template to the config file it would yield "foobar". Similarly that many .js templates do. 

Where one could discuss such a request? Thanks a lot with any guidance!
