### ISSUE TITLE
Edit stored Iot Edge modules 

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#1832]
Is it possible to edit Iot Edge modules that I have created some time ago ? I'm nodejs in my modules ...

**Comment by MPapst** [comment]
You can edit docker images if you want to. But this is considered bad practice.

A possibility would be to copy files into a container of the module (using ```docker cp```) and commit the changes (using ```docker commit```).
If you have got a container registry or use docker hub, you can overwrite the pushed image by just repushing the same tag.

**Comment by darobs** [comment]
Agree with @MPapst - this would be best served by pushing new module images and updating the module image tag in the Edge Deployment.  

Otherwise, updating files in a container and committing the changes is currently permitted, but we may have attestation in the future, which would prevent an altered container from being used.  It's not considered best practice.
