### ISSUE TITLE
Azure portal reports inconsistent message count for IoT Hub Usage

### ISSUE THREAD

**Issue by pkoronawa** [Azure/iotedge#1933]
When I refresh the IoT Hub Overview on the Azure portal, the number of messages reported in IoT Hub Usage is inconsistent. Refreshing repeatedly seems to bounce between 2 or 3 different values for messages received. They all increase at a reasonable rate, but I wonder what's going on?

**Comment by vipeller** [comment]
@pkoronawa gathering data (running queries) in a distributes system rarely gives accurate result. There are levels of "accuracy", and the more precise result we want, the more expensive to execute the query. The numbers you see is not the result of some sort of precise message counting mechanism, but it is based on a less expensive query.

Just an example (and this is not the way it is implemented): let's say that you have 1000 servers accepting incoming messages, and the distribution of the messages are sort of even. You want to get an idea how many messages you received yesterday between 6pm-7pm. One solution is to parse the related log sections at all the 1000 servers. Or you can assume that if you parse only 10 servers and project the result to the remaining 990 (that you can do because of the even distribution), then you can get a good number, but it costs only 1% to calculate it. Also, if you pick the 10 server randomly, and you run the query 5 times, you will get 5 different but similar numbers.
