### ISSUE TITLE
hsm-sys - time_t usage and year 2038 issue on 32bit devices

### ISSUE THREAD

**Issue by danigian** [Azure/iotedge#1960]
## Expected Behavior
Customers should be able to deploy their IoT Edge devices using certificates expiring after 2038.

## Current Behavior
Because of hsm-sys usage of time_t, on Linux 32bit devices it happens that time_t is using a 32bit number, making the device not supporting the certificates expiring after 2038 (tested with 2047 expiring certificate)

## Steps to Reproduce
1. Create a valid certificate expiring in 2047 
2. Use it for IoT Edge
3. See edgelet failing

### Device Information
* Host OS: Yocto Linux
* Architecture: arm32
* Linux containers 

### Runtime Versions
* iotedge 1.0.8.3

## Additional Information
Thanks to Philips Dynalite for reporting the issue

**Comment by alexeyzolotarev** [comment]
Hi All,

I'll add more details to this issue.

We have a device_ca.crt certificate, with expiry date in 2047, and a root  CA with expiry in 2059,
and we set these in the config.yaml

Basically, what happens, is that at the very beginning iotedged  daemon fails to start, saying that certificate has  already  expired  in 1969, Dec 31, 23:23:59   (which looks like a time_t value of  -1).
Independent check via Openssl confirms that it is a valid expiry date in the future

iotedge check  reports that   the field 'Not Before'  is invalid.

After investigating the debug logs the error was localized to certificate checking functions in hsm-sys,  so replacing  time_t with  int64_t  in all functions allowed us to partially solve the problem and start the  daemon.

Next issue  came again from   hsm-sys,  this time when  edgeAgent and edgeHub were pulled and started.  This time there was an errror in edgeHub saying there are issues with unable to get Trusted Bundle certificates due to unsupported  time format.
This happened to be the   hsm-sys  was only ready to process the ASN1_UTCTIME format (2 year digit), while it occcasionally get the date from our  root_ca.crt, which was a 4 digit year format,  ASN1_GENERALIZEDTIME.
Fixing hsm-sys to allow this additional time format resolved the unsupported certificate format.

attached is a patch applied on top of  edgelet 1.0.8.3, which shows and fixes the problem area.
We repaced the calculation of time from the ASN1_TIME string with corresponding OpenSSL conversion functions, trying to retain most interfaces unchanged. 

[fix_hsm_sys_y2038.zip](https://github.com/Azure/iotedge/files/3820153/fix_hsm_sys_y2038.zip)

**Comment by arsing** [comment]
(Inlined patch from https://github.com/Azure/iotedge/issues/1960#issuecomment-551110123 so as to not require downloading a zip file)

<details>
<summary>Click here</summary>

```diff
diff --git a/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c b/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c
index 2979be8f4..60ae99ef9 100644
--- a/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c
+++ b/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c
@@ -23,8 +23,8 @@ typedef struct CERT_DATA_INFO_TAG
     size_t private_key_len;
     PRIVATE_KEY_TYPE private_key_type;
     uint8_t version;
-    time_t not_before;
-    time_t not_after;
+    int64_t not_before;
+    int64_t not_after;
     const char* cert_chain;
     const char* first_cert_start;
     const char* first_cert_end;
@@ -56,6 +56,9 @@ static size_t END_CERT_MARKER_LEN     = sizeof(END_CERT_MARKER) - 1;
 // openssl ASN1 time format defines
 #define ASN1_TIME_STRING_UTC_FORMAT 0x17
 #define ASN1_TIME_STRING_UTC_LEN 13
+//Dynalite additions
+#define ASN1_TIME_STRING_GENERALIZED_FORMAT  0x18
+#define ASN1_TIME_STRING_GENERALIZED_LEN 15
 
 static void extract_first_cert_and_chain
 (
@@ -141,7 +144,7 @@ static void extract_first_cert_and_chain
     }
 }
 
-static time_t tm_to_utc(const struct tm *tm)
+static int64_t tm_to_utc(const struct tm *tm)
 {
     // Most of the calculation is easy; leap years are the main difficulty.
     int month = tm->tm_mon % 12;
@@ -156,8 +159,8 @@ static time_t tm_to_utc(const struct tm *tm)
     const int year_for_leap = (month > 1) ? year + 1 : year;
 
     // Construct the UTC value
-    time_t result = tm->tm_sec                      // Seconds
-        + 60 * (tm->tm_min                          // Minute = 60 seconds
+    int64_t result = ((int64_t) tm->tm_sec)         // Seconds
+        + 60 * (int64_t) (tm->tm_min                          // Minute = 60 seconds
             + 60 * (tm->tm_hour                         // Hour = 60 minutes
                 + 24 * (month_day[month] + tm->tm_mday - 1  // Day = 24 hours
                     + 365 * (year - 70)                         // Year = 365 days
@@ -167,22 +170,37 @@ static time_t tm_to_utc(const struct tm *tm)
     return result < 0 ? -1 : result;
 }
 
-time_t get_utc_time_from_asn_string(const unsigned char *time_value, size_t length)
+int64_t get_utc_time_from_asn_string(const unsigned char *time_value, size_t length)
 {
-    time_t result;
+    int64_t result;
 
     if (time_value == NULL)
     {
         LOG_ERROR("Parse time error: Invalid time_value buffer");
         result = 0;
     }
-    else if (length != TIME_FIELD_LENGTH)
+    else if ((length != ASN1_TIME_STRING_UTC_LEN) && (length != ASN1_TIME_STRING_GENERALIZED_LEN))
     {
         LOG_ERROR("Parse time error: Invalid length field");
         result = 0;
     }
     else
     {
+	struct tm target_time;
+	ASN1_TIME* asn1time = ASN1_TIME_set(NULL, time(NULL)); //allocate memory
+        memset(&target_time, 0, sizeof(target_time));
+
+	if(ASN1_TIME_set_string_X509(asn1time, (const char*) time_value) != 1) {
+            LOG_ERROR("Parse time error: Failed to set time structure 1");
+	    result = 0;
+	}else if(ASN1_TIME_to_tm(asn1time, &target_time) != 1) {
+            LOG_ERROR("Parse time error: Failed to set time structure 2");
+	    result = 0;
+	}
+	ASN1_STRING_free(asn1time);
+        result = tm_to_utc(&target_time);
+
+/*
         char temp_value[TEMP_DATE_LENGTH];
         size_t temp_idx = 0;
         struct tm target_time;
@@ -235,6 +253,7 @@ time_t get_utc_time_from_asn_string(const unsigned char *time_value, size_t leng
             }
         }
         result = tm_to_utc(&target_time);
+*/	
     }
 
     return result;
@@ -276,12 +295,13 @@ static int parse_common_name(CERT_DATA_INFO* cert_info, X509* x509_cert)
 static int parse_validity_timestamps(CERT_DATA_INFO* cert_info, X509* x509_cert)
 {
     int result;
-    time_t not_after, not_before;
+    int64_t not_after, not_before;
     ASN1_TIME *exp_asn1;
 
     exp_asn1 = X509_get_notAfter(x509_cert);
-    if ((exp_asn1->type != ASN1_TIME_STRING_UTC_FORMAT) &&
-        (exp_asn1->length != ASN1_TIME_STRING_UTC_LEN))
+    if (((exp_asn1->type == ASN1_TIME_STRING_UTC_FORMAT) && (exp_asn1->length != ASN1_TIME_STRING_UTC_LEN)) ||
+	((exp_asn1->type == ASN1_TIME_STRING_GENERALIZED_FORMAT) && (exp_asn1->length != ASN1_TIME_STRING_GENERALIZED_LEN)) ||
+	((exp_asn1->type != ASN1_TIME_STRING_UTC_FORMAT) && (exp_asn1->type != ASN1_TIME_STRING_GENERALIZED_FORMAT)))
     {
         LOG_ERROR("Unsupported 'not after' time format in certificate");
         result = __FAILURE__;
@@ -294,8 +314,9 @@ static int parse_validity_timestamps(CERT_DATA_INFO* cert_info, X509* x509_cert)
     else
     {
         exp_asn1 = X509_get_notBefore(x509_cert);
-        if ((exp_asn1->type != ASN1_TIME_STRING_UTC_FORMAT) &&
-            (exp_asn1->length != ASN1_TIME_STRING_UTC_LEN))
+        if (((exp_asn1->type == ASN1_TIME_STRING_UTC_FORMAT) && (exp_asn1->length != ASN1_TIME_STRING_UTC_LEN)) ||
+           ((exp_asn1->type == ASN1_TIME_STRING_GENERALIZED_FORMAT) && (exp_asn1->length != ASN1_TIME_STRING_GENERALIZED_LEN)) ||
+           ((exp_asn1->type != ASN1_TIME_STRING_UTC_FORMAT) && (exp_asn1->type != ASN1_TIME_STRING_GENERALIZED_FORMAT)))
         {
             LOG_ERROR("Unsupported 'not before' time format in certificate");
             result = __FAILURE__;
diff --git a/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_x509.c b/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_x509.c
index 0be5034f4..52aaa376a 100644
--- a/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_x509.c
+++ b/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_x509.c
@@ -229,7 +229,7 @@ static CERT_INFO_HANDLE create_device_certificate(HSM_CLIENT_HANDLE hsm_handle)
             double seconds_left = 0;
             time_t now = time(NULL);
 
-            if ((seconds_left = difftime(validity_seconds, now)) <= 0)
+            if ((seconds_left = (double)(validity_seconds - now)) <= 0)
             {
                 LOG_ERROR("Issuer certificate has expired");
                 result = NULL;
diff --git a/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c b/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c
index 5a7fa1939..890ebaee6 100644
--- a/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c
+++ b/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c
@@ -54,6 +54,11 @@
 #define ASN1_TIME_STRING_UTC_FORMAT 0x17
 #define ASN1_TIME_STRING_UTC_LEN 13
 
+//Dynalite additions
+#define ASN1_TIME_STRING_GENERALIZED_FORMAT  0x18
+#define ASN1_TIME_STRING_GENERALIZED_LEN 15
+
+
 struct SUBJECT_FIELD_OFFSET_TAG
 {
     char field[MAX_SUBJECT_FIELD_SIZE];
@@ -102,7 +107,7 @@ static void destroy_evp_key(EVP_PKEY *evp_key);
         X509V3_EXT_conf_nid((conf), (ctx), (nid), (value))
 #endif
 
-extern time_t get_utc_time_from_asn_string(const unsigned char *time_value, size_t length);
+extern int64_t get_utc_time_from_asn_string(const unsigned char *time_value, size_t length);
 
 //#################################################################################################
 // PKI key operations
@@ -782,14 +787,15 @@ static int validate_certificate_expiration
 )
 {
     int result;
-    time_t exp_time;
+    int64_t exp_time;
     double seconds_left = 0;
 
     *is_expired = true;
     time_t now = time(NULL);
     ASN1_TIME *exp_asn1 = X509_get_notAfter(x509_cert);
-    if ((exp_asn1->type != ASN1_TIME_STRING_UTC_FORMAT) &&
-        (exp_asn1->length != ASN1_TIME_STRING_UTC_LEN))
+    if (((exp_asn1->type == ASN1_TIME_STRING_UTC_FORMAT) && (exp_asn1->length != ASN1_TIME_STRING_UTC_LEN)) ||
+	((exp_asn1->type == ASN1_TIME_STRING_GENERALIZED_FORMAT) && (exp_asn1->length != ASN1_TIME_STRING_GENERALIZED_LEN)) ||
+	((exp_asn1->type != ASN1_TIME_STRING_UTC_FORMAT) && (exp_asn1->type != ASN1_TIME_STRING_GENERALIZED_FORMAT)))
     {
         LOG_ERROR("Unsupported time format in certificate");
         result = __FAILURE__;
@@ -801,7 +807,7 @@ static int validate_certificate_expiration
     }
     else
     {
-        if ((seconds_left = difftime(exp_time, now)) <= 0)
+        if ((seconds_left = (double)( exp_time - now)) <= 0)
         {
             LOG_ERROR("Certificate has expired");
         }
```

</details>

**Comment by danwale** [comment]
We've hit this issue as well, is there any update on when this will be resolved in a stable release?

**Comment by lt72** [comment]
@danwale @alexeyzolotarev The issue is with how __time_t__ is defined in glibc. We will not be able to change that.
We anticipate that we will issue a further release (likely 1.0.10) with a breakign change and move from time_t to [u]int64_t.

**Comment by alexeyzolotarev** [comment]
Hi  @lt72,  

The two issues fixed by the patch above are not related to time_t functions from glibc, but rather with the overflow in   calculations of seconds in hsm_sys, that is done manually.
Another issue was that OpenSSL could sometime return the extended ASN1 string format with 4 year digit instead of 2, (refer to ASN1_GENERALIZEDTIME   vs ASN1_UTCTIME).

It does indeed requires some re-work in function interfaces (so to avoid this in our patch we used the re-construction of asn1time  in get_utc_time_from_asn_string  function in hsm_sys code) but we are Ok for the larger re-work if it is needed, as we can use our patch for now (with some changes regarding the failure result return in  get_utc_time_from_asn_string).

**Comment by arsing** [comment]
I looked at the patch. It's doing two different things, hence the confusion.

One thing it does is change `time_t` to `int64_t`. This, as Lorenzo said above, is not something we're considering right now. We're assuming glibc will fix it themselves and we'll get it for free. Alternatively, you can of course compile iotedged and libiothsm against another libc of your choice that does have 64-bit `time_t`.

The other thing the patch is doing is changing the calculation in `tm_to_utc` (converts `tm` to `time_t`) to widen the fields of the `tm` struct to `int64_t` before using them for the calculation:

```diff
@@ -156,8 +159,8 @@ static time_t tm_to_utc(const struct tm *tm)
     const int year_for_leap = (month > 1) ? year + 1 : year;
 
     // Construct the UTC value
-    time_t result = tm->tm_sec                      // Seconds
-        + 60 * (tm->tm_min                          // Minute = 60 seconds
+    int64_t result = ((int64_t) tm->tm_sec)         // Seconds
+        + 60 * (int64_t) (tm->tm_min                          // Minute = 60 seconds
             + 60 * (tm->tm_hour                         // Hour = 60 minutes
                 + 24 * (month_day[month] + tm->tm_mday - 1  // Day = 24 hours
                     + 365 * (year - 70)                         // Year = 365 days
```

This *is* a legitimate bug in our code - since all the fields of `tm` are `int`, the calculation will be done in `int`, and only then widened to whatever width `time_t` has. We *should* be casting the fields to `time_t` first, just like this patch is casting them to `int64_t` first.

---

On that note, there is another bug here in that `tm_to_utc` returns `-1` to indicate an error, but the caller expects `0` to be an error. This means an overflowed value of `(time_t) -1` makes it all the way to iotedged, where it manifests as a cert expiring at 1969-12-31T23:59:59Z . It still fails because the cert is expired of course, but we should fix it to fail properly.

**Comment by arsing** [comment]
And another problem is that the `parse_validity_timestamps` also breaks post-2050 because it requires the `ASN1_TIME` object to be `ASN1_UNIVERSALTIME`, but openssl switches to `ASN1_GENERALIZEDTIME` for times past 2050 as RFC5280 requires. I guess we should fix that too.

**Comment by arsing** [comment]
Casting the intermediates is in https://github.com/Azure/iotedge/pull/2234 . That will let you use a cert expiring past 2038 (but before 2050) on a platform with 64-bit `time_t`.

For now, I'm not making the fix to also support certs past 2050. Ideally, by the time supporting such certs becomes an issue, we'll be able to mandate openssl > 1.1.1 which has `ASN1_TIME_to_tm` and get rid of the whole manual parser code entirely.

**Comment by arsing** [comment]
#2234 is in master so I'm relabeling this from bug to enhancement, because we're not going to do anything more about this for now.

**Comment by dme-development** [comment]
Was the fix for certificates between 2038 - 2050 already included in 1.0.9? I'm seeing the same problem on our arm64 device:

> openssl x509 -enddate -noout -in device.root.ca.pem
notAfter=Dec 31 12:50:37 2049 GMT

> journalctl -u iotedge
Mai 15 08:36:49 iotedged[29531]: 2020-05-15T06:36:49Z [INFO] - Edge issuer CA expiration date: 1969-12-31T23:59:59Z
Mai 15 08:36:50 iotedged[29531]: 2020-05-15T06:36:50Z [ERR!] - The daemon could not start up successfully: Edge device CA has expired or is near expiration
Mai 15 08:36:50 iotedged[29531]: 2020-05-15T06:36:49Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias:144

**Comment by myagley** [comment]
@dme-development the fix isn't in `1.0.9`. It is in `1.0.10`. A release candidate was just released. https://github.com/Azure/azure-iotedge/releases/tag/1.0.10-rc1 contains the packages with the change.

**Comment by Sdelausnay** [comment]
Hi,

I just tested the version  `1.0.10` and the solution to the 2050 problem is not implement. 

Is there another solution to solve this, seeing our customer has setup a complete PKI infrastructure with a Root certificate valid until 2050 and now they need to rebuild part of it to move the Root certificate to 2049. I guess this will become more and more a problem seeing the verification also applies to Root certificates.

**Comment by kpm-at-hfi** [comment]
I'm seeing the problem reported here when running 1.0.9.

* Does 1.0.10 include the fix?
* Is there a schedule for 1.0.10 to be released?
* Does the fix in 1.0.10 get us certs working <2050, but not =>2050?

```
me@device:~/certs $ openssl x509 -enddate -noout -in iot-edge-device-ca-full-chain.cert.pem
notAfter=Aug 22 22:07:20 2045 GMT

me@device:~/certs $ journalctl -u iotedge --no-pager --no-full
...snip...
Sep 03 15:40:39 device iotedged[9681]: 2020-09-03T14:40:39Z [INFO] - Edge issuer CA expiration date: 1969-12-31T23:59:59Z
Sep 03 15:40:39 device iotedged[9681]: 2020-09-03T14:40:39Z [ERR!] - The daemon could not start up successfully: Edge device CA has expired or is near expiration
Sep 03 15:40:39 device iotedged[9681]: 2020-09-03T14:40:39Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert…-workload-ca
Sep 03 15:40:39 device systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 15:40:39 device systemd[1]: iotedge.service: Failed with result 'exit-code'.
```

**Comment by kpm-at-hfi** [comment]
Also, this limitation of 1.0.9 (and presumably earlier) should be noted in documentation; for example [here](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs) and [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates).

**Comment by kpm-at-hfi** [comment]
Does this issue affect only the device ca cert itself, or is this a problem if **anything** in the device ca cert chain expires later than 2038?

**Comment by arsing** [comment]
>- Does 1.0.10 include the fix?

Yes, as myagley said above. See https://github.com/Azure/iotedge/blob/release/1.0.10/edgelet/hsm-sys/azure-iot-hsm-c/src/certificate_info.c#L147-L182

>- Does the fix in 1.0.10 get us certs working <2050, but not =>2050?

Yes, certs with 2038 <= not-after < 2050 will work in 1.0.10, and 2050 <= not-after will still not work.


>```
>Sep 03 15:40:39 device iotedged[9681]: 2020-09-03T14:40:39Z [INFO] - Edge issuer CA expiration date: 1969-12-31T23:59:59Z
>Sep 03 15:40:39 device iotedged[9681]: 2020-09-03T14:40:39Z [ERR!] - The daemon could not start up successfully: Edge device CA has expired or is near expiration
>```

I assume this log is from 1.0.9, because with 1.0.10 it'll fail with the correct error message of `Could not parse 'not after' timestamp from certificate` rather than thinking it's a cert that expired one second before 1970.

>Does this issue affect only the device ca cert itself, or is this a problem if **anything** in the device ca cert chain expires later than 2038?

It ought to be the device CA cert itself (ie the first PEM in the file) because that's the only one that's parsed.

**Comment by kpm-at-hfi** [comment]
Thanks for those responses, @arsing.

You're right... that is from 1.0.9. With what I'm doing I'm not able to move to 1.0.10 until it's actually released.

> It ought to be the device CA cert itself (ie the first PEM in the file) because that's the only one that's parsed.

Hmm. I did make a new device ca cert that expired prior to 2039 using an intermediate cert that expires in 2045. It still didn't work.

```
$ openssl x509 -enddate -noout -in iot-edge-device-ca-full-chain.cert.pem
notAfter=Nov 28 16:46:00 2038 GMT

Sep 03 17:50:45 device iotedged[1128]: 2020-09-03T16:50:45Z [INFO] - Edge issuer CA expiration date: 1969-12-31T23:59:59Z
Sep 03 17:50:45 device iotedged[1128]: 2020-09-03T16:50:45Z [ERR!] - The daemon could not start up successfully: Edge device CA has expired or is near expiration
Sep 03 17:50:45 device iotedged[1128]: 2020-09-03T16:50:45Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert…-workload-ca
Sep 03 17:50:45 device systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 17:50:45 device systemd[1]: iotedge.service: Failed with result 'exit-code'.
```

**Comment by arsing** [comment]
You're testing a cert that has not-after > 2038 with 1.0.9

**Comment by kpm-at-hfi** [comment]
Oh... I thought it was acceptable through the end of 2028. Thanks!
