### ISSUE TITLE
Edge Runtime install on windows - old version of Windows 10 required?

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/iotedge#1987]
The docs say that you can only install Edge run-time on the Windows 10 build 1809/17763.  Only.  :P  If you try and install Edge on a properly patched machine, the install fails since it says that the latest build (1909/18363) is not compatible.

It appears to be near impossible (or very well hidden) to take a machine (or VM) and update to not the current build.  Windows update will try and take it to 1909/18363, and if you try and download the Windows Media Creator it does the same thing.

Does anyone have any guidance on how to get around this?  To update to a not recent version of Windows OR to get the EDGE install to accept the latest version of windows?

Secondary effect: assume one does get a Windows machine onto 17763, the next Windows Update will blow away Edge will it not?

**Comment by dmefed** [comment]
As a side question, whether it is planned to add IoT Edge Runtime support for the latest 1903 Windows 10 build?

If yes, when approximately this could happen?

**Comment by veyalla** [comment]
@RotateAt60MPH You can use Windows Server 2019 eval during development: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019. This will remain on build 17763 which a long term support release.

@dmefed No plans, we intend to support only LTSC releases of Windows at this time. Please see this page for production supported OS list: https://docs.microsoft.com/en-us/azure/iot-edge/support#tier-1

**Comment by dallasakre** [comment]
@veyalla The solutions you have suggested are both terrible and do not reflect well on Microsoft.  The original post by @RotateAt60MPH is exactly the issue many of us will face and I would have thought that Microsoft was security conscious of IoT Edge devices and would therefore encourage Windows updates.  

Also, you didn't answer the last part of the question: 

> Secondary effect: assume one does get a Windows machine onto 17763, the next Windows Update will blow away Edge will it not?

**Also, you mentioned Windows Server 2019 eval during development, but what are we supposed to use for production then?**  You can't possibly suggest that we install Windows Server OS on all of our Edge PC's... and no Linux is not an option based on the existing applications that also run on the edge device.

**Comment by veyalla** [comment]
@dallasakre Few clarifications which may help:

* From the Tier 1 OS page I linked in the previous reply, on Windows 10 Desktop Client OS, only [Windows 10 **IoT** Enterprise](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise) is supported in production. This is a Windows 10 SKU licensed differently than Pro, Home or Enterprise (non-IoT) SKUs and usually available from OEMs. The non-IoT Windows 10 SKUs currently do not allow production use of Windows containers so they can't be used by IoT Edge in production.

* An [LTSC SKU](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise#long-term-servicing-channel-ltsc) will get regular security fixes but not new features like 1903, 1909...etc might. So there is a higher bar to stability and compatibility.

* Windows Server 2019 is similarly an LTSC release. And since it has a free eval version easily available, I suggested using it for development as it won't get feature updates past build 17763

**Comment by dallasakre** [comment]
@veyalla Thanks for the quick response, that is helpful.

**Comment by olovemaas** [comment]
Dear Veyalla. Thanks for the link to download Win Server 2019. I'll try it out.  However, you sure make it hard to use Microsoft software and spread the Edge technology when locking out users like this. This is not good way forward. KR Olov E

**Comment by RotateAt60MPH** [comment]
@veyalla 

Spinning up a evaluation version of Win Server is NOT a reasonable expectation for creating an Edge development environment.  What happens when that eval times out?  Reinstall another fresh eval version of Win server?  Seriously?

It shows a staggering amount of shortsightedness on the part of Microsoft to expect developers to base a development environment on EVALUATION software.  Is the Azure dev team so removed from the Windows dev team that there is no collaboration between them?

**Comment by TerryWarwick** [comment]
@RotateAt60MPH,

We are aware of the challenges with limiting support to Windows 10 build 17763 for developers on the semi-annual channel releases.  This is complicated by the requirement that the Windows container host and Windows container image versions must match due to sharing of the Windows Kernel. ([More Info](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-1909%2Cwindows-10-1909#matching-container-host-version-with-container-image-versions)) We have aspirations to loosen this requirement in a future release of Windows to make it easier for Azure IoT Edge to support multiple releases of Windows for both production and R&D.

In regards to working within these restrictions as a developer...  Windows 10 version 1809 (build 17763) is a long term servicing release which comes with a 10 year support lifecycle.  This edition is only available through Volume License as Windows 10 Enterprise LTSC and the commercial IoT OEM channels as Windows 10 IoT Enterprise LTSC.  Your best bet as a developer would be to setup a VM in Azure using the [Windows 10 Enterprise 2019 LTSC plan](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoftwindowsdesktop.windows-10?tab=PlansAndPrice) using a Volume License so that you can continue to keep your local system on current releases.  You could also use the  [Windows 10 LTSC Evaluation](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise), but that carries the same drawbacks as previously cited with the Server eval.

Terry Warwick
Microsoft

**Comment by RotateAt60MPH** [comment]
@TerryWarwick Well, it is refreshing to actually get an authoritative response to concerns.  Thanks for that!

For my team, the value proposition for IoT development erodes when another license for Windows (Enterprise) is required.  For sure, it would be ideal to leverage existing dev infrastructure for development since our team does not have licenses for Enterprise.

The acknowledgement that there is an awareness of this concern goes a long way to my confidence that this will be addressed.
