### ISSUE TITLE
One extra blob URL is being used in the Edge Runtime and that is not open on our proxy firewall 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#2042]
Hi Team
    We have seen that Edge runtime is using the blob URL for some purpose and that is not enabled on our Proxy firewall. So could you please let us know that for what purpose it is being used. And do we need to enable it on our firewall?? 
Also please let us know the full name of that storage account so that we can enable it on firewall.

**Comment by arsing** [comment]
What component are you seeing the access from? Is it iotedged? Edge Agent? Edge Hub? Moby engine?

If it's Edge Agent, it will access storage accounts for uploading logs if you use [the `UploadLogs` direct method.](https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md#uploadlogs)

If it's the Moby engine, you're likely seeing the storage account that hosts the `mcr.microsoft.com/*/ Docker images for Edge Agent and Edge Hub. (MCR is just a directory for ACR, and ACR hosts images on blob storage accounts.) In this case, I don't think we can tell you what the storage account really is, because it's auto-managed by ACR. (You obviously know what storage account it's accessing from your firewall logs, but there's no guarantee it'll remain the same in the future.) If you want control over this, you'll probably have to mirror the images to a container registry in your control.

**Comment by sachidanand** [comment]
Hi Team,
    We are getting this Blob being accessed by Mob-Docker .. So as you mentioned that MCR is using the blob storage under line so do we need to enable it on our firewall then.. Also could you give me more steps for mirroring the image to our ACR. 

Also I think then the ACR which we are using for custom modules then it would also use some storage account under the line right ???  Can we fix this storage account for our custom ACR ...

**Comment by arsing** [comment]
>Also could you give me more steps for mirroring the image to our ACR.

`docker pull` + `docker push`


>Also I think then the ACR which we are using for custom modules then it would also use some storage account under the line right ??? Can we fix this storage account for our custom ACR ...

For an ACR, yes, you'd probably be in the same boat that you're in now. I wasn't saying you have to use an ACR specifically. You can use whatever Docker container registry you want.

Alternatively, you have the option of whitelisting the whole `*.blob.core.windows.net` wildcard, or all IP ranges of Azure, as documented at https://docs.microsoft.com/en-us/azure/container-registry/container-registry-firewall-access-rules

Alternatively alternatively, you have the option of setting up a vnet and add your devices to that.
