### ISSUE TITLE
[documentation request] Abandoned message retry strategy of edgeHub

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedge#2053]
This is a documentation request and so not able to adhere to template. If a ModuleClient choses to temporarily reject a message using MessageResponse.Abandoned, edgeHub will retry delivery of the message after while. 
1. Is it possible to document the retry strategy (min period/max period/retry count) used by edgeHub for `MessageResponse.Abandoned` messages. 
2. Is the retry configurable?

To be sure: This query is not about retry strategy chosen by ModuleClient/client side code. This query is about edgeHub behaviour.

**Comment by varunpuranik** [comment]
Hi @kiranpradeep - we don't recommend using the MessageResponse.Abandoned pattern from the modules. The MessageResponse.Completed is used to send an ack to the EdgeHub to indicate that the message was received. 

If you want to defer processing a message, we recommend maintaining a separate queue of received messages, which can then be processed by the application.

Can you please elaborate on your scenario where you want to use MessageResponse.Abandoned? 

To answer your question - edgeHub will send un-acknowledged messages to the module with a timeout of 30s, which is an internal detail and not configurable. It will retry the operation till the message is acknowledged by the module.

**Comment by kiranpradeep** [comment]
@varunpuranik Thanks for the reply. As per the suggestion, we will not use edgehub queue. The planned scenario was to use edgehub internal queue as a persistence mechanism which we have dropped now.

**Comment by MarekLani** [comment]
@varunpuranik  please can you comment more on reasons why not to use message.Abandoned? Can you provide intended use of abandoning message?

**Comment by veyalla** [comment]
@varunpuranik can you PTAL?

**Comment by massand** [comment]
@MarekLani - great question!
To clarify:

- The intent of EdgeHub within Edge architecture is reliable message delivery between modules and IoT Hub. 

- The intent of the SDK MessageResponse codes is to provide common response codes to the sender of the message. The superset of MessageResponses will get returned to the message sender by EdgeHub. However, the subset of MessageResponses returned by message receiver that really make sense is Completed.

I will reach out to the C# SDK team to figure out more background on this API and maybe better documentation for this scenario. Closing this issue for now since it is pretty clear there is no intent to support abandoning messages from receiver modules.  

Related to this, we are investigating if EdgeHub is correctly returning Abandoned to sender modules when there is a true failure over AMQP. See #2813

**Comment by aalex21** [comment]
Is this statement still valid on the latest version of EdgeHub Behavior? 

From previous reply in this issue chain>>

@varunpuranik,

"we don't recommend using the MessageResponse.Abandoned pattern from the modules. The MessageResponse.Completed is used to send an ack to the EdgeHub to indicate that the message was received.

If you want to defer processing a message, we recommend maintaining a separate queue of received messages, which can then be processed by the application."

The scenario is same with the initial question - If a client module wants to defer processing a message, can this abandoned behavior can be used to utilize the edgehub storage/retry capability.
