### ISSUE TITLE
Transparent Gateway - Leaf Device Device-Twins question

### ISSUE THREAD

**Issue by DoychinDoychev** [Azure/iotedge#2071]
Hi there,

I went through the docs for iot edge but i couldn't find the answer to the following question:
```
I have a transparent gateway setup with one leaf device.
I want to set desired device properties for the leaf device from the cloud.
Will the traffic go through the edge or will it go on a separate channel, not related to the edge?
```

thanks

**Comment by varunpuranik** [comment]
Hi @DoychinDoychev - the leaf device can connect to EdgeHub on the IoT Edge device, and can get its Desired properties by doing a GetTwin() operation. It can also subscribe to the desired property updates ([SetDesiredPropertyUpdateCallbackAsync](https://github.com/Azure/azure-iot-sdk-csharp/blob/f5c5081f13a76cae25f691f547d0a276352e0629/iothub/device/src/ModuleClient.cs#L430)) so that the leaf device can get a callback if the desired properties are updated in the cloud. 

Does that answer  your question?

**Comment by DoychinDoychev** [comment]
hi @varunpuranik thank you for your answer. 

Let me confirm if i understand correctly - once the leaf device is connected to edge then all its communication goes through the edge, including:
- if desider properties are changed, that change will be communicated to the leaf via the edge
- if direct method is invoked from a backend service in the cloud,  that will be communicated to the device via the edge.

Do i understand this correctly?

**Comment by varunpuranik** [comment]
Yes, that is correct.

I will close this issue. Please re-open it if you have any other questions.
