### ISSUE TITLE
Production Certificates on an IoT Edge device

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#2225]
Hi, I want to use production certificates instead of the temporary ones, but I have no idea how to do it. I've read this document,  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-production-certificates.
In the Prerequisites it says that I need to: "Have a root certificate authority (CA) certificate, either self-signed or purchased from a trusted commercial certificate authority like Baltimore, Verisign, DigiCert, or GlobalSign.", but I don't know how to do it.

Does anyone has documentation or any tutorial to add a production certificate?

**Comment by philipktlin** [comment]
@veyalla do you have any documentation for production certificate setup on IoT Edge devices?

**Comment by veyalla** [comment]
Assigned to @eustacea

**Comment by eustacea** [comment]
Hi @Ilheu ,
A good starting point is to reach out to an IoT Identity certificate authority based on your risk assessment and ask for their issuance process.  What you need from them is a DeviceCA encoded in .pem file format as explained in the linked document you cite, and what they will need from you is your certificate parameter preferences e.g. expiration date.

If for example you chose Global Sign then their [IoT Identity Platform](https://www.globalsign.com/en/internet-of-things/) page would be a good starting point (and they would already be familiar with IoT Edge DeviceCA) and the page links you to their contact information.

It is this way now because IoT device certificate issuance and lifecycle management is emergent such that IoT Identity CA services providers have not coalesced around a single unified standard interface yet.

**Comment by Ilheu** [comment]
Hi @eustacea  and @veyalla! Thank you very much for your prompt reply. 
Basically I'm using the Azure IoT Edge to act as a transparent gateway, and I need to use a production certificate instead of an 30 day certificate. 
As I have understood it, to acquire a certificate, I can only do it using a fixed IP but it doesn't fit well in my solution ... Is there any alternative or solution that can help me?

**Comment by veyalla** [comment]
@Ilheu Based on the security needs of your installation, if you have determined that having long lived, self-signed certificates are acceptable, starting with 1.0.9 release one can set the certificate validity time in the daemon's [config.yaml](https://github.com/Azure/iotedge/blob/b0c0c72f2fe948e1175894db3c405d808e5e310e/edgelet/contrib/config/linux/config.yaml#L110).

**Comment by sachidanand** [comment]
What are the max days we can put into the expiry ???

**Comment by Ilheu** [comment]
@veyalla Thank you so much for the answer! 
I have already updated my iodedge version to 1.0.9, but the config.yaml stays equal, without the variable "auto_generated_ca_lifetime_days", should I add it by hand or is something I'm not doing well?

**Comment by Ilheu** [comment]
@veyalla and @eustacea  can you help me with this doubt?

**Comment by veyalla** [comment]
Sorry for the late response. Take a look a this thread: https://github.com/Azure/iotedge/issues/2340#issuecomment-579035307

**Comment by Ilheu** [comment]
@veyalla Thank you so much for the answers!!
Can you help me with this issue?
I was using Iot Edge as a transparent gateway, and suddenly the downstream devices stopped communicating, because there was an update and now I can only get the edge working without the certificates, I think it is generating its own certificates. How can my downstream devices send data to iotedge if they don't have the same certificates (because edge is generating its own certificates), and 
With this, my clients are not receiving the data they should.

**Comment by veyalla** [comment]
Looks like a different issue. Please create a new issue if you still need help with this.
