### ISSUE TITLE
Ubuntu iotedge debian (deb) package mishandles configuration file installation

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#2279]
I believe there is an issue in the current debian package for iotedge. I tested this on Ubuntu 18.04, but I am almost certain that other debian based distros are equally affected.

When installing `iotedge` package, dpkg installs the `/etc/iotedge/config.yaml` configuration file. Then, the `iotedge.postinst` debian maintainer script (which can be viewed in `/var/lib/dpkg/info/iotedge.postinst` on a system that already had the `iotedge` package installed) modifies the  `/etc/iotedge/config.yaml` configuration file **in place**. Such in place modification is not ideal, but not really a problem at this point.

However, imagine that at some point in the future, a new version of `iotedge` package is released **and that new version has some differences to the default  `/etc/iotedge/config.yaml` file**. When upgrading from the old version of `iotedge` package to the new version, dpkg will notice that the default config file is different and the `/etc/iotedge/config.yaml` is not the old or new default version. This causes dpkg to go into interactive mode (even if export DEBIAN_FRONTEND=noninteractive), printing out something like

```
Configuration file '/etc/configtest/configtest.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** configtest.conf (Y/I/N/O/D/Z) [default=N] ?
```

I believe there are actually two problems here:

1. Instead of modifying `/etc/iotedge/config.yaml` configuration file **in place** in `iotedge.postinst`, the debian package should instead be leveraging `debconf`. See http://manpages.ubuntu.com/manpages/precise/man7/debconf-devel.7.html
and http://manpages.ubuntu.com/manpages/bionic/man8/dpkg-reconfigure.8.html for more information
2. The `iotedge` package should allow for additional reconfiguration of `/etc/iotedge/config.yaml` after upgrade. Here is an example illustrating this problem. I want to create my own DEB package which depends on `iotedge` and in my package's postinst maintainer script, I want to further modify  `/etc/iotedge/config.yaml` and restart the iotedge service. Without my package knowing that `iotedge` was upgraded, my package can't possibly know that the `/etc/iotedge/config.yaml` was reconfigured by iotedge and now needs additional reconfiguration by my package. The correct debian way to do that is with triggers. See https://stackoverflow.com/a/15276537/4071435 which itself is based on
https://manpages.debian.org/buster/dpkg-dev/deb-triggers.5.en.html . If `iotedge` package is enhanced to issue a trigger on (re)configuration, then my package could listen for that trigger and take action.

Please let me know if you would like further clarification of the two problems. I can even try to help modify the iotedge debian package with you, if that is desired.

**Comment by arsing** [comment]
>This causes dpkg to go into interactive mode (even if export DEBIAN_FRONTEND=noninteractive), printing out something like

I'm surprised that it prompts even with `DEBIAN_FRONTEND` set. Are you sure you didn't do `DEBIAN_FRONTEND=noninteractive sudo apt update...` ? `sudo` will not pass the env var along.

Regardless, in a real non-interactive session (stdin not a tty), it won't prompt and default to `N` as the interactive prompt says - keep the user-modified file rather than overwrite it with the package's. This is in line with what we want. Specifically, we will never want a new `iotedge` package to remove the changes that the user made to their `config.yaml`, even if the new `config.yaml` has some new defaults. We'll also not want to make targeted replacements to check if the new defaults can be inserted into the `config.yaml` safely, because this is too much effort to get right. Basically any changes to the defaults will need to be explicitly added by the user.

That said, I'm not opposed to using `debconf` instead of the ad-hoc `sed` in `postinst`. Please send a PR.

(`debconf` would technically allow us to also ask for other parameters of the `config.yaml` directly, like the IoT Hub auth parameters. I'm hestitant to add this because from my experience of doing this in [the Windows installer,](https://github.com/Azure/iotedge/blob/26b90a102cf69d41ec005136d2b3393b0337ccaf/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L168-L279) it's [a bunch of brittle regexes](https://github.com/Azure/iotedge/blob/26b90a102cf69d41ec005136d2b3393b0337ccaf/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L1769) that I'd rather not propagate.)

>Without my package knowing that `iotedge` was upgraded, my package can't possibly know that the `/etc/iotedge/config.yaml` was reconfigured by iotedge and now needs additional reconfiguration by my package. The correct debian way to do that is with triggers.  [...] If `iotedge` package is enhanced to issue a trigger on (re)configuration, then my package could listen for that trigger and take action.

Can your package not do this by registering a trigger for `/etc/iotedge` without needing any change in the `iotedge` package?

**Comment by gri6507** [comment]
> I'm surprised that it prompts even with DEBIAN_FRONTEND set. Are you sure you didn't do DEBIAN_FRONTEND=noninteractive sudo apt update... ? sudo will not pass the env var along.
Yes, I intentionally did `sudo su -` before doing `apt install package`. Moreover, since I cannot induce the desired test using the `iotedge` package (there is only one deb in repos and therefore it has a fixed config file), I created a simple debian test package, with two debs one version with one config file and another version with another config file. It's a really simple test, but if you'd like I can share that with you.

> Can your package not do this by registering a trigger for /etc/iotedge without needing any change in the iotedge package?
The way debian triggers work is that there has to be a producer and a consumer. My package can be a consumer, but iotedge has to be the producer of the trigger.

>I'm not opposed to using debconf instead of the ad-hoc sed in postinst. Please send a PR.
I will send one shortly

**Comment by arsing** [comment]
>>Can your package not do this by registering a trigger for `/etc/iotedge` without needing any change in the iotedge package?
>
>The way debian triggers work is that there has to be a producer and a consumer. My package can be a consumer, but iotedge has to be the producer of the trigger.

For file path based triggers like the one I suggested, the producer is implicit.

**Comment by gri6507** [comment]
>>>Can your package not do this by registering a trigger for /etc/iotedge without needing any change in the iotedge package?

>>The way debian triggers work is that there has to be a producer and a consumer. My package can be a consumer, but iotedge has to be the producer of the trigger.

>For file path based triggers like the one I suggested, the producer is implicit.

I'm sorry for misunderstanding. You are correct. I modified my deb package so that I now have:


**debian/mypackage.triggers**
```
interest-noawait /etc/iotedge
```

**debian/mypackage.postinst**
```bash
if [ "$1" = "configure" ] || [ "$1" = "triggered" ]; then
  echo "doing my (re)configuration"
fi
```

**Comment by gri6507** [comment]
I created a PullRequest https://github.com/Azure/iotedge/pull/2301 for the above commit
