### ISSUE TITLE
Enable/Disable IoT Edge device via portal takes a long time to propagate to Edge module 

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#2334]
I have and IoT Edge module which listens for Module Twin changes, Connection Status changes, and Direct Module Method calls. When any of those callbacks happen, the event is printed to the module log with a timestamp.

In the web portal, at the device level, there is an option to enable/disable the device's connection to the IoT Hub.
![image](https://user-images.githubusercontent.com/11834450/72638343-dbf59000-3928-11ea-8d35-995dce8ce42e.png)

With the edge device in the enabled state, I can use the web portal to send Module Twin changes and Direct method calls, both of which are seen my my running module on that device. When I use the web portal and change my Edge device's "Enable connection to IoT Hub" setting from Enabled to Disabled and click the Save button, that change does not get propagated to the actual device for about 5 minutes. This means that I can still use the web portal to send further module twin changes and direct method calls even though the device is listed as "disabled". Is this typical? After approximately 5 minutes, the further attempts to send Module Twin changes or Direct method calls are no longer seen by my module. Is there any way to make that faster?

Furthermore, if I then use the web portal to change my Edge device's "Enable connection to IoT Hub" setting from Disabled to Enabled and click the Save button, that change does not get propagated to the actual device until the next time the module gets the next 

``` 
ConnectionStatusCb(status=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason=IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN)
```

which seems to be every 48 minutes! Until then, all further attempts to update the Module Twin 
 or send a Direct Module Method via the web portal are not seen by the module. That's a very long time to wait for what what the web portal shows as an "enabled" device. Is this expected? Is there any way to make that faster? After the next

```
ConnectionStatusCb(status=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED, reason=IOTHUB_CLIENT_CONNECTION_OK)
```
a single partial Module Twin change finally comes through, containing the delta between last online state and the state after re-connection (in other words, if the Module Twin had a field A that went from value 1 to value 2 and then back to value 1, then field A is not communicated in the partial update.

Related to the questions above, when a device is marked as Enabled on the portal, but the actual device hasn't yet reactivated (which, again, could be up to 48 minutes), there doesn't appear to be anything in either the Device Twin or the Module Twin that is visible in the portal to indicate that the pending changes have not yet been synchronized. Is there some way to see that from the cloud side?

**Comment by damonbarry** [comment]
> When I use the web portal and change my Edge device's "Enable connection to IoT Hub" setting from Enabled to Disabled and click the Save button, that change does not get propagated to the actual device for about 5 minutes...Is this typical?

I'm actually seeing different behavior. If I "disable" a device in the portal (set "Enable connection to IoT Hub" to "Disable") then try to, say, connect as that device and send a C2D message, I can't do it--IoT Hub returns 404 Device Not Found. But if I connect as a _module_ under that device, I _can_ send a C2D message. Also, if I'm running the Edge runtime as that device and disable it in the portal, the Edge runtime stays connected (`$edgeAgent` still responds to "ping" direct methods over an hour later).

The behavior I'm seeing is what I'd expect. The "Enable connection to IoT Hub" radio button in the portal is tied to the "status" property in the device's identity. You can see the value of "status" in the device's twin, but really it's a property on the core identity that's been around since before twins. The same property exists on module twins too, but I can't figure out how to change it (there's no radio button in the portal for disabling modules; only devices). Since Edge runtime only connects as modules and never as the device, the device status property doesn't effect the Edge runtime.

Also, the status property was never intended to be used to directly control device connections in real time, but rather as a simple management convenience; e.g. if you registered a device identity in IoT Hub but the corresponding physical device is going to be offline for a while (maybe because it was damaged, or because it was part of a research project that has been postponed until next quarter), you can disable it as a security precaution so no other device can connect using that identity. If a device is already connected when you disable it, I'd expect it to continue to work until its SAS token expires (48 min sounds like the right refresh period for a default one-hour SAS token).
