### ISSUE TITLE
How to install IoTEdge for centos7 ARM on raspbian Pi

### ISSUE THREAD

**Issue by onlinepy** [Azure/iotedge#2398]
I tried installing IoT Edge for Centos ARM32 on Raspberry PI. During installation of the libiothsm-std-1.0.9-0.1.rc3.el7.armv7hl.rpm
rpm -ivh libiothsm-std-1.0.9-0.1.rc3.el7.armv7hl.rpm
error: Failed dependencies:
libcrypto.so.1.0.0 is needed by libiothsm-std-1.0.9-0.1.rc3.el7.armv7hl
libssl.so.1.0.0 is needed by libiothsm-std-1.0.9-0.1.rc3.el7.armv7hl

**Comment by arsing** [comment]
Yes, I can see the same thing in a `centos:7` arm32 container. The amd64 package installs fine.

And indeed the deps aren't the same:

```sh
$ rpm --query --requires libiothsm-std_1.0.9-0.1.rc3.el7.x86_64.rpm | egrep 'crypto|ssl'

libcrypto.so.10()(64bit)
libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
libcrypto.so.10(libcrypto.so.10)(64bit)
libssl.so.10()(64bit)


$ rpm --query --requires libiothsm-std-1.0.9-0.1.rc3.el7.armv7hl.rpm | egrep 'crypto|ssl'

libcrypto.so.1.0.0
libssl.so.1.0.0
```

CentOS arm32 and aarch64 are two of the three targets that use our custom Linaro images with  openssl compiled ourselves (since upstream doesn't ship cross-compilers). @darobs Do you know if these two targets were ever tested to work?

**Comment by arsing** [comment]
Talked with darobs offline. We confirmed that the mismatch between the amd64 and arm32/aarch64 packages has existed since the beginning, so those two arches were likely broken all this time.

I also confirmed that the situation with CentOS has not changed since I last looked at it; it still does not provide a usable cross-compiler itself, nor a cross-arch openssl devel package. So it appears we do have to use the Linaro compiler.

That said, it might be possible to build openssl using `rpmbuild` + the Linaro compiler with the src RPM of the `openssl-libs` package instead of our ad-hoc script, and hopefully that will end up referencing the right sonames.
