### ISSUE TITLE
Many releases missing assets

### ISSUE THREAD

**Issue by nanowireUK** [Azure/iotedge#2399]
Trying to deploy IoT Edge to Debian 9 OS. Version 1.0.8 is the lastest non-rc version with the required assets (and Moby is even only 1.0.7).

Is there a reason there isn't a full build of assets for each release?

**Comment by arsing** [comment]
1.0.8 does not have a Debian 9 package because it is not a tier 1 OS. We did upload a Debian 9 package for 1.0.7 for an unrelated historic reason. Otherwise we do not release Debian 9 packages.

If you want to install it on Debian 9, you will have to build it yourself.

(For 1.0.9-rc, we *are* releasing Debian 9 packages. It's not yet determined whether we'll also publish these to packages.microsoft.com when it exits RC or not.)

>(and Moby is even only 1.0.7).

I assume this is a typo, because Moby is version 3.0.x. In any case, the versions of the `moby-engine` / `moby-cli` packages are unrelated to the version of the `iotedge` package.
