### ISSUE TITLE
[edgeHub] Start modules after edgeHub is ready

### ISSUE THREAD

**Issue by adashen** [Azure/iotedge#242]
When starting an edge solution, our custom module (java) starts faster then edgeHub. So the first connection will fail.

## Expected Behavior
Edge could start modules when edgeHub is ready to avoid this kind of errors.

## Current Behavior
Module container is started without checking the readiness of edgeHub.

**Comment by damonbarry** [comment]
This behavior is by design. Modules need to be resilient to transient connection problems. Even if we guaranteed that Edge Hub would start first, custom modules would still need to "do the right thing" if Edge Hub went down at some later time. The same is true for any other modules you might need to communicate with, not just Edge Hub.

The better solution is to ensure your module retries failed connection attempts, and recovers for loss of connectivity.
