### ISSUE TITLE
Edge Transparent proxy 'TLS authentication error' 'Remote certificate invalid according validation procedure'

### ISSUE THREAD

**Issue by pietrobr** [Azure/iotedge#2910]
hi I'm following this tutorial: https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/Instructions/Labs/LAB_AK_12-setup-an-iot-edge-gateway.html

When I try to connect from the downstream device to the gateway I get this error: 'TLS authentication error

![image](https://user-images.githubusercontent.com/2890569/80751656-7ec5c900-8b2a-11ea-9bbc-f4fa4253232e.png)
' 
What can cause the certificate to be not valid? How to solve?

**Comment by yophilav** [comment]
Hi, 
It looks like the release version 1.0.8 is used in this tutorial. 
The release 1.0.8 version has a known TLS authentication bug that we fixed in the release 1.0.9. 
Could you please upgrade the system to the release 1.0.9? 

The upgrade instruction can be found here: 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge

You want these packages:
https://github.com/Azure/azure-iotedge/releases/tag/1.0.9

**Comment by pietrobr** [comment]
Thanks @yophilav updating to 1.0.9 solve the issue.

**Comment by darenm** [comment]
@yophilav Do you know who "owns" the preconfigured Azure Marketplace image **Azure IoT Edge on Ubuntu**? This VM is provisioned using the **Ubuntu Server 16.04 LTS + Azure IoT Edge runtime** image which is still using IoT Edge 1.0.8:
```bash
vmadmin@vm-az220-training-gw0001-dm200420:~$ iotedge --version
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
```
