### ISSUE TITLE
kubernetes edgeagent stops working after some days

### ISSUE THREAD

**Issue by iitsBergenol** [Azure/iotedge#2978]
## Expected Behavior
We are using the kubernetes helm chart to deploy an azure iot edge device with modules to our kubernetes cluster, see https://microsoft.github.io/iotedge-k8s-doc/examples/pervol_translation.html 
Then we update our deployed modules after code changes with azure pipelines and the azure iot Edge tasks. We generate a manifest with updated docker tags and deploy that to multiple devices.
We expect that to restart the updated modules with the new releases.

## Current Behavior
After a few days, the modules don't get updated by our pipeline anymore. We implemented a workaround that restarts the edgeagent, that fixes the problem. But we would like to get rid of that workaround

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy helm chart for iot edge to kubernetes
2. Deploy modules with deployment manifest
3. Wait a few days
4. Try another deployment

## Context (Environment)
Azure Kubernetes Cluster

### Device Information
* Kubernetes version: 1.15.10
* Host OS (nodepool) Linux, nodesize: Standard_DS2_v2 : 
* Container OS: python:3.7-slim-buster

### Runtime Versions
* iotedged:  repository:  azureiotedge/azureiotedge-iotedged   tag: 0.1.0-beta8
* Edge Agent:   azureiotedge/azureiotedge-agent:0.1.0-beta8
* Edge Hub: mcr.microsoft.com/azureiotedge-hub:1.0

## Logs

Unfortunately i didn't save logs in broken state. I can deliver that later on if required.

## Additional Information
I think current versions in edgeagent  and iotedged could help.

**Comment by dmolokanov** [comment]
Hi @iitsBergenol! Thanks for letting us know. While we are investigating this bug, could you please dump logs and attach to the issue when you face this behavior next time?

**Comment by iitsDelbruegger** [comment]
Hi @dmolokanov,
this is one edge device that broke during the last weekend:
![grafik](https://user-images.githubusercontent.com/56017849/82785900-c4dd2680-9e63-11ea-94a4-828f9b224587.png)

And here are the logs:
[iotEdgeStopsWorking.zip](https://github.com/Azure/iotedge/files/4675565/iotEdgeStopsWorking.zip)

**Comment by dmolokanov** [comment]
Thanks for the logs! It seems like all modules have wrong trust-bundle attached to a proxy sidecar. One way it could happen: your installation has a self-signed root CA generated by `iotedged` on a startup. When Edge module started a `trust-bundle` CofigMap created and attached to a proxy sidecar and everything works. 
For some reason (I don't see anything in logs though) `iotedged` got restarted, so it regenerated root CA. Old trust-bundles that attached to every module became invalid in this case. Your workaround works because when Edge Agent restarts it restarts all modules. After restart, all modules got a new trust-bundle.

There is a setting that can be configured to make `iotedged` re-use previous root CA and not regenerate a new one until expiration `iotedged.data.persistentVolumeClaim.name=iotedged`. 
You can set it up via helm chart installation:
```bash
helm install --repo https://edgek8s.blob.core.windows.net/staging pv-example1 edge-kubernetes \
  --namespace pv1 \
  --set "provisioning.deviceConnectionString=$connStr" \
  --set "edgeAgent.env.persistentVolumeClaimDefaultSizeInMb=5000" \
  --set "edgeAgent.env.storageClassName=azurefile"
  --set "iotedged.data.persistentVolumeClaim.name=iotedged"
  --set "iotedged.data.persistentVolumeClaim.storageClassName=azurefile"
  --set "iotedged.data.persistentVolumeClaim.size=100Mi"
```

**Comment by veyalla** [comment]
FYI, this information is noted [here](https://microsoft.github.io/iotedge-k8s-doc/examples/prereqs.html#persistent-storage-for-the-iot-edge-daemon-iotedged) and [here](https://microsoft.github.io/iotedge-k8s-doc/examples/ha.html)

![image](https://user-images.githubusercontent.com/22105760/82935272-a0f01280-9f41-11ea-97c2-33e26e97aeb0.png)

Closing this issue, please re-open if you still run into this problem after following the guidance.
