### ISSUE TITLE
Issue with IotEdge certificates

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#308]
Currently working on IotEdge transparent gateway in C#/.NET core and getting authorisation error. To figure out what is wrong, I hooked up into certification callback:

```
mqttTransportSettings.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>                {
                    return true;
                };
```
The argument *chain* provides a chain status, which indicates that signature of certificate is not valid.
I guess there is something to do with 512 key length.

Interestingly, machine cert-store has no validation errors (picture below on right), which means .NET Core 2.1 (which I use) does not use machine cert-store. Instead it uses user cert-store.

Then I installed the same chain into user cert-store. But that one indicates that there is some signature error. 

Confusing? Now it is getting even more interesting.

When I run the same code (with callback validation shown above) after installing same certificate chain in user cert-store, the C# code passes successfully validation of the chain, even if windows user cert-store validation does not pass (as shown in picture on left)

![image](https://user-images.githubusercontent.com/1756871/45678230-42507f80-bb36-11e8-871f-1413ab58694f.png)

I'm not sure if I can ask any question related to this. My feeling is, that all this is just too complicate and it does not help me feel good, when thinking about security and trying NOT to think about productivity.

How about some other easier security mechanism in context of transparent gateways? 
1. For example downstream device could use two connection strings. One for *edgeHub* and one for *iotHub*.
2. *iotHub* could accept all connections and pass through authentication to IotHub. (or similar)

#### iotedge version
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

**Comment by mrohera** [comment]
Hello @ddobric,
There is an issue with iotedge 1.0.0 related to certificates and this was fixed in iotedge 1.0.1. Essentially the problem manifested when switching around from running edge in the "quick start" mode and then setting up a "transparent gateway" and vice versa. This could explain signature error you alluded to above. Could you kindly give 1.0.1 a try and report any problem you are seeing?

How about some other easier security mechanism in context of transparent gateways?
Glad you bring this up :).

Currently we require that users use this format for the connection string:
'''
HostName=yourHub.azure-devices.net;DeviceId=yourDevice;SharedAccessKey=XXXYYYZZZ=;GatewayHostName=mygateway.contoso.com
'''

We are adding support in the next release of the Edge Hub where you can replace the yourHub.azure.devices.net with yourEdgeHub hostname and then do not have to worry about appending a GatewayHostName to the connection string. This should likely be made available in the 1.0.2 release of the Edge. This should simplify how devices connect to the Edge.

**Comment by ddobric** [comment]
Thanks for your feedback.
What is the recommended way to upgrade the iotedge runtime?

**Comment by mrohera** [comment]
Sorry for the delay in responding on this one. 

@chipalost is working on a doc to formalize this. I can offer a few resources to assist you in the interim:

* IoT Edge Releases Page: [https://github.com/Azure/azure-iotedge/releases](https://github.com/Azure/azure-iotedge/releases)

* To update the IoT Security Daemon
  * On linux machines to install the latest version
  ```
  $> apt-get update 
  $> apt-get install iotedge
  ```
  * On Windows machines, to install the latest version, you would need to first [remove](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#remove-the-iot-edge-runtime) and then [reinstall](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#remove-the-iot-edge-runtime).

* To update the Edge modules themselves (Edge Hub and Edge Agent), you can update your deployment to pick specific Edge Hub and Edge Agent image tags.
  * If you prefer to stick to tag version 1.0 ```ex. mcr.microsoft.com/azureiotedge-hub:1.0``` (not advised for production environments) you will need to remove the images on your local edge device using command ```docker rmi mcr.microsoft.com/azureiotedge-hub:1.0```. The next pull will obtain the latest images.

**Comment by chipalost** [comment]
Mahesh's comments on updating the runtime are pretty complete. You can also refer to the Azure Update blog post about the 1.0.2 release. We'll formalize instructions for updating the runtime into product documentation soon.

https://azure.microsoft.com/en-us/updates/iot-edge1-0-2/

**Comment by myagley** [comment]
I'm going to close this issue due to inactivity, but please feel free to reopen.
