### ISSUE TITLE
Sending pending telemetry messages on module termination

### ISSUE THREAD

**Issue by ewertons** [Azure/iotedge#3287]
This issue is being filed on behalf of @gri6507.

From the original filed on https://github.com/Azure/azure-iot-sdk-c/issues/1506

----------------

I have a module which queues up data to be sent to the cloud in accumulated batches via `IoTHubModuleClient_LL_SendEventAsync()` where I pass a completion callback function pointer. My completion function is very simple: `printf("Result is: %s\n",  result_msg(MU_ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result)));`

Typically, the result code is `IOTHUB_CLIENT_CONFIRMATION_OK`. However, I also want to flush any pending accumulated data in one last message to the cloud when my module instance is being updated due to a deployment policy change. I have a signal handler in my module which catches TERM signal that iotedge runtime sends when the old module instance is being stopped. I added a call to send my unsent accumulated data into this signal handler. However, no message goes out and the callback function prints `IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY`.

What is the correct way to send a telemetry message **when** the module is asked to terminate for any reason (e.g. due to upgrade)?

**Comment by and-rewsmith** [comment]
Have you created this module in a way where you can actually handle the signal? If the container starts in a way where your program is called by another process, there is no guarantee that this process forwards the sigterm it receives from iotedged.

**Comment by gri6507** [comment]
@and-rewsmith Thank you for the response. My container was created with the following at the end of the Dockefile
```Dockerfile
USER moduleuser
CMD ["./my_module"]
``` 
I know that my module receives the SIGTERM signal, so I do not believe the problem is the mean by which the container starts my module executable.

**Comment by and-rewsmith** [comment]
I have never seen IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY before, but I am guessing that the module connection was dropped.

Here is my understanding of what should happen in this scenario:
- iotedged issues sigterm
- custom module handles sigterm and attempts to drain messages
- because edgehub has no reason to disconnect the client, then the module client stays active and drains its messages

I don't see why the module client would get disconnected before the container shuts down. It seems unlikely, but is it possible EdgeHub is restarting at this time? That might explain the loss of connection.

**Comment by and-rewsmith** [comment]
I just tried this scenario with the C# SDK and everything worked fine. I think this may be an issue with the C SDK.

**Comment by and-rewsmith** [comment]
Specifically, what I tried was handling the SIGTERM and doing the following:
- sending messages from an existing module client
- disposing this module client, creating a new one, and sending more messages

This is why I think the problem is not on our end. It doesn't look like we are doing anything to inhibit ModuleClient from sending messages. Feel free to re-open if you have additional information.
