### ISSUE TITLE
edgeHub failed to run when ECC Device CA key is used  

### ISSUE THREAD

**Issue by RaymWong** [Azure/iotedge#3371]
Provide a general summary of the issue in the Title above
--> edgeHub failed to run when ECC key type is used in the device CA key. The edgeHub works fine when RSA key is used

## Expected Behavior
EdgeHub should start and running and edge module can be deployed

## Current Behavior
edheHub failed and edge modules failed to deploy

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. generate ECC key
openssl ecparam -out $DEVICE_CA_KEY.pem -name prime256v1 -genkey
2.
openssl req -new  -key $DEVICE_CA_KEY.pem -subj /CN=DeviceCA -out $DEVICE_CA_KEY.csr
3.
Sign the above CSR with any CA and get the device_cert.pem
4.
modify config.yaml to use the URI point to the above devcie_cert.pem and the private key.

5. sudo systemctl restart iotedge

<img width="166" alt="Picture1" src="https://user-images.githubusercontent.com/46432420/89653974-83a0d280-d8fa-11ea-9d82-207a8e41a630.png">

<img width="454" alt="New Bitmap Image (2)" src="https://user-images.githubusercontent.com/46432420/89654684-9667d700-d8fb-11ea-85b5-c5f45b5838e4.png">

**Comment by massand** [comment]
@RaymWong - there aren't enough logs to see why EdgeHub is failing to start.  Please follow the issue template and gather the edgeHub logs for us to investigate. 

One area to look into is clearing leftover certs from a previous deployment. In order to generate new workload CA and Edge certs based on the new device CA cert (with EC), you should wipe the current certs under `/var/lib/iotedge/hsm/certs/`.

**Comment by massand** [comment]
@RaymWong - can you report back if the old certs from previous deployment were causing the issue? Or follow the new issue template and gather required logs?

**Comment by RaymWong** [comment]
> @RaymWong - can you report back if the old certs from previous deployment were causing the issue? Or follow the new issue template and gather required logs?

I have cleared the previous certs and keys  at location /var/lib/iotedge/hsm/ and tried using ECC and RSA key types.
The RSA key is working fine whereas ECC key does not. I will try to collect the log again if possible. Thanks.

**Comment by RaymWong** [comment]
> @RaymWong - can you report back if the old certs from previous deployment were causing the issue? Or follow the new issue template and gather required logs?

[log.txt](https://github.com/Azure/iotedge/files/5084456/log.txt)

**Comment by massand** [comment]
@RaymWong - The `iotedged` logs you attached seem to check out fine, in terms of new server certificate generation. But, I did not see edgeHub's `/sign` workload API request, which is expected before it connects to IoT Hub. Could you provide the EdgeHub module logs corresponding to the launch failure? 

Two steps to achieve this - 
1. Set the following environment variable in the deployment manifest (e.g. via Azure portal > IoT Hub > IoT Edge > Device details > Set Modules > Runtime Settings):
```
 RuntimeLogLevel: debug
```
2. Restart IoT Edge (`sudo systemctl restart iotedge`) and gather the logs on device using `iotedge logs edgeHub`

**Comment by massand** [comment]
@RaymWong - I suspect you are hitting an issue because EdgeHub does indeed only support server certs with RSA private keys 
 https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs#L341

When you look at the EdgeHub logs, I suspect you will hit the exception in the `ParseCertificateAndKey` function above. I will discuss next steps with the team.

**Comment by massand** [comment]
This is fixed in master, which should be picked up in a subsequent release.

**Comment by corollaries** [comment]
@massand Any ETA on the release? We're currently experiencing this issue as well which is a major blocker for us. Is there going to be a `1.9.*` release for this?
