### ISSUE TITLE
IoT Edge runtime is not downloading latest version of module image after its updated

### ISSUE THREAD

**Issue by has-taiar** [Azure/iotedge#364]
Hi there, 

I have an Azure IoT Edge device setup to `pull` an image from my `Azure CR`. It works fine and it pulls the `latest` image from the `Azure CR`. However, when I update this container on the `Azure CR` and push a new `latest` image. The Edge Runtime is not picking it up. Is this expected behavior?

Should I be setting modules by a specific tag name? I am thinking that using `latest` tag simplifies my `deployment.json` as I would not need to update it every time a new image is pushed. 

Hope to hear from you soon. 

Thanks
Has

**Comment by avranju** [comment]
Hi Has,

Yes this behavior is by design. The Edge runtime is designed to detect changes in deployments. So if nothing has materially changed in the deployment definition itself (even if something referred to from the deployment — such as the image definition referred to by a tag — changes) then Edge does not take any action.

So we have a the following options:

1. Use a unique tag for every image
2. Change the “version” property in the module’s entry to a new value every time
3. Delete the module from the deployment and then add it back

Or if this is during development then you could simply run “docker rm -f <module id>” and that should cause Edge to download the image afresh.

Raj

________________________________

**Comment by has-taiar** [comment]
Thanks for the prompt response @avranju, appreciate it. 

Do we have to remove the image before we added it again? I am setting up CI/CD, so I am hoping that once an image is updated, it will trigger a new `pipeline` in Azure DevOps which would then just increment the `tag` (which would be version/build number). Would that be sufficient for the Edge Runtime to pull the new / latest image? 

Thanks again

**Comment by avranju** [comment]
Yes that should be sufficient. Changing the tag in the deployment will cause Edge to detect the change and redeploy the module.

________________________________

**Comment by has-taiar** [comment]
Thanks again @avranju, 

Is that the best practice then? I was just concerned about updating the whole `deployment.json` file for one image as it might impact other modules inadvertently.

Thanks again for your quick reply. Much appreciated

**Comment by avranju** [comment]
Yes when image bits are updated it is a good practice to update the tag as well. And it should be safe to update the deployment, i.e., change just the tag for the module in question and leave all other module definitions in tact. Edge will only redeploy that one module that was updated.

Raj

________________________________

**Comment by malavvakharia** [comment]
@avranju  @has-taiar ,

There is one setting while deploying the custom iot edge module that is Image Pull Policy.

But there is no option to use always.

![image](https://github.com/Azure/iotedge/assets/48623627/6188b8dd-75bf-4773-95ca-ac4866e0b230)

Now what I need to handle scenario as @has-taiar ,If I push any changes to azure container registry it will not reflect in my iot edge device. So iot edge agent automatically detect that changes or how can I handle this type of scenario?

**Comment by utsav-blaze** [comment]
Hi , what would be the best practice to update my modules, weather i should try through CI/CD or Azure Device Update can also help me for this??
