### ISSUE TITLE
How to include SSL certificate in IOTEdge Module 

### ISSUE THREAD

**Issue by MohanGopi2010** [Azure/iotedge#3679]
We have a concept like WEB API as a iotedge module. We created it. In this web api iotedge module we need to use SSL certificate. 
Is their way to add this.

**Comment by robinmholt** [comment]
Short answer is yes.

Long answer is very-very long.  I sent you an email describing what we have done and what we currently don't have working, but it comes down to we have a ASP.NET restful API.  We create our listener giving it the location to a .PFX file and a password and the listener does come up supporting TLS 1.2.  The complexity comes from having unique certificates per device and the CN= and/or the Subject Alternative Name.  For our Web API, we set the Subject Alternative Name to a long string of descriptive text that is common to all of our modules.  Additionally, we have a PKI infrastructure which periodically issues refreshed certificates, but a well protected Root CA certificate.  We override host validation and replace the hostname with our SAN descriptive text.  We additionally restrict our root store to just the well protected Root CA certificate.

Our problem is that the certificate chain is not being published and is detailed more here:
https://stackoverflow.com/q/64246401/12195361

Also, this feels like it belongs in a different forum, but I don't know which one is most appropriate.

**Comment by massand** [comment]
Thank you for reporting. Based on the detailed description provided on your Stackoverflow post, I see this issue being more about module development and tooling specific to Windows Containers. The ASP.Net / Windows Containers community will likely provide better guidance on the other forums you have posted.

One suggestion I have is sharing the Dockerfile corresponding to your code in the Windows Containers MSDN post, so the community can figure out how your container is built. Non-admin users tend to need ACLs applied to specific folders or registry keys for performing crypto operations.

Closing this issue here since you have engaged the appropriate community for your issue.
