### ISSUE TITLE
[documentation request] Workload API

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedge#3724]
<sub>This is not an issue ticket and hence not following the template. This is only a documentation request. Kindly guide if the issues page is not appropriate for this type of requests.</sub>

Question: Is the Workload API intended to be used by customer applications? For e.g if I like to encrypt minimal data to be stored on device, can I start using `encrypt()` which is part of Workload API?

If yes, could the documentation of Workload API [[link](https://github.com/Azure/iotedge/blob/40f10950dc65dd955e20f51f35d69dd4882e1618/edgelet/workload/docs/WorkloadApi.md)] be extended and to help customer applications fully utilise them? For e.g. currently I don't know which key is used to encrypt data by the `encrypt()` API. E.g. I don't which key is used in the `sign()` API? What are algorithms supported by `key_id` field of sign()?  A little more info on create_identity_certificate() and create_service_certificate() will also help.

**Comment by massand** [comment]
The Workload API exposes APIs that are used by edgeAgent and edgeHub out-of-the-box. I don't believe there is an SDK support for leveraging these APIs yet because it isn't fully supported AFAIK. However, there is a [swagger](https://github.com/Azure/iotedge/blob/e10f76b390896f2a512ccd0d4b3c7adec4c95d77/edgelet/api/workloadVersion_2019_01_30.yaml) for it, which was used to generate C# client code for edgeAgent/edgeHub. 

One example of the encrypt/decrypt API is within [edgeAgent/edgeHub common logic](https://github.com/Azure/iotedge/blob/e10f76b390896f2a512ccd0d4b3c7adec4c95d77/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/EncryptionProvider.cs) which calls the [generated-and-wrapped workload client](https://github.com/Azure/iotedge/blob/da97168ce1529105422f5673e66dc184d95c6981/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs)

On the iotedge server-side of this workload API, the logic is all within the [edgelet-http-workload](https://github.com/Azure/iotedge/blob/d1048eb435bd6575c0518e44abd00de6186bc097/edgelet/edgelet-http-workload/src/server/decrypt.rs). The hsm-sys crate's HSM rust logic has the logic for [decryption](https://github.com/Azure/iotedge/blob/a272069cc4f28aa1b724f50b3460f0eab13cad42/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_enc_openssl_key.c) , but the summary is that each module gets its own encryption key and the module encryption key is derived from the master encryption key + module metadata (module_id + gen_id). The latter is defined in the [Rust edgelet-http-workload logic](https://github.com/Azure/iotedge/blob/d1048eb435bd6575c0518e44abd00de6186bc097/edgelet/edgelet-http-workload/src/server/decrypt.rs#L47). 

The swagger and swagger-generated documentation are currently the only documentation for this API. Hope the explanation and examples help some more. One thing to note is that if the edgeAgent and edgeHub are resilient to changes in encryption keys and I believe we don't currently validate the same module encryption keys persisting between releases.  So, best to keep your application resilient to a situation where the genid on your module identity changes and it invalidates the old encryption key- if that ever happens.

**Comment by kiranpradeep** [comment]
Thanks for the helpful reply. Looking at azure-iot-edge-identity-translation-lite[[1](https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite)] repo, I was getting an impression like Workload API was intended to be used by user modules. But from the reply, it feels more like, if user modules have to use the Workload API, we need to understand some amount of iotedge internals (e.g. genid) and also the swagger documentation is missing some details like allowed algorithms for sign() etc.
