### ISSUE TITLE
How to downgrade iotedge runtime?

### ISSUE THREAD

**Issue by davidguidali** [Azure/iotedge#3907]
Whats the proposed way to downgrade the installed iotedge runtime version w/o losing any caches (e.g. edge hub offline storage)?
I want to downgrade from 1.0.10 to 1.0.8. I tried with _Install-IoTEdge_ as well as _Update-IoTEdge_ and provided the 1.0.8 .cab file as parameter (offline installation). Both commands worked, but both did not really install the older version of the runtime.

Do I need to do an uninstall and re-install the old version? But this will delete the cache files, so I would need to back them up.

**Comment by arsing** [comment]
>Both commands worked, but both did not really install the older version of the runtime.

The parameter takes the directory containing the .cab file, not the .cab file itself. In older versions of the script it silently ignored this situation and went ahead and downloaded the latest CAB anyway. It was fixed later.

Note that you must use the version of the script that matches the package you're trying to install. ie you can't use a 1.0.x script to install a 1.0.y package. It may or may not succeed, and even if it suceeds the config.yaml is not guaranteed to have been generated correctly.

>Do I need to do an uninstall and re-install the old version? But this will delete the cache files, so I would need to back them up.

It'll only delete the Edge Hub storage if you left the storage inside the container instead of volume-mounting the storage directory to a directory on your host. We recommend production users to do that anyway - https://aka.ms/iotedge-storage-host

If you did volume-mount the directory to your host, then that directory is going to be left as-is even if the container is deleted as part of package uninstall - it's your directory so it has nothing to do with the package.

**Comment by varunpuranik** [comment]
@davidguidali - were you able to resolve your problem? If so, can you please close this issue?

**Comment by varunpuranik** [comment]
@davidguidali - I am closing this issue since we didn't hear back from you. If you run into any more issues, please feel free to open a new issue and provide all details as requested in the template.
