### ISSUE TITLE
What's the proposed way to upgrade security daemon and rutime?

### ISSUE THREAD

**Issue by imZack** [Azure/iotedge#3986]
In the issue https://github.com/Azure/iotedge/issues/3974#issuecomment-729160388, I've learned that mixing the version of security daemon (iotedged) and modules (edgeHub/edgeAgent) is not supported.

In the [Doc - Update the IoT Edge security daemon and runtime](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge?view=iotedge-2018-06#update-the-security-daemon), it shows how to update the security daemon & the runtime (which is the edgeHub/edgeAgent) separately.

How can we update the daemon first and runtime afterward if mixing versions are not supported?

**Comment by damonbarry** [comment]
@imZack I asked around the team, and it sounds like I misspoke in that earlier comment.

We do try to maintain compatibility between non-matching versions of Edge agent, Edge hub, and iotedged. But there are some caveats:
- If a version is out of support and you run into an issue, it might be difficult to get help for it.
- If a version is prerelease (for example, 1.2 is currently prerelease), that's similar to the out-of-support scenario _for production workloads_.
- When new versions introduce new features (for example, 1.2 has some pretty big stuff, like nested edge), the new features may require new versions of the other components, and therefore won't work in a mismatched environment. But older features should continue to work.

However if you're still interested in upgrading everything "atomically", you could do this:
1. systemctl stop iotedge
2. Deploy a new configuration that includes the new versions of Edge agent and Edge hub (updates will be made to Edge agent's twin, but since the agent isn't running it won't receive the update yet)
3. Upgrade iotedged
4. systemctl start iotedge

When iotedged starts, it will run whatever version of Edge agent is listed in your config.yaml. Once that comes online, it will get its twin and notice the new deployment. If necessary, it will instruct iotedged to get a new version of itself and restart. Then when it comes up again, it will download and start the rest of the modules.

**Comment by imZack** [comment]
Thank you @damonbarry for the clarification & suggestion on steps of upgrading atomically.

In terms of upgrading to the new version for different components, is there a matrix that can describe the dependeny? 
E.g. nested edge requires the security daemon version greater than a specific version and perhaps also note what's the incompatible versions we should avoid or migrate carefully.

**Comment by damonbarry** [comment]
For the current release, you can look at https://aka.ms/latest-iotedge-stable to see the current version of iotedged, Edge agent, and Edge hub.

There isn't a matrix (that I'm aware of) for 1.2, as it's still in preview.

**Comment by imZack** [comment]
Is the endpoint https://aka.ms/latest-iotedge-stable a permanent link? Can I find the definition of the JSON payload? Seems like the current stable version is mixed with `1.0.10.2` and `1.0.10.3`.

**Comment by damonbarry** [comment]
Yes it's a permanent link that points to https://github.com/Azure/azure-iotedge/blob/master/latest-versions.json. In the latest release, [1.0.10.3](https://github.com/Azure/azure-iotedge/releases/tag/1.0.10.3), there were only changes to the Edge agent and Edge hub modules, not to iotedged. So iotedged remained at version 1.0.10.2.

**Comment by imZack** [comment]
Thanks for the explanation. It's clear to me now.
