### ISSUE TITLE
IOT Edge Generic questions

### ISSUE THREAD

**Issue by ramakrpr** [Azure/iotedge#4193]
Hi Team,

I had few questions on the IOT Edge - specifically the way we intent to set it up. Our objective is to setup edge devices to use x509 authentication and device Hierarchy (one parent + multiple child edge stack devices)

1. We envision a hierarchail deployment - to start with One Parent (Connected to IOT Hub) and multiple IOT Edge Stack devices (Childs - in a secure zone / no internet access). The stack devices will communicate via the parent to Hub.
 - Given this scenario, we intent to follow the approach [here](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11&tabs=azure-cli)
 This version of IOT Edge (now in preview) we see the module IoTEdgeAPIProxy which facilitates the lower level devices to communicate with the parent. However the question is, then when is the below documentation applicable? Believe only when the devices need to communicate directly with the Hub and is behind a proxy?
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2018-06

I believe the need to facilitate communication via a proxy server for the stack devices (lower layers) will no more be applicable in our case and this is the same capability that is provided by the IoTEdgeAPIProxy module now in preview?

2. We plan to setup Enterprise CA based authentication for the Edge devices - basically following the documentation below
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manual-provision-x509?view=iotedge-2018-06&tabs=azure-portal%2Clinux

- The question is, every edge device we plan to add to the Hub (in our case the Parent + Child lower stack layers) need to go through this process correct?

3. As a pre-requesite for Enterprise CA based authentication, i dont see that the above link is asking to upload the Root/Intermediate CA to iot hub as per link below. I believe this is not applicable for Manual provisioning and is only for via Device Provisioning Service
https://docs.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates

4. The certificates which i need to use for authentication - i.e. whose thumbprints i provide while adding a new device should this be differnet from the actual Device CA certificate, which i will use later within config.yaml under section below
certificates:
  device_ca_cert: "<File URI path to the device CA certificate unique to this device.>"
  device_ca_pk: "<File URI path to the device CA private key unique to this device.>"
  trusted_ca_certs: "<File URI path to the root CA certificate shared by all devices in the gateway hierarchy.>"

5. Considering the requirment that we need to achive x509 authentication + hierarchial setup of edge devices (Parent+childs) i believe then we need the following certificates

Authentication
=============
 - 2 certificates per device (parent+childs) - whose thumbprints will be used for authentication while adding the device to hub

IOT Edge device hierarchy
=============
 - 1 device ca certificate and key for each device (parent+childs)
 - Intermediate CA + root CA certificates

**Comment by richma-ms** [comment]
@ramakrpr, 

A few things to unpack first, as the proxy setup can be understandably confusing atm.

There are two different kinds of proxies being referenced by the documentation.

The first is an [HTTP forward proxy](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2018-06), which is a customer supplied proxy implementation to be used in the traditional single-layer Edge setup in network environments where the Edge device does not have a direct internet connection.  When translated to a multi-layer hierarchical Edge setup, this means if the root / top layer Edge device does not have a direct internet connection, the forward proxy is necessary to provide the final leg of connectivity to IoT Hub.

The second, IoTEdgeAPIProxy module, is a _reverse_ proxy introduced to deal with hierarchical Edge devices deployed within the stringent requirements of a [Purdue network](https://en.wikipedia.org/wiki/Purdue_Enterprise_Reference_Architecture) environment.  In this environment, a given lower layer can only reach the immediate layer above/below it, and are not allowed to use a single forward proxy to reach the internet.  The reverse proxy then is in place to route specific traffic through each intermediate Edge device, which facilitates critical functionalities such pulling Docker images.

To answer your first question:
1. As mentioned above, you only need a forward proxy if your root Edge device is not allowed to connect directly to internet.

**Comment by richma-ms** [comment]
Your other questions are relevant to setting up x509 certs, which also kinda needs its own background explanation to clear up some confusion here.

There are two device authentication flows involving x509 certs, thumbprint (or self-signed) auth, and CA-signed cert auth.  The tutorial you're looking at is for thumbprint authentication, the relevant doc for CA-signed cert authentication is [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device?view=iotedge-2018-06#x509-ca-signed-authentication).

The advantage of CA-signed cert auth is that only the root CA cert is needed validate all client certs, as we only need to check at authentication time that the client cert was signed by the root or one of the intermediates.  There's no thumbprint involved, which means rotation of client certs does not require a change in iothub.

With thumbprint auth, the authentication challenge is just a straight up string comparison between the thumbprint calculated from the incoming client cert, and the previously submitted thumbprint in IoTHub.  So if the client cert changes, someone needs to make sure the corresponding thumbprints are also updated in iothub.

Note that CA-signed cert authentication as I described is not currently supported by IoTEdgeAPIProxy in the preview build, we're looking to have this addressed by GA.  But if you network setup requires deploying the reverse proxy module, then this will be a blocker for you.

To answer our remaining questions, I'm assuming what you're looking for is first auth flow:
2. Yes, every manually provisioned x509 device needs to go through the same setup.

3. See the documentation I linked for CA-signed cert auth, it does require the CA/intermediate to be uploaded to IoTHub even for manual provisioning.

4. There's no thumbprint involved.  What you'll need to do is include the CA cert as in the trustbundle on each Edge device when setting **trusted_ca_certs**, this is the equivalent of "uploading" the CA cert to iothub, but done for each Edge device so that it can validate the client certs presented by the incoming connection from children devices.  I'm not finding any detailed documentation on this, but it's identical to getting CA-signed cert auth to work in the single layer Edge setup, just repeated for each Edge in the lower layer.

I hope the lengthy explanations made sense.  You've unfortunately touched on two of the most complex aspects of Edge deployment, some of which is new and our documentation is still getting caught up.

**Comment by ramakrpr** [comment]
Hi @richma-ms  thank you for the detailed response.so if I make it short below are the conclusions- just to check if I got it right

1. For hierarchical setup in our case the parent will have internet connection but child’s won’t. In such a scenario we don’t need HTTP forward proxy but  IotEdgeApiProxy (reverse proxy) for hierarchies to communicate

**Comment by richma-ms** [comment]
@ramakrpr 

1. Correct
2. Connection strings is an option, the other is thumbprint auth as I described (which is a bit more secure than raw SAS keys in the connection string, but fundamentally not that different).
3. You need to fill in the "Manual authentication settings when using an X.509 identity certificate" section of config.yaml, which has properties where you can specify the IoT Hub hostname and the Edge device ID.

As for the portal UX, you should still be able to add a CA-certificate leaf device, it's just Edge devices does not have that option in the as you said.

**Comment by richma-ms** [comment]
Closing this one out, if you have more questions or feel free to re-open or post a new issue.
