### ISSUE TITLE
Transparent gateway- Offline device management

### ISSUE THREAD

**Issue by sanjeev-magoo** [Azure/iotedge#4531]
Hi,

We are working on a use case (Transparent gateway) where in gateway might run in offline mode due to security reasons. Definately, one time connectivity will be made available to register the edge device and leaf devices. But connectivity might be available or not available to edge device.

Now, we want to manage leaf devices even in the case when edge is offline. My questions-
1. can a module running in edge subscribe or intercept change in reported props of leaf devices? We want to show customer about update of device configuration (via reported props) in offline mode on a webportal (available within the same network, not on internet).
2. Can I query all leaf devices, edge device details such as deviceId, reported props etc via a module running on edge device in transparent gateway scenario? We want to show all devices connected to edge device on webportal with some device properties (when edge is offline), webportal is available on same network.

Can you please also validate following understanding-
1. Through edge, update of desired props is NOT supported. 
2. C2D messages are NOT supported through edge.
3. Module can call direct method of device.

**Comment by and-rewsmith** [comment]
> can a module running in edge subscribe or intercept change in reported props of leaf devices? We want to show customer about update of device configuration (via reported props) in offline mode on a webportal (available within the same network, not on internet).

The edge device maintains a local copy of the twin for modules and leaf devices, and will sync with the cloud copy when connection is restored. A module can only get its own twin, so you cannot create a module that intercepts other modules twin changes. Assuming your goal is to show device configuration updates on some custom-made portal, you will have to architect this a different way.

> Can I query all leaf devices, edge device details such as deviceId, reported props etc via a module running on edge device in transparent gateway scenario? We want to show all devices connected to edge device on webportal with some device properties (when edge is offline), webportal is available on same network.

You should be able to query all leaf devices and modules via the registry manager api, however you can only do this online. 
- modules:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.getmodulesondeviceasync?view=azure-dotnet
- leaf devices:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.createquery?view=azure-dotnet

If the webportal itself can access the internet to use the registry manager api, this will allow you to get all connected devices. But the gateways that are offline will not have synced their updates yet. You will have to use some custom solution to represent their state correctly, as the registry manager will be giving you outdated info.

> Can you please also validate following understanding
-Through edge, update of desired props is NOT supported.
-C2D messages are NOT supported through edge.
-Module can call direct method of device.

A couple notes:
- Modules cannot use c2d, but leaf devices connected to edge can use c2d and the message will indeed go through edge. 
- Modules can call direct methods of other modules via ModuleClient. However the docs indicate that you need to make a ServiceClient (requiring a cloud connection) in order to call a leaf device direct method. I feel like this might not be the case though and the docs could be wrong. If you use this api for calling module direct methods, and instead of the module id you plug in a device id, I think it might work. Waiting on other team members to confirm. @vipeller Is this possible?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.invokemethodasync?view=azure-dotnet#Microsoft_Azure_Devices_Client_ModuleClient_InvokeMethodAsync_System_String_System_String_Microsoft_Azure_Devices_Client_MethodRequest_

**Comment by sanjeev-magoo** [comment]
Thanks @and-rewsmith for your response. We are able to call direct method of device from module without a cloud connection.
