### ISSUE TITLE
Best Practice: Device subscription to messages processed by a module

### ISSUE THREAD

**Issue by zachcdr** [Azure/iotedge#4651]
Let's imagine I run a small cryofreeze operation out of my garage. I have twenty or so freeze tanks in which customers can lease to preserve their pet goldfish in a suspended state. Each one of these tanks is equipped with a temperature sensor that reports out a message: 
`{ "tankId": 1, "temperature": -20, "isOccupied": true }`

These messages are consumed by a module.

Additionally, I have a few employees. Each employee is outfitted with a tablet running "Cryo Fish" software. Each instance of this software is a registered device.

At any point in time, I might have one or many employees actively working and running their "Cryo Fish" software. Some employees are new and only assigned to one Cryo Tank while others are experienced and can manage several Cryo Tanks. I am curious as to if a single "Cryo Fish" software device can instruct the module that is processing the temperature messages to route messages to the device and what the best practice is to do that.

Use Case:
Employee A's software needs to event on messages where isOccupied is true
Employee B's software needs to event on messages where tankId is 6
Employee C and D are out of office and don't care about any messages

At any point, any employee can say "give me messages for criteria X" and can say "stop delivering me messages"

Thanks in advance.

**Comment by vipeller** [comment]
@zachcdr Hi. I assume that you would like to use the built in routing of edgeHub, which could be configured to route the messages depending on some message parameters (like isOccupied). The thing is that the routing system was not designed to be dynamic in the sense that it is changed frequently.

The routing configuration is part of the device twin of EdgeHub. Usually it is easy to change the twin (the desired properties section of the twin) of a module. But EdgeHub is a system module, and its desired properties section (where the routing configuration lives) cannot be changed the way than for other modules.

If you use the azure portal, you can see it that for a normal module you easily edit and apply the twin while for EdgeHub you need a new deployment, which is a much heavier operation. Also, you need a cloud connection for that. A "Cryo Fish" client cannot the module directly to change the routing, the client needs to tell the cloud to change the routing configuration (with a new deployment) and edge will notice the new deployment and downloads it and reconfigures itself.

Maybe I would recommend using the soon-to-be released 1.2 version (it is already available as release candidate). It has a built in MQTT server in it. MQTT dispatching is not that flexible than EdgeHub routing - while EdgeHub is able to apply complex rules on message parameters, MQTT is based on topics. It is a problem because in order to be able to receive every occupied tank data, the processing module (which receives all the cryo tank message) needs to filter and publish on a "occupied" topic, but also it needs to publish the same message let's say on "tank_1" topic if the tankId is 1. If there are several attributes, you see how it might be a problem to republish the same messages on several topics, according to the needs. Also, it is not too future proof - adding new attributes needs a change in the processing module, so it can republish the messages on the possible new topics.

In this case it seems easier just use the processing module as a relay module to publish on MQTT on a single topic, and all Cryo Fish gets and filters all messages (it it is not a security concern that the data actually reaches every device, it just filters it before it dumps the data to the screen)

Let' me know if you would like to further discuss the options

**Comment by zachcdr** [comment]
@vipeller Hey! To start, thanks so much for such a detailed and thorough response.

I was originally thinking that a given Cry Fish Software Device could send a message upstream to the module. This message would give the module some instructions like "I am device CryFish1, invoke the direct method "ReceiveCryoTankTemp", for all temp messages that meet criteria x, y, and z. The module would update the twin with this message, essentially appending it to a "subscribers" property in the twin's desired properties section. Then, for every temperature message that is received by the module, the module would check its twin for all subscribers. If the message met the subscriber's criteria, then the message would be sent via a direct method to the device and method listed in the subscriber details. 

To me, this felt clunky, which is why I thought I would ask here to see what the best practice is. 

Assuming I go with the routing built into EdgeHub, I believe it is possible to have all of my Cryo Fish software devices be named "cryofishdevicex" and I could route to these devices with a wildcard: cryofishdevice*

Within the device itself, do I subscribe to these messages with the device client's `ReceiveAsync()` method?

Thanks, again, for being so helpful with this. I hope others will find this discussion beneficial.

**Comment by vipeller** [comment]
Hi @zachcdr,

If you plan to implement the logic in the "processing module" which is able to decide that which client should get which temperature data (so basically the processing module would be a smart dispatcher, which knows which client should receive what messages), the the question is that when this processing module decided that CryoFish2 client should receive the actual temperature messages from Tank3, what the best way would be.

As you said, it is an option to the "processing module" to call a direct method with the data. This is useful if your processing module needs to be sure that the client application received the message (because method calls have return values, and the call (nt the C# SDK for example) waits for that result.

Other option is to send Module-to-Module messages. It is a bit inconvenient to set up, because every new client application needs a routing entry (for Edge built in routing capabilities), so the processing module would know where to send those messages. If we accept that this setup is needed for every new client instance, then the benefit of this solution is that even if a client is not ready to receive a message, Edge will take care delivering it later (when the client connects). I am not sure if this is a desired behavior or the feedback of the direct method call is the better.

A third option is to use the MQTT broker in version 1.2. In this case we talk about topics, and every client could have its own dedicated topic (e.g.  /messages/temp/CryoFish1). If the processing module wants to send a message to that client, it just publish the message on the specific topic. Note, that using the current C# SDK, you cannot publish messages on those topics. You need to you an MQTT SDK (any sdk you want) to send those messages. As Edge is a compliant MQTT broker (from version 1.2) it can work together any complaint MQTT clients. The link you referred is about the "old" MQTT support, where not the etire functionality but only a few IoT Hub related operations were supported.

Regarding how to store the client application subscriptions, if we are talking about "pre-mqtt", storing it in twin is possible as you described, but you can persist it on your device if you want (at the end your module is an ordinary application, it can do whatever it want/can on the given device).

If you decide to go with pure MQTT, the processing module does not need to care: the broker will know which clients are connected and which client has what subscription. The processing module just sends a message to /messages/temp/CryoFish1, and if no device is listening on that topic (e.g. the client is off), then noting will receive that message. The clients can create two different type of connections to the MQTT broker. If they want transient connection, and they are not connected, the message being sent when they are not connected will never be delivered to them. But clients also can chose to create a persistent connection, in that case when a client is not connected, the broker will keep collecting the messages, and once a client comes back (which previously in the previous connection subscribed to that topic), it will receive all the messages.

I suggest to take a look at a high level description of the MQTT protocol to see better the options, also let me know if you have any questions

**Comment by ebertrams** [comment]
@zachcdr , did @vipeller 's answer addressed your question? If yes can we please close this issue? Thank you!

**Comment by zachcdr** [comment]
@vipeller thanks so much for the responses. I believe this gives me enough to move forward and I will close out this issue.
