### ISSUE TITLE
[API Proxy] The api proxy module has hard dependency for the env that was used in the config

### ISSUE THREAD

**Issue by huanwu** [Azure/iotedge#4948]
Repro Step:
1. Add api proxy with default config or customized config
2. Remove the env from the module that was defined in the config e.g. BLOB_UPLOAD_ROUTE_ADDRESS

Expected:
Api proxy is still running well

Actual:
api proxy throw error unknown "blob_upload_route_address" variable.

**Comment by huguesBouvier** [comment]
The config template that you use has BLOB_UPLOAD_ROUTE_ADDRESS. By design BLOB_UPLOAD_ROUTE_ADDRESS need to be in the env var list, otherwise, API proxy doesn't recognize it as a variable and won't delete the code block that is missing.

We discussed the env var list designed, it could potentially be removed, however, we adopted it as a safety mechanism to prevent  variables being replaced by mistake. For custom config, you have to be specific about all the variables that you wish to be replaced.
