### ISSUE TITLE
Azure IoT Edge stop reconnect back to Azure IoT Hub

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#5064]
Hi,
   Not sure this behavior is by design or bug. My issue is:
   I have a Free tier Azure IoT Hub (8K messages per day), and it be connected by couple Azure IoT Edge devices. When the Azure IoT Hub reaches 8K message quota, all the Azure IoT Edge devices will be disconnect by Azure IoT Hub, this is make sense. 

   The problem is when 8K message issue be resolved, such as over a day, we found the Azure IoT Edge devices still remain disconnect. What we can do is to restart edgeAgent or edgeHub to make them reconnect to Azure IoT Hub.

    I would like to know the behavior (disconnect till restart edgeAgent or edgeHub) is expected or abnormal case.

**Comment by yophilav** [comment]
Let me check with my colleague regarding the expected behavior. 

From my personal experience, I have seen the device automatically recovered once the Quota limit was resolved. 
Do you have any exception handle in place such that the module may recover? 
If you would like, please feel free to open a support ticket and you can share the log/support-bundle there so we can further investigate.

Thank you!

**Comment by yophilav** [comment]
@KevinKao809  
I can try to reproduce the issue. What's your configuration? 
(Please refer to the issue template for the response: https://github.com/Azure/iotedge/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
