### ISSUE TITLE
JSON syntax error does indicate which file is responsible for error

### ISSUE THREAD

**Issue by shoter** [Azure/iotedge#5129]
## Expected Behavior
When there is syntax error then error message should also contain information about which file caused syntax exception.

## Current Behavior
Error only tells that something is wrong somewhere without specifically indicating which file is causing the error.
![image](https://user-images.githubusercontent.com/3819892/122550437-f22ee080-d033-11eb-872c-227c8191a0ec.png)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create some syntax error in your document
2. Use AzureIoTEdge to push module images to registry
3. You should receive error without information about which file caused the error

**Comment by dmolokanov** [comment]
Hello @shoter! Not sure I understood what are the steps to reproduce the issue. 
What doc are you modify?
What is the azdevops pipeline do you run?

**Comment by marianan** [comment]
Thank you @shoter for filing this issue. The error occurs during loading of the deployment.template.json at https://github.com/Azure/iotedgedev/blob/966e6ca47ba8c68c376b8b400ea7725bcd96abc0/iotedgedev/envvars.py#L106. At this time the underlying cli tool does not separate loading errors as there is only one deployment template file that is provided as an input. If that changes in the future we will consider providing more detailed error messages to assist users in identifying which file caused the error but at this time we are not planning on making such change.

**Comment by shoter** [comment]
@marianan This is fairly disappointing that there is no plan to make such a change. As an user using this job it is not clear to me which file is responsible for this without further explanation from your side. For me potential candidates are:
- deployment template
- deployment config file created based on deployment template
- module.json files of each module

This error does not clearly indicates that error lies within deployment.template.json therefore it is forcing user to analyze all of the files he suspects. As an user I do not have information that this kind of error might only appear when problem lies within template file as there is not such information in documentation.

**Comment by marianan** [comment]
@shoter thanks for clarifying the source of the confusion. I understand now that we indeed have a gap in our user experience for this scenario. I added this request to our backlog.

**Comment by shoter** [comment]
> 
> 
> @shoter thanks for clarifying the source of the confusion. I understand now that we indeed have a gap in our user experience for this scenario. I added this request to our backlog.

@marianan Happy to clarify that and happy to hear that it appeared in backlog. Thanks!

**Comment by shoter** [comment]
To my amusement error was not in any of the files I specified. I lost a lot of time to solve this issue.

I wrongly specified parameter azureContainerRegistry by filling it like that:        
```
 azureContainerRegistry: '${{ parameters.azureContainerRegistry }}'
```

The issue started I think because [official documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops#container-registry-types) is providing **wrong** template that is never going to work.

This issue mentions the same problem:
https://github.com/microsoft/azure-pipelines-tasks/issues/13442

That's why it is so important to know where error originates from!

**Comment by marianan** [comment]
@shoter we found that this specific article [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops) is not complete and we recommend using [this one](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment-classic?view=iotedge-2020-11) instead until we resolve the content.

**Comment by shoter** [comment]
@dmolokanov Is this issue resolved? I see you closed it.

**Comment by cindydeng1998** [comment]
@shoter We have investigated the error messages that our tool can provide for the following three files

- **deployment template**: the iotedgedev tool (which the CICD task uses) will return an error message similar to this one below if there are any issues with the deployment template. 

"Validating schema of deployment manifest.
Warning: Deployment manifest schema error: 'schemaVersion' is a required property. Property path:modulesContent->$edgeHub->properties.desired

- **deployment config file created based on deployment template**: since this file gets generated based on the template, that file will be the source of error 
- **module.json files of each module**: Our tool outputs an error log that shows which lines of the module.json file is causing an issue during build.

We are also working on a revamp of our documentation to give our customers a better experience, since the source of the issue came from an out of date documentation. We will continue to keep in mind of providing helpful error messages in future development. Thank you for your feedback.
