### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by suneetnangia** [Azure/iotedge#5153]
Documentation on detailed packaging aspect of identity service points to a dead link.

Originating Documentation Link: https://github.com/Azure/iotedge/blob/master/doc/packaging.md
Dead Link: https://azure.github.io/iot-identity-service/packaging.html

## Expected Behavior
Detailed packaging documentation link for identity service should be a valid link.

## Current Behavior
Detailed packaging documentation link for identity service points to dead link.

## Additional Information
Dead link is present under the following section https://github.com/Azure/iotedge/blob/master/doc/packaging.md#comparing-packages

**Comment by dmolokanov** [comment]
@arsing / @gordonwang0 Looks like we don't have Packaging page in the identity service repo anymore. Should we just remove the link?

**Comment by arsing** [comment]
I move that page from i-i-s's web docs to the non-web dev docs, because it doesn't matter for users, only devs.

For the iotedge page's table I suggest removing all the rows except "Command-line Interface", "Config files" and "Package dependencies", and remove the "aziot-identity-service" column. And yes, remove the sentence with the broken link.

**Comment by dmolokanov** [comment]
@suneetnangia Thanks for catching this! We are going to fix this. @arsing Thanks for suggestions!

**Comment by micahl** [comment]
Closing as the doc page no longer has a broken link to the identity service's package page.
