### ISSUE TITLE
Cannot invoke direct method

### ISSUE THREAD

**Issue by h3dgyy** [Azure/iotedge#534]
I am trying to call a direct method from the portal (VS Code doesnt work as well for me):

`Failed to invoke device method: {"message":"NotFound:{\r\n \"Message\": \"{\\\"errorCode\\\":404103,\\\"trackingId\\\":\\\"10b1e5037b1f4c3fb195d050ed89a147-G:5-TimeStamp:11/12/2018 19:35:33\\\",\\\"message\\\":\\\"Timed out waiting for device to connect.\\\",\\\"info\\\":{\\\"timeout\\\":\\\"00:00:10\\\"},\\\"timestampUtc\\\":\\\"2018-11-12T19:35:33.5194825Z\\\"}\",\r\n \"ExceptionMessage\": \"\"\r\n}"}`

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### Container Operating System
Linux

#### iotedged
iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
3.0.1

## Logs
`Failed to invoke device method: {"message":"NotFound:{\r\n \"Message\": \"{\\\"errorCode\\\":404103,\\\"trackingId\\\":\\\"10b1e5037b1f4c3fb195d050ed89a147-G:5-TimeStamp:11/12/2018 19:35:33\\\",\\\"message\\\":\\\"Timed out waiting for device to connect.\\\",\\\"info\\\":{\\\"timeout\\\":\\\"00:00:10\\\"},\\\"timestampUtc\\\":\\\"2018-11-12T19:35:33.5194825Z\\\"}\",\r\n \"ExceptionMessage\": \"\"\r\n}"}`

## Additional Information
My sample works when I use the `iotedgehubdev` tool

**Comment by myagley** [comment]
Hello. Is it possible to get the Edge Hub logs for this time period? `iotedge logs edgeHub`

Can you describe the scenario a little more? What is receiving the direct method, a module or device?

**Comment by jason-e-gross** [comment]
Just for reference:

I was also seeing this identical error this morning when I was trying to use direct method (from cloud to module) with an app service that's been doing it for a few months now -- and same result when trying to invoke it via the IOT Hub portal.

The error persisted after multiple restarts of the edge device (which usually clears up issues of DMs failing for me) -- but as of maybe an hour ago - it's all working agiain.   Maybe a hiccup in Azure IOT?

**Comment by veyalla** [comment]
@jason-e-gross On the Edge device's twin where you are observing this, is there any entry like:

`
 "deviceScope": "ms-azure-iot-edge://xxxxxxxx"
`

**Comment by jason-e-gross** [comment]
Yep, there is:
"deviceScope": "ms-azure-iot-edge://jg-lunchbox-636765911026121875"

**Comment by chriswaters78** [comment]
Running 'sudo systemctl status iotedge' also makes the Direct Methods start working again.

I have 6 devices running and this issue has affected all of them when I have tried to call some direct methods on them today.

**Comment by chriswaters78** [comment]
Sorry, I meant 'sudo systemctl restart iotedge' in the comment above.

**Comment by myagley** [comment]
For tracking, the underlying issue is: https://github.com/Azure/azure-iot-sdk-csharp/issues/571

**Comment by chriswaters78** [comment]
@myagley - I don't see any reference to just the inbound direct method calls being dropped on that ticket?

The same problem has just occurred again. I have had 6 devices running since I restarted them 4 days ago. The first time we have needed to send a direct method call since then and 3 out of the 6 have failed to respond, simply getting a 'timed out waiting for device to respond' message.

The whole time they have been happily sending D2C messages, it is just the C2D messages that fail. There is nothing in the edgeHub or edgeAgent logs that indicates a connectivity issue. SSH'ing to the device and restarting iotedge fixes the issue, but it seems puzzling that the hub module cannot detect this complete loss of connectivity itself.

We need this to be production ready as our customer is looking to go live very soon, now in fact, and we are in the embarrassing position of having to say that an Azure offering that has been in GA for nearly 6 months is simply not fit for purpose at present. However nice the edge framework is to develop for it absolutely has to be reliable.

I am going to write some additional code on our central hub to call these direct methods periodically and sends out an alert at the point they stop responding. I will also turn on debug tracing and hopefully this may give some more detail on what is actually happening when the connection is lost.

**Comment by lt72** [comment]
@chriswaters78 Hello, sorry for the very late answer. Do you still need help with this?

**Comment by chriswaters78** [comment]
@lt72 Hi, since the recent 1.8 releases things have been much more stable so no more help needed although I lost quite a lot of faith in the Azure IoT solution as it took a long time to fix this critical bug in what was supposed to be a GA release. I think #634 has more details.

**Comment by lt72** [comment]
@chriswaters78 I understand your concern, we are working to improve our turnaround time. Thank you for your feedback.
