### ISSUE TITLE
How Verify messages sent from IOT Edge to Cloud

### ISSUE THREAD

**Issue by nainesh72** [Azure/iotedge#5354]
Hi
How to verify that messages are sending successfully to the cloud, Because I get some duplicate messages on randomly time intervals and there are no fixed patient that i check 
Thanks 
Nainesh

**Comment by nlcamp** [comment]
@nainesh72 - Are you looking for a way to view the messages being received in the cloud by IoT Hub? If so, one tool you can use is the Azure CLI with the Azure IoT extension.

Instructions for installing the Azure CLI are available here:  https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

Once you have the Azure CLI installed, you can install the Azure IoT extension and use it to monitor the stream of messages flowing from your Edge device to your IoT Hub instance in the cloud:

```
az extension add --name azure-iot
az iot hub monitor-events -n <IoT-Hub-Name>
```

**Comment by nainesh72** [comment]
Hi
Sir, I need message received conformation because sometimes my edge hub send duplicate message to cloud or database, 
Thanks

**Comment by varunpuranik** [comment]
@nainesh72 - 
- EdgeHub stores every messages received from downstream clients (modules and devices), and sends an ack to the client when the message has been stored. This is to support offline scenarios, and ensure global at-least-once semantics. Because of that, the client does not receive an ACK or a notification when the message is sent to its destination (such as IoT Hub), as per the routes set on the EdgeHub. 
- Since EdgeHub uses QoS1 for the messages, it is possible for some messages to be sent twice (say in case the connection is lost before the ACK is received). This behavior is by design and not a bug. 

If you want to track which messages are sent, then you need to set the [MessageId](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Message.cs#L83) property on the message from the client, and then in the cloud you can check the messages by the messageId for duplicates. 
Please let me know if that answers your questions.

**Comment by nainesh72** [comment]
Hi
Thank, 
I know that if messages are not getting confirmation and meanwhile if the connection is broken then reestablish connection then the message is resend again on the cloud  so anyway on edge module which has to send message to IoT edge hub a get confirmation that message is sent to the cloud so we wait to send next message 
Note: Today I export my data from the cloud in the last 24 hour, there are three message are duplicate in my database, i send one of them
![image](https://user-images.githubusercontent.com/50742468/129912555-e38154e3-9009-4de5-b641-40b986f849c4.png)

Thanks 
Nainesh

**Comment by nainesh72** [comment]
Hi
thanks, Varun
I change my function to avoid duplicate records

**Comment by nainesh72** [comment]
Have any solution for get conformation that record are send to the cloud

**Comment by nainesh72** [comment]
Have any solution for get conformation that record are send to the cloud

**Comment by varunpuranik** [comment]
@nainesh72 - if you are looking for a way for a module or a leaf device to know when a message has been sent to IoT Hub, then unfortunately there is no such direct mechanism that IoT Edge supports. 
The reason is that from the module/leaf device standpoint, EdgeHub is the server (similar to IoT Hub), and once the message reaches the server, it is EdgeHub's responsibility to route it to its destination, such as IoT Hub. So you would have to build such a confirmation mechanism on top of IoT Hub primitives at the application level. 

Hope that answers your question.

**Comment by nainesh72** [comment]
Hi
Thanks for Replay But how I add message-id in payload, I send derail how i create message but how i add message-id please guide us

                    string dataBuffer = JsonConvert.SerializeObject(tempData);
                    var eventMessage = new Message(Encoding.UTF8.GetBytes(dataBuffer));
                    
                    eventMessage.Properties.Add("sequenceNumber", count.ToString());
                    eventMessage.Properties.Add("batchId", BatchId.ToString());
                    Console.WriteLine($"\t{DateTime.Now.ToLocalTime()}> Sending message: {count}, Body: [{dataBuffer}]");

                    await moduleClient.SendEventAsync("temperatureOutput", eventMessage);
                    count++;
Thanks 
Nainesh

**Comment by varunpuranik** [comment]
@nainesh72 - 
I am not quite sure what your question is. But you can set the MessageId on the message as so - 
eventMessage.MessageId = "<Some unique ID for the message>";

**Comment by nlcamp** [comment]
@nainesh72 - Please see the following reference material showing all of the properties that you can set on a `Message`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.message?view=azure-dotnet

As @varunpuranik has shown, the MessageId is a property on the `Message`.

**Comment by nainesh72** [comment]
Hi 
my question is how I add message-id, so I track on the cloud that message is duplicate, currently, I get a message on cloud following  

{"properties": {"sequenceNumber": "1","batchId": "69d58308-baa7-407e-aabd-c41152c393e8"},"systemProperties": {"iothub-connection-device-id": "Simulation1","iothub-connection-module-id": "IotEdgeModule1","iothub-connection-auth-method": "{\"scope\":\"module\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","iothub-connection-auth-generation-id": "637649967321226854","iothub-enqueuedtime": "2021-08-19T19:09:30.173Z","iothub-message-source": "Telemetry"},"body": "eyJtYWNoaW5lIjp7InRlbXBlcmF0dXJlIjoyMS44NzIyNzgyOTY2Nzg0NTYsInByZXNzdXJlIjoxLjA5OTM3MzQ3NjgzNjc4Nn0sImFtYmllbnQiOnsidGVtcGVyYXR1cmUiOjIxLjAwMzE4OTI1OTQ0MzA1NCwiaHVtaWRpdHkiOjI1fSwidGltZUNyZWF0ZWQiOiIyMDIxLTA4LTE5VDE5OjA5OjI5LjE3MjEyMjVaIn0="}

Thanks
Nainesh

**Comment by nainesh72** [comment]
Hi 
any solution for message receive on cloud get a conformation to edge module so i update my module logic that after getting conformation, module release second message to cloud

**Comment by nainesh72** [comment]
Hi
This is a connectivity issue, Mobin engine DNS not working so I give each module DNS then problem solved
