### ISSUE TITLE
Question about the IoT Edge hub server certificate's lifetime (created by the IoT Edge security manager)

### ISSUE THREAD

**Issue by apittier** [Azure/iotedge#5387]
Hello, 

I've followed the instructions from [Create demo certificates to test IoT Edge device features](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2018-06) for testing purposes and have extended the "default validity period" (by changing the `DEFAULT_VALIDITY_DAYS` value) to _365 days_.

After starting the edge runtime, I see that 3 certificates were created:

1. iotedge-tls_.cert.pem --> validity period = 90 days
2. iotedged-workload-ca_.cert.pem  --> validity period = _365 days_
3. edgeHub_.cert.pem --> validity period = 90 days 

(2) has 365 days validity period (as I was expecting) but then it called my attention that (1) and (3) don't. 

Taking from [Customize certificate lifetime](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2018-06#customize-certificate-lifetime) we have that:
> ! Note
> There is a third auto-generated certificate that the IoT Edge security manager creates, **the IoT Edge hub server certificate. This certificate always has a 90 day lifetime, but is automatically renewed before expiring**. The auto_generated_ca_lifetime_days value doesn't affect this certificate.

- I understand this refers to (3) and wanted to confirm that indeed "is automatically renewed before expiring"? How can I test this?
- What is the (1) created certificate? Is it supposed to renew automatically too? Can I test its renewal?

BTW, I'm working in an environment where "Installed IoT Edge daemon has version 1.0.8".

Thanks,
Amparo

**Comment by pmzara** [comment]
Thanks, @apittier for your questions!!! Let me check.

**Comment by arsing** [comment]
>- I understand this refers to (3)

Correct.

---

>and wanted to confirm that indeed "is automatically renewed before expiring"? How can I test this?

You could change your system clock to time travel to the future, just before expiry. Or you could generate your own cert with the same parameters (same CN, SANs, signed by the workload CA) but has a shorter expiry and replace this file with that.

---

>- What is the (1) created certificate? Is it supposed to renew automatically too? Can I test its renewal?

It's not used unless the workload API is configured to listen to an `https` URI, which in turn is not done unless iotedged is running in Kubernetes mode. In Kubernetes mode, the server listens on TCP sockets because modules are expected to be Kubernetes pods and would thus be connecting over TCP, so the server must enforce security by only serving TLS. In regular Docker mode, the server listens on unix sockets and modules run on the same device with access to said unix socket, so no TLS is needed.

The code that creates (1) ought to have been feature-guarded so that it's not compiled in docker mode (`#[cfg(feature = "runtime-kubernetes")]`) ...

**Comment by apittier** [comment]
Many thanks @arsing for your answers!
