### ISSUE TITLE
Problem with HSM failure and can't get trust_bundle for certificates in EFLOW

### ISSUE THREAD

**Issue by bryangregoire** [Azure/iotedge#5402]
**Describe the Problem**

Eflow states errors in logs about HSM failure and indicate he can't get trust bundle about certificates. They worked no problem within first deployment and the same type of certificates are used in production for IoT Edge 1.1 Windows binairies setup.

**To Reproduce**
Indicates certificates location in config.yaml to /home/iotedge-user/certs/..." 

**Expected behavior**
No certificates errors

**Screenshots**
![image](https://user-images.githubusercontent.com/87985593/130250033-4bec7be2-62e5-4465-8e7e-68f8be6188a2.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 IoT Enterprise 21H1
 - Version: 19043.1165
 - Virtual Machine: Physical
 
**Additional context**
No

**Comment by veyalla** [comment]
Hi @bryangregoire - quoting @arsing who looked into this:
>"Unsupported 'not after' time format in certificate" means certs with expiry after 2050 were used, which we don't support in 1.1

**Comment by bryangregoire** [comment]
Hi @veyalla !

My certificates are up to 2031-07-14... it should be OK no?

![image](https://user-images.githubusercontent.com/87985593/131531264-28e944da-cbb1-42da-b644-a536097b3dd8.png)

**Comment by veyalla** [comment]
@arsing?

**Comment by arsing** [comment]
I assume that's a screenshot of the device CA cert. What about the trust bundle certs?

**Comment by bryangregoire** [comment]
@arsing 

Here's the device identity certificate (for DPS): 
![image](https://user-images.githubusercontent.com/87985593/132004524-d0e6576a-4ade-4af4-8636-71c1d02dcd8d.png)

Here's the Edge internal CA certificate (in config.yaml): 
 ![image](https://user-images.githubusercontent.com/87985593/132004657-2e8b75cb-7474-491a-8829-dbc0b8a46d9e.png)

Here's the master CA certificate that generate the two previous certificates: 
![image](https://user-images.githubusercontent.com/87985593/132004742-e6495626-0919-453c-a179-e758da07859f.png)

Something wrong ?

**Comment by arsing** [comment]
2050-05-29 is after 2050

**Comment by arsing** [comment]
To elaborate on why 2050 is a problem: https://github.com/Azure/iotedge/pull/2234

>Aside: There is still a Y2050 problem even after this change. That is because
the code asserts that the times use the ASN1_UTCTIME type; this type uses
the format YYMMDDHHMMSS where 0 <= YY < 50 implies 20YY and
50 <= YY < 100 implies 19YY, and the code parses the string accordingly.
For years past 2050, openssl switches to ASN1_GENERALIZEDTIME which has
a four-digit YYYY.
>
>Rather than try to support both formats, we should stop parsing this structure
ourselves and just use `ASN1_TIME_to_tm`. We can't do this today because
the function does not exist before openssl 1.1.1, but hopefully that will
stop being an issue by the time supporting certs with expiry past 2050
becomes important.

Since 1.2 no longer uses the same code it doesn't have this problem. We don't plan to fix it for 1.1 LTS.

**Comment by bryangregoire** [comment]
Tanks @arsing for your explanation! It's strange because it's working with same certificates on Windows binairies of IoT Edge 1.1...
