### ISSUE TITLE
How to allow GPU passthrough like --GPUS all in native docker run, in Azure IOT edge config json?

### ISSUE THREAD

**Issue by spatra007** [Azure/iotedge#5737]
Hi

I need help in running my container that uses GPU, in IOT edge.

This is the command that I am using to run my image in native docker - 

sudo docker run --gpus all -it --privileged  -v /home/admin/template/:/data -e "display=1" --net=host --env="DISPLAY" -v="$HOME/.Xauthority:/root/.Xauthority:rw" test_image:v1

Could someone please help me to translate this to an equivalent deployment.json for IOT edge deployments?

**Comment by nlcamp** [comment]
@spatra007 - I'm closing this issue due to the lack of a response. Please note the following doc also has some info that you may find useful -- in particular, see the section about running `docker inspect` on your running container in order to determine the createOptions you'll need in your IoT Edge deployment manifest:

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-use-create-options?view=iotedge-2020-11
