### ISSUE TITLE
Monitoring the network connect/disconnect events

### ISSUE THREAD

**Issue by anoop18pant** [Azure/iotedge#5871]
hi,
i am using Azure iot edge runtime on my device and i want to implement one container which can glow the LEDs connected on my device based on following:
1. When device disconnects from IOT hub 
2. Network is lost

Basic idea is to implement a event monitoring on device side to blink LEDS. Any example code to monitor the network events will be of great help.

Can someone help how to implement this monitoring on device side.

**Comment by vipeller** [comment]
@anoop18pant Hello, unfortunately, edge does not propagate those events back (connect/disconnect) to devices/modules. One of the purposes of edge is actually to hide the case when edge gets disconnected form Iot Hub. When edge is disconnected, devices/modules still can pull a twin (even though it is only a stored version), they can send messages and property updates. The goal was with the design that devices (modules) should not be affected by edge being offline.

Because of this, it is quite hard to notice from a module/device that edge is not online :( At this moment I could not even tell a workaround, but let me think about it

**Comment by anoop18pant** [comment]
hi vipeller,

Thank you for your response. Can you please help in this ASAP its bit urgent.

**Comment by vipeller** [comment]
@anoop18pant would it be a solution that a device tries to access IotHub? E.g. the device (or module) tries to make a direct method call to itself through iot hub. If edge does not have the connection, most probably the device cannot call iot hub, but even if it can, the direct method call will not make its way back to edge if that is not connected. It is ugly I know, also needs polling (the device needs to monitor e.g every minute).

**Comment by vipeller** [comment]
@anoop18pant if you don't have more questions, I would close this ticket. Sorry, that the event you need isn't exposed.

**Comment by vipeller** [comment]
it is not supported, closing for now
