### ISSUE TITLE
iotedge check doesn't recognize moby version 20.10.10+azure-1

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#5872]
Since the moby engine might have a suffix (e.g. `-1`) behind `azure` in the version number the iotedge check reports 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/969523/143871730-646156d9-dea0-41ef-8521-fd5a8c39c541.png)

But indeed moby version 20.10.10+azure-1 should be recognized as production ready.

My guess is that the following code needs adjustment:

https://github.com/Azure/iotedge/blob/5015eca6d497e317a28ed0dc3bc013315c34b53b/edgelet/iotedge/src/check/checks/container_engine_is_moby.rs#L65

Please let me know if I was unclear or if I could contribute further information. Thanks in advance.

**Comment by huguesBouvier** [comment]
Thank you for spotting it. This PR should fix it.

**Comment by huguesBouvier** [comment]
I am closing the issue. After discussion with the moby team, we have decided to actually remove the check.
The reason is that they might change the versioning again in the future. Depending on what they do, we might not be able to differentiate moby and docker CE, so the best action is to remove a check that doesn't rely on solid grounds.
