### ISSUE TITLE
It seems DNS is not taken from system settings

### ISSUE THREAD

**Issue by ondrejspilka** [Azure/iotedge#6261]
## Expected Behavior
edgeHub shall takeover system setting of DNS servers. No need to setup docker.json daemon DNS record as indicated in [iotEdge FAQ for empty config](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2020-11#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device)

## Current Behavior
edgeHub can't connect to cloud, so edge receives **empty configuration**, subsequently error depicted in attached printscreen happens.
Especially in environments with transparent proxy but firewall filtering, where particular gateway and DNS is given by customer IT, setting DNS to 1.1.1.1 might fail.
Initially, even when system was configured by **nmcli**, edgeHub was not able to connect.
After explicit setting of `/etc/docker/daemon.json` to customer IT provided DNS, all works.

![image](https://user-images.githubusercontent.com/3624673/161942937-3c3daa0a-eda5-4341-bdac-bba4b51e7d4b.png)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. install iotEdge, latest greatest
2. put it after proxy/firewall which restricts global DNSs (1.1.1.1)
3. iotEdge edgeAgent will not connect
4. then, setup dedicated DNS/forwarder, use the address

## Context (Environment)
N/A

### Output of `iotedge check`

<details>
<summary>Click here</summary>

![image](https://user-images.githubusercontent.com/3624673/161944015-05228248-d39b-47dd-ab84-1cdc70071638.png)
</details>

### Device Information
* Ubuntu 18.04 TLS
* amd64, arm32, arm64
* Linux/moby

### Runtime Versions
* iotedge 1.2.5
* edgeAgent                        running          Up 18 hours      mcr.microsoft.com/azureiotedge-agent:1.2.3
* edgeHub                          running          Up 18 hours      mcr.microsoft.com/azureiotedge-hub:1.2.3
* Docker version 20.10.11+azure-2, build dea9396e184290f638ea873c76db7c80efd5a1d2

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by darobs** [comment]
Hi @ondrejspilka,

The example given in the documentation is not expected to be an exhaustive answer. Our team needs to configure the DNS to an internal DNS server for devices inside the corporate network, but we use a public DNS server for the example.

We place all modules except edgeAgent into a custom bridge docker network named `azure-iot-edge`. This lets the user look up modules by name in module code. However, this does affect how DNS works inside the container. [It uses Docker's embedded DNS service.](https://docs.docker.com/config/containers/container-networking/#dns-services)

According to the Docker documentation above, the default bridge network will automatically use the host's DNS configuration. If you want to switch to using the default "bridge" network, it's configurable in the config.toml: https://github.com/Azure/iotedge/blob/main/edgelet/contrib/config/linux/template.toml#L400

I am marking this as a "doc" issue because I'm sure our documentation could be more clear on this subject.

**Comment by darobs** [comment]
Closing this issue, please reopen if you have any follow-up questions. (Closing this issue won't stop this being tracked as a potential documentation improvement.)
