### ISSUE TITLE
Need a way to send device modelId

### ISSUE THREAD

**Issue by TahaSnoussi** [Azure/iotedge#6420]
Using the SDK, the device is able to announce it's modelId. Each module is also able to announce it's modelId.
Can't this be ported to device level with IoT Edge enabled devices?

**Comment by varunpuranik** [comment]
@TahaSnoussi : 
- As I mentioned before - by default, in IoT Edge, all workload modules use the module identities to connect to IoT Hub. They can expose their modelId (separate for each module)
- If you have a host level workload that uses the device Id, then it can also expose its modelId. 
- There is no concept of a uber modelId for all the workloads running on the IoT Edge device - this is because the device has multiple discrete components running on it. 
- The IoT Edge runtime components (EdgeAgent/EdgeHub) do not expose their modelId. 

Does that answer your question?

**Comment by varunpuranik** [comment]
@TahaSnoussi - please let me know if you have any further questions. If not can you please close this issue?

**Comment by micahl** [comment]
@TahaSnoussi are you expecting the device to be connected and managed via IoT Central?  Or is this for your own cloud application?

**Comment by TahaSnoussi** [comment]
@micahl I'm trying to use some features of Plug & Play without using IoT Central.
@varunpuranik I'm still trying to find a proper solution to make an IoT Edge Device announce its modelId but from your feedback that's a no go with current implementation. So you can close this issue.

What I implemented for now is the following:
- DPS
  The enrollement group contains a tag modelId (of the device)
- IoT Hub
  The device is provisioned with that tag
  The device sensor module sends telemetry with modelId (of the sensor) to the Hub that is routed to an external event hub
- Digital Twin
  An Azure Function creates a twin of the device modelId that has sensors as components
  An Azure Function treats the telemetry to update device twin sensor component that corresponds to that sensor modelId

This way, a Sensor module is represented by a component of a device in digital twin.
If I update a sensor to send additional telemetry, I update the model version (in the modelId) and update the device and sensor models in digital twin.

Do you think this is viable?

**Comment by micahl** [comment]
> This way, a Sensor module is represented by a component of a device in digital twin. 

@TahaSnoussi would having the Sensor module announce its own modelId not work for your scenario?  I'd like to better understand why using a [component](https://docs.microsoft.com/en-us/azure/digital-twins/concepts-models#components) on the device identity might be preferred to using the module.
