### ISSUE TITLE
On Debian10-Iot edgeHub StorageOnIotEdge failing after restart

### ISSUE THREAD

**Issue by radhegithub** [Azure/iotedge#6593]
My Iot edge runtime machine was working fine and all of sudden Stops working due to below errors:
1.  Issue : modules are failing due to timeout and runtime(iot edgeAgent and EdgeHub, StorageOnIotEdge)
2. Issue: When sending device to cloud messages more than 256KB then it is not processing, so how can i increase limit
I am using iot edge device as gateway with iot device

**Error Log Description:**
=================
scoutcam@vmdebiandev007:~$ iotedge system logs
-- Logs begin at Sat 2022-08-13 11:17:47 UTC, end at Sat 2022-08-13 14:03:52 UTC. --
Aug 13 13:37:00 vmdebiandev007 aziot-edged[6470]: 2022-08-13T13:37:00Z [INFO] - [work] - - - [2022-08-13 13:37:00.161518034 UTC] "POST /modules/%24edgeHub/genid/637953694007473268/decrypt?api-version=2019-01-30 HTTP/1.1" 500 Internal Server Error 36 "-" "-" auth_id(-)
Aug 13 13:37:01 vmdebiandev007 aziot-edged[6470]: 2022-08-13T13:37:01Z [INFO] - [mgmt] - - - [2022-08-13 13:37:01.481399601 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 OK 2986 "-" "-" auth_id(-)
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [INFO] - <-- POST /key?api-version=2020-09-01 {"content-length": "74", "content-type": "application/json"}
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [INFO] - <-- POST /decrypt?api-version=2020-09-01 {"content-length": "1007", "content-type": "application/json"}
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [ERR!] - OpenSSL error
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [ERR!] - !!! internal error
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [ERR!] - !!! caused by: could not decrypt
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [ERR!] - !!! caused by: could not decrypt: AZIOT_KEYS_RC_ERR_EXTERNAL
Aug 13 13:37:03 vmdebiandev007 aziot-keyd[6475]: 2022-08-13T13:37:03Z [INFO] - --> 500 {"content-type": "application/json"}
Aug 13 13:37:03 vmdebiandev007 aziot-edged[6470]: 2022-08-13T13:37:03Z [ERR!] - Internal server error: Failed to get identity
Aug 13 13:37:03 vmdebiandev007 aziot-edged[6470]: 2022-08-13T13:37:03Z [INFO] - [work] - - - [2022-08-13 13:37:03.182893687 UTC] "POST /modules/%24edgeHub/genid/637953694007473268/decrypt?api-version=2019-01-30 HTTP/1.1" 500 Internal Server Error 36 "-" "-" auth_id(-)

**Comment by radhegithub** [comment]
I performed these steps and Issue got resolved based on instruction provided: https://github.com/Azure/iotedge/issues/6537
this issue also comes in raspberry

In my case i had storage directory:

scoutcam@vmdebiandev007:~$sudo iotedge system stop
scoutcam@vmdebiandev007:/$ cd /etc/iotedge/storage/
scoutcam@vmdebiandev007:/etc/iotedge/storage$ rm -r edgeHub
scoutcam@vmdebiandev007:/etc/iotedge/storage$ rm -r edgeAgent
scoutcam@vmdebiandev007:/var/lib/aziot$ sudo chmod 775 /var/lib/aziot/keyd
scoutcam@vmdebiandev007:/var/lib/aziot$ cd keyd
scoutcam@vmdebiandev007:/var/lib/aziot/keyd$ cd keys
scoutcam@vmdebiandev007:/var/lib/aziot/keyd/keys$ rm -r *
scoutcam@vmdebiandev007:~$ sudo iotedge system restart

**Comment by arsing** [comment]
>In my case i had storage directory:

Yes, the failure to decrypt is expected if you don't clean the storage directory and redeploy the module or the device, because redeploying creates a new identity and thus a new encryption key.

>2. Issue: When sending device to cloud messages more than 256KB then it is not processing, so how can i increase limit
I am using iot edge device as gateway with iot device

The max message size of 256KiB is an IoT Hub limit. See https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits for the full list.

**Comment by malavvvakharia** [comment]
I am facing the same issue, but I don't have a storage folder. How to resolve it? FYI, we are using TPM as well.

Nov 13 12:46:04 test aziot-keyd[63156]: 2025-11-13T12:46:04Z [INFO] - --> 500 {"content-type": "application/json"}
Nov 13 12:46:04 test aziot-edged[63143]: 2025-11-13T12:46:04Z [INFO] - --> 500 {"content-type": "application/json"}
Nov 13 12:46:07 test aziot-edged[63143]: 2025-11-13T12:46:07Z [INFO] - <-- POST /modules/%24edgeAgent/genid/638986221764691426/decrypt?api-version=2022-08-03 {"accept": "application/json", "host": "workload.sock:80", "connection": "close", "content-type": "application/json", "content-length": "3183"}
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [INFO] - <-- POST /key?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "74"}
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [INFO] - --> 200 {"content-type": "application/json"}
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [INFO] - <-- POST /decrypt?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "3515"}
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [ERR!] - OpenSSL error
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [ERR!] - !!! internal error
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [ERR!] - !!! caused by: could not decrypt
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [ERR!] - !!! caused by: could not decrypt: AZIOT_KEYS_RC_ERR_EXTERNAL
Nov 13 12:46:07 test aziot-keyd[63156]: 2025-11-13T12:46:07Z [INFO] - --> 500 {"content-type": "application/json"}
Nov 13 12:46:07 test aziot-edged[63143]: 2025-11-13T12:46:07Z [INFO] - --> 500 {"content-type": "application/json"}
Nov 13 12:46:12 test aziot-edged[63143]: 2025-11-13T12:46:12Z [INFO] - <-- GET /modules?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
Nov 13 12:46:12 test aziot-edged[63143]: 2025-11-13T12:46:12Z [INFO] - --> 200 {"content-type": "application/json"}
pt?api-version=2022-08-03 {"accept": "application/json", "host": "workload.sock:80", "connection": "close", "content-type": "application/json", "content-length": "3183"}
Nov 13 12:46:19 test aziot-keyd[63156]: 2025-11-13T12:46:19Z [INFO] - <-- POST /key?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "74"}
Nov 13 12:46:19 test aziot-keyd[63156]: 2025-11-13T0;1;31m2025-11-13T12:46:22Z [ERR!] - !!! caused by: could not decrypt: AZIOT_KEYS_RC_ERR_EXTERNAL
Nov 13 12:46:22 test aziot-keyd[63156]: 2025-11-13T12:46:22Z [INFO] - --> 500 {"content-type": "application/json"}
Nov 13 12:46:22 test aziot-edged[63143]: 2025-11-13T12:46:22Z [INFO] - --> 500 {"content-type": "application/json"}
Nov 13 12:46:27 test aziot-edged[63143]: 2025-11-13T12:46:27Z [INFO] - <-- GET /modules?api-version=2022-08-03 {"accept": "a
