### ISSUE TITLE
How to specify a configuration location for edgelet 1.3.0?

### ISSUE THREAD

**Issue by licensedslacker** [Azure/iotedge#6605]
## Expected Behavior
Configuration location can be given as an application argument or environment variable.

Previously the configuration can be given to _iotedged_ with the "-c" argument.

## Current Behavior
It's unclear how to change the configuration location.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Custom
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.3.0
* Edge Agent [image tag (e.g. 1.0.0)]: N/A
* Edge Hub [image tag (e.g. 1.0.0)]:  N/A
* Docker/Moby [run `docker version`]: 18.09.9

## Additional Information
[The source code](https://github.com/Azure/iotedge/blob/9e7e40e2688f08162a431c82e2fad9dfcecfb94f/edgelet/edgelet-settings/src/docker/mod.rs#L22) mentions that the configuration location can be override by **AZIOT_EDGED_CONFIG**
environment variable. However, I have difficulties getting this working and _aziot-edged_ always exists with the error "Failed to load settings: could not read config".

There is also slight conflict with the default path: [in the source](https://github.com/Azure/iotedge/blob/9e7e40e2688f08162a431c82e2fad9dfcecfb94f/edgelet/edgelet-settings/src/docker/mod.rs#L26) the path is specified into "/etc/aziot/edged/config.toml" but [the how-to guide](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=linux#configure-iot-edge-with-the-new-certificates) mentions location to be "/etc/aziot/config.toml".

How to specify the configuration location outside of the default path?

**Comment by arsing** [comment]
>Previously the configuration can be given to iotedged with the "-c" argument.
>
>[...]
>
>How to specify the configuration location outside of the default path?

Why do you want to do this?

---

>There is also slight conflict with the default path: [in the source](https://github.com/Azure/iotedge/blob/9e7e40e2688f08162a431c82e2fad9dfcecfb94f/edgelet/edgelet-settings/src/docker/mod.rs#L26) the path is specified into "/etc/aziot/edged/config.toml" but [the how-to guide](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=linux#configure-iot-edge-with-the-new-certificates) mentions location to be "/etc/aziot/config.toml".

There is no conflict. Those two links are about two different config files.

1.3 split up iotedged into five services. `/etc/aziot/edged/` is the config directory for the edged service, one of those five, specifically. Because we don't want users to manually write five individual configs that all need to be consistent with each other, we have a "super config" that is a combined form for all the services. `iotedge config apply` processes this file into the individual configs for each of those services. The default path for the super config is `/etc/aziot/config.toml`, but you can specify a different path when invoking `iotedge config apply` if you want.

We don't expect users to deal with the individual service configs, which is why the documentation only mentions the super config.

**Comment by licensedslacker** [comment]
Seems like I'm not familiar with this master config system and how the iotedged shall be run on the system. I have used 1.1 LTS version previously and didn't adopt 1.2 into use. For now, I'd say there is no need for changes and I'm closing this ticket.
