### ISSUE TITLE
UpstreamProtocol IoT Edge environment variable: case sensitive or case insensitive ?

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#6613]
I'm building and configuring an IoT Edge solution, and I've noticed that in [this](https://github.com/Azure/iotedge/blob/main/doc/EnvironmentVariables.md) documentation file, the possible values for the `UpstreamProtocol` environment variable are listed as:
- Mqtt
- Amqp
- etc...

However, in [this](https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2020-11#choose-upstream-protocol) document, the possible values are all listed in uppercase.
So, I was now wondering:  what are the correct values ?  Or are they just case-insensitive ?

The same goes for the names of the Environment Variables that can be used to enable/disable protocol heads.
[Here](https://github.com/Azure/iotedge/blob/main/doc/EnvironmentVariables.md#edgehub) they're in PascalCase.  [Here](https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2020-11#disable-unused-protocols) they're camelCased.

So, this is a bit confusing :)

**Comment by brotherneeru** [comment]
Hello! The UpstreamProtocol env variable is case agnostic . Any mixture of case should be accepted as long as the spelling is correct. 

To the point of in one doc , it being camel-cased and in another Pascal, that may just be because those are two separate docs written at different times, one on github and one on docs.microsoft . I'll see who I can talk to to get these on the same page

Thank you

**Comment by fgheysels** [comment]
> Hello! The UpstreamProtocol env variable is case agnostic . Any mixture of case should be accepted as long as the spelling is correct.

So, both the variable name as the contents are case insensitive then ?

**Comment by brotherneeru** [comment]
Yes , the variable name as well should be case insensitive

**Comment by fgheysels** [comment]
Thanks!
