### ISSUE TITLE
Referencing other projects c#

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#67]
Hi there,

I'm trying to reference another project of mine in my IoT Edge Solution in Visual Studio Code (C#).
Adding the reference using 'dotnet add reference' works, it recognizes the project and adds the reference to my .csproj file.

However, when I try to build the IoT Edge solution, I get the following error:
Skipping project "/project/project.csproj" because it was not found.

**Comment by MPapst** [comment]
Hi,

that depends on the default `Dockerfile`. This one scopes only the current project into the build container.
You will need to adjust the `COPY` command inside the `Dockerfile` to get all projects or the whole solution into it.

I had the same issue. I solved it using a private nuget feed (from VSTS), I provide all the necessary projects from there.

**Comment by mbdwaj** [comment]
Well for .NET, I found a way.

Lets say, you are at D:\Projects\MyProject. This will be referred as {somepath}

Inside this, you have {somepath}\modules\{modulename} with all the Dockerfiles. Also, lets say, you have some projects such as {somepath}\coreprojects\{someproject}.csproj which is being referenced into the {modulename} project.

if you try to build this inside DOCKERFILE, using VS Code, the file will not be able to get access because the context of the docker is set to the module folder access, see bold below.

docker build  --rm -f "{somepath}\modules\{modulename}\Dockerfile.amd64" -t {someacr}/{modulename}:0.0.1-amd64 "**{somepath}\modules\{modulename}**" ; if ($?) { docker push {someacr}/{modulename}:0.0.1-amd64 }

Thus, if we correct this to, {somepath}, which would be root for all project folders, and have the DOCKERFILE to copy like COPY . .
it will easily build the dependencies inside the docker and create image easily.

Hence the correct command should be for setting context at root folder.

docker build  --rm -f "{somepath}\modules\{modulename}\Dockerfile.amd64" -t {someacr}/{modulename}:0.0.1-amd64 "**{somepath}**" ; if ($?) { docker push {someacr}/{modulename}:0.0.1-amd64 }

I hope this helps.

**Comment by mbdwaj** [comment]
Is this something MSTeam can fix in the code of VSCode Extension. I can see it in the extension's JS file, thus saving everyone to do this activity each time. I changed the JS code myself and reload the extension, thus it is working fine at my end.

**Comment by nhuurnink** [comment]
I get:
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

This is my template file:
```
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "MainProject.dll"]
```

My command is:
docker build  --rm -f "{pathWithBothProjects}\MainProject\modules\MainProject\Dockerfile.arm32v7" -t something.azurecr.io/mainproject:0.0.1-arm32v7 "{pathWithBothProjects}"

**Comment by myagley** [comment]
I am going to close this issue for now. Please feel free to reopen if you have questions. Thanks!

**Comment by ben-kotvis** [comment]
Why on earth was this closed?  The work around is absurd.

**Comment by HaimAudioburst** [comment]
Have the same issue in Visual Studio 2017 enterprise. Adding the kibernetes container reference to simple .net core project - solution built successfully. Running azure dev spaces (using vs extension tool) result in project not found. Any fix for this issue?

**Comment by erich-wang** [comment]
@HaimAudioburst, as to the issue you mentioned, is it related to VS extension IoT Edge Tools (Preview)? If yes, you may specify **contextPath** if module.json for module project.

**Comment by mabubaker1947** [comment]
Is there any Microsoft documentation created since this issue was marked as completed ? Kindly post a comment with the appropriate docx link here @myagley

**Comment by ddobric** [comment]
End of the year 2022.Still the same issue.
