### ISSUE TITLE
Upstream messages are queued untill restart of edgeHub/edgeAgent module

### ISSUE THREAD

**Issue by maalliet** [Azure/iotedge#6871]
Hello,

We have deployed the Azure Industrial IoT solution in orchestrated mode together with a custom module that acts as an mqtt server. It maps OPC UA messages using a certain configuration and puts them onto a MQTT topic.
Today around 18h07 UTC, we received the message that the IoT Edge device was in a unhealthy state - thanks to the default workbook & metrics collector module.
It appeared that since then, no more telemetry messages arrived at the IoT Hub & upstream messages starting to queue up very quickly, see screenshot (note: the time there is UTC+1)
This happens every now and then but we are unable to identify the root cause, but the logs show a connectivity issue but we don't understand why the device is not able to reconnect.
Only way to solve this is to restart the edgeAgent or edgeHub module to re-establish the connection.
Also, all queued messaged are dropped and not sent to the cloud after restarting, although the gateway is configured for offline support.

Attached you can find the support-bundles of last day, hope you could help us out identifying the root cause.

Thank you in advance.

![Screenshot 2023-01-26 230734](https://user-images.githubusercontent.com/9742401/214962730-a924eda0-6aee-43f6-beae-099c00345dcb.png)
[support-bundle-2023-01-26--21-35-48.zip](https://github.com/Azure/iotedge/files/10513797/support-bundle-2023-01-26--21-35-48.zip)

**Comment by nlcamp** [comment]
@maalliet - Thanks for reporting this issue. Approximately how often do you see this problem? Daily? Weekly? Monthly?

I see you're using an old version, iotedge v1.2.8, We recommend upgrading to our LTS version, 1.4.x, which has some bug fixes compared to 1.2 and is fully supported. If you encounter the same problem with 1.4, we'd be able to provide a bug fix.

Can you upgrade to 1.4.x and let us know if you run into the same problem? If you do, please capture the logs and iotedge check output (note: please use `sudo` -- the iotedge check output in your attached support bundle was missing some content, possibly because it needs to be run with `sudo`).

Note: this issue has some of the same symptoms that were reported in https://github.com/Azure/iotedge/issues/6006. Please take a look at the commands mentioned in that link for simulating poor network connectivity as a way to potentially expedite a repro of this issue:

`sudo tc qdisc add dev eth1 root netem loss 30%`

**Comment by maalliet** [comment]
@nlcamp Thanks a lot for your reply. 

To be fair, it is an issue that we are struggling with for a longer period (around a year). At the start it happened quite frequently (around 3-5 times per month). We initially thought that it was caused by the custom module and focusing on that one instead for further analysis. We've done a few iotedge upgrades which in the end reduced frequency of the issue to about once per month. Of course it always fails on crucial moments where other things have priority so we did not follow-up on the issue the last few months and were lacking behind the upgrade of iotedge. I'll do the upgrade asap.

You're right, that other issue didn't catch my eye, but seems very similar what we experienced. 
I'll see if we can setup a separate iot edge device to do some proper testing. I'll close it for now and will reopen with new logs if it occurs again.
