### ISSUE TITLE
Unstall-SecurtityDaemon failing

### ISSUE THREAD

**Issue by futurexpe** [Azure/iotedge#690]
I had installed iot edge on my dev box.

Currently there is some issue with the 'iotedge' service not showing up. 
Get-Service iotedge
Get-Service : Cannot find any service with service name 'iotedge'.
At line:1 char:1
+ Get-Service iotedge
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (iotedge:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand

 
So I tried to uninstall the securitydaemon so I can re-install it:
Uninstall-SecurityDaemon
Uninstalling...
Uninstall-SecurityDaemon : The property 'net.azure-devices.edge.owner' cannot be found on this object. Verify that the
property exists.
At line:1 char:1
+ Uninstall-SecurityDaemon
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Uninstall-SecurityDaemon], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Uninstall-SecurityDaemon

**Comment by ancaantochi** [comment]
Hi @shreyone,

Thanks for reporting this issue, it is a bug in the uninstall script where it tries to remove the containers that were created by edge. As a workaround, can you remove all the containers before you uninstall (unfortunately this means including containers that were not created by edge because that is actually causing the bug to reproduce). 

Thanks.

**Comment by arsing** [comment]
Another workaround is to comment the [`Set-StrictMode` line](https://github.com/Azure/iotedge/blob/1.0.5/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L141) so that accessing the missing property returns `$null` instead of throwing.
