### ISSUE TITLE
Stream Analytics on IoT Edge module possibility of data loss

### ISSUE THREAD

**Issue by maciej-kepa** [Azure/iotedge#6949]
Hello. Our team is currently investigating the capabilities of Stream Analytics module deployed on IoT Edge. We are performing simple aggregation on data stream over a 1min window:
```
SELECT  
    COUNT(temperature)
INTO
   output
FROM
   input TIMESTAMP BY timestamp
GROUP BY TumblingWindow(minute,1)
```

If the module is somehow stopped or restarted in the middle of that time window, the data that was aggregated in the window up to the restart moment is lost. For example - if we have 1 message per second in out input, and we restart the module in the middle of 1 minute window (after 30 seconds) - we will lose 30 messages. 
If my understanding is correct, this happens because:
1. Stream Analytics module consumes messages from edgeHub queue
2. The messages are aggregated in memory of the module
3. edgeHub takes the consumed messages out from the queue
4. Module is restarted and memory is wiped out along with aggregated messages before it can send the whole window to upstream

Our question is: is that understanding correct and is there any mechanism that could prevent the data loss in case of Stream Analytics module restart?

**Comment by and-rewsmith** [comment]
@xitia Can yout ake a look since this is related to ASA module?

**Comment by jlian** [comment]
@xitia can you help take a look here?

**Comment by xitia** [comment]
@maciej-kepa This is a known limitation with ASA on edge module. We have limited support in repeatability. This is mainly because edge hub is a push based streaming local data store, the streaming job is not able to query events from particular time range for reprocessing. Unfortunately, we don't have a workaround for this scenario, unless edge hub can provide such functionality.
