### ISSUE TITLE
 IoT Edge Module - Missing Connection String for Module

### ISSUE THREAD

**Issue by MPapst** [Azure/iotedge#7]
## Expected Behavior
Connection String or relevant Tokens are injected into Module via Env var

## Current Behavior
At least the SAS Token is not injected into the module.

## Steps to Reproduce
1. Create a sample Module (e.g. using VSCoce Extension)
2. Build Container and deploy to edge device
3. Find env vars not containing a connection string or the SAS token (all other necessary information to build up the connection string is found in differend env-vars)

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
1.0.0

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
Version: dev
API version: 1.37
Git commit 9aac187

## Additional Information
In the preview versions the Connection String for the ModuleClient was injected into the docker container. The Environment Variable EdgeHubConnectionString is missing in the version. Additional there is no candidate in the Env-vars with could suits those needs. Even when combining the evn-vars, the SAS Token is missing.

**Comment by aribeironovaes** [comment]
Hi @MPapst , 

This behavior is actually by design and it's a security change that we made on GA. 
The Connection string (With exposed keys) is not injected any more into modules. 
New modules should use new templates (Hence new SDK) that will call a new method (Create From Environment method) and this will make sure it will call our security daemon (iotedged) to get it's token. 

Have you tried the new VS Code Template and did you have any problem? 

Let us know, 

Angelo Ribeiro.

**Comment by MPapst** [comment]
@aribeironovaes, thanks thats working for me.
That was just a combination of some ugly circumstances... (`dotnet new -i ...` is not working when you have a private vsts nuget repository set up; the VSCode extension is supplying the old templates and the documentation in docs shows an env var that I did not even know)

Thanks for your help!
