### ISSUE TITLE
Why do the `edgeHub` and `edgeAgent` containers not support Docker Volumes?

### ISSUE THREAD

**Issue by F-Joachim** [Azure/iotedge#7166]
The [preferred mechanism](https://docs.docker.com/storage/volumes/) from Docker to persist data is to use Docker Volumes. Thus, we want to refactor our manifests by replacing all of our host mounts with (named) volumes mounts. The most beneficial point would be the independence of the host system and the corresponding pre-configuration of the directories (as already described [here](https://github.com/Azure/iotedge/issues/6035) and [here](https://feedback.azure.com/d365community/idea/7f49f935-188c-ec11-a81b-6045bd7956bb)).
However, we are still hesitating to make the switch as we have seen that the `edgeHub` and `edgeAgent` do not yet support this Docker feature. Are there any reasons - in combination with the `iotedge` - why you do not support Docker Volumes? 

Many thanks in advance for the clarification.

**Comment by arsing** [comment]
`createOptions` in the EA / EH twins takes any valid JSON object that [dockerd's ContainerCreate API](https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerCreate) takes, which includes the ability to specify a mountpoint as a volume instead of a host dir. If you can't figure out how to construct the JSON, you can create a dummy container with `docker create` and whatever options you want, then `docker inspect` it to get the JSON, then translate that into the EA / EH config.

If EA / EH is started as root, it will fix up the permissions of the storage directory ([EA](https://github.com/Azure/iotedge/blob/fb3d0e07190ca29faa57aa1fc67b43f94d9ad995/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/agentStart.sh#L49-L59) and [EH](https://github.com/Azure/iotedge/blob/fb3d0e07190ca29faa57aa1fc67b43f94d9ad995/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/hubStart.sh#L52-L62)) and then change to a limited user, so permissions are not a problem either.

So I don't see anything that would prevent you from using docker volumes. I haven't tried it though. Try it?

**Comment by F-Joachim** [comment]
@arsing - Thanks for your response.

The technical realization of how to configure the volume mounts is already clear to me. **The question was rather aimed at asking whether this is also a supported way of Microsoft**, since the [documentation ](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4#configure-system-modules-to-use-persistent-storage) does not refer to it (in contrast to [Blob Storage](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-1.4#granting-directory-access-to-container-user-on-linux)). 

As I took a closer look at the scripts you linked, I saw that both containers run as `root`. Only the application runs as `edge<agent|hub>user`. When I wrote the issue, I assumed that the container also runs as a user and therefore requires corresponding permissions for the `storageFolder`, which are set in the Dockerfile. However, this means that the volume mounts only work because the container is running as `root`. It wouldn't work with user rights, right?

I've tested the volume mounts for both `edgeHub` and `edgeAgent` (running as `root`) in my test environment and it works as expected.

**Comment by F-Joachim** [comment]
> As I took a closer look at the scripts you linked, I saw that both containers run as root. Only the application runs as edge<agent|hub>user. When I wrote the issue, I assumed that the container also runs as a user and therefore requires corresponding permissions for the storageFolder, which are set in the Dockerfile. However, this means that the volume mounts only work because the container is running as root. It wouldn't work with user rights, right?

Understood - the resulting process of the image (= `edgeHub` or `edgeAgent` application) runs with user privileges and is therefore not a security risk 👍
