### ISSUE TITLE
Nest edge devices - child showing 502 Bad Gateway

### ISSUE THREAD

**Issue by wolfvillain2** [Azure/iotedge#7198]
I've configured a linux edge devices to be in the nested structure. When the child device tries to pull containers, I'm getting the following message when I did an iotedge check.

![image](https://github.com/Azure/iotedge/assets/156369742/277c2d6b-4cbd-49d1-a6e0-b9054ca4ffac)

The child device is able to telnet to parent device over 443 so not sure what could be the issue here.

**Comment by wolfvillain2** [comment]
I've made progress but now this is what I'm seeing when docker tries to pull the image from the parent. 
![image](https://github.com/Azure/iotedge/assets/156369742/b1c7d4d3-22f3-4171-ad2c-6297f7a91329)

The iotedge api proxy is set to use port 443

**Comment by vipeller** [comment]
Hi @wolfvillain2. How does your docker proxy settings look like? It seems that docker tries to use plain instead of tls. It does it if it has http proxy set, or when it fails with https and then it falls back to plain. The https failure can be caused by unknown CA certificate for example, is it possible that the child does not know the root ca for the proxy communication?

**Comment by jlian** [comment]
@wolfvillain2 can you share the details

**Comment by jlian** [comment]
@wolfvillain2 checking in again
