### ISSUE TITLE
Cannot start service iotedge on computer '.'. 

### ISSUE THREAD

**Issue by gauravagarwal28** [Azure/iotedge#78]
Followed the instructions for setting up IOT Edge runtime on my windows machine with Linux Containers from here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux

but I get the following error on starting the service:

> PS C:\WINDOWS\system32> Start-Service iotedge
Start-Service : Service 'iotedge (iotedge)' cannot be started due to the following error: Cannot start service iotedge on computer '.'.
At line:1 char:1
 Start-Service iotedge 

## Steps to Reproduce
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux

## Context (Environment)
Windows 10 with Linux containers (Docker)

### Device (Host) Operating System
Windows 10

### Container Operating System
Linux containers

### Runtime Versions
GA

#### Docker
Version 18.06.0-ce-win70 (19075)

PS C:\WINDOWS\system32> Start-Service iotedge
Start-Service : Service 'iotedge (iotedge)' cannot be started due to the following error: Cannot start service iotedge on computer '.'.
At line:1 char:1
+ Start-Service iotedge
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PS C:\WINDOWS\system32> Get-Service iotedge

Status   Name               DisplayName
------   ----               -----------
Stopped  iotedge            iotedge

**Comment by gauravagarwal28** [comment]
considering #77 , I even downgraded the docker version but I get the same error.

**Comment by MPapst** [comment]
Are you getting a similar logging output from the security agent?
Try
```
Get-WinEvent -ea SilentlyContinue `
-FilterHashtable @{ProviderName= "iotedged";
LogName = "application"; StartTime = [datetime]::Now.AddMinutes(-5.0)} |
select TimeCreated, Message |
sort-object @{Expression="TimeCreated";Descending=$false}
```

**Comment by dsajanice** [comment]
Are you running as administrator?

**Comment by ilyas-it83** [comment]
Yes i did face the problem in my windows machine  and i ran PS with admin! Please find the logs below!

PS C:\WINDOWS\system32> Get-Service iotedge

Status   Name               DisplayName
------   ----               -----------
Start... iotedge            iotedge


PS C:\WINDOWS\system32> Get-WinEvent -ea SilentlyContinue `
>>  -FilterHashtable @{ProviderName= "iotedged";
>>    LogName = "application"; StartTime = [datetime]::Today} |
>>  select TimeCreated, Message |
>>  sort-object @{Expression="TimeCreated";Descending=$false}

TimeCreated            Message
-----------            -------
26-07-2018 01:57:12 PM info: iotedged::app -- Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
26-07-2018 01:57:12 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
26-07-2018 01:57:12 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
26-07-2018 01:57:12 PM info: iotedged::windows -- Starting iotedged service.
26-07-2018 01:57:12 PM info: iotedged -- Initializing the module runtime...
26-07-2018 01:57:12 PM info: iotedged -- Using runtime network id nat
26-07-2018 01:57:12 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
26-07-2018 01:57:12 PM info: iotedged -- Finished initializing the module runtime.
26-07-2018 01:57:12 PM info: iotedged -- Finished configuring certificates.
26-07-2018 01:57:12 PM info: iotedged -- Initializing hsm...
26-07-2018 01:57:12 PM info: iotedged -- Configuring certificates...
26-07-2018 01:57:12 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
26-07-2018 01:57:15 PM info: iotedged -- Change to configuration file detected.
26-07-2018 01:57:15 PM info: iotedged -- Detecting if configuration file has changed...
26-07-2018 01:57:15 PM info: iotedged -- Finished initializing hsm.
26-07-2018 01:57:15 PM info: iotedged -- Removing all modules...
26-07-2018 01:57:15 PM info: iotedged -- Finished removing modules.
26-07-2018 01:57:15 PM info: iotedged -- Provisioning edge device...
26-07-2018 01:57:15 PM info: iotedged::windows -- Stopped iotedged service.
26-07-2018 01:57:15 PM error: iotedged::windows -- Error while running service. Quitting.
26-07-2018 02:03:58 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
26-07-2018 02:03:58 PM info: iotedged::app -- Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
26-07-2018 02:03:58 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
26-07-2018 02:03:58 PM error: edgelet_utils::logging --         caused by: while parsing a block mapping, did not find expe...
26-07-2018 02:03:58 PM error: edgelet_utils::logging -- Invalid configuration file
26-07-2018 02:03:58 PM error: iotedged::windows -- Error while running service. Quitting.
26-07-2018 11:15:51 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
26-07-2018 11:15:51 PM info: iotedged::app -- Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
26-07-2018 11:15:51 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
26-07-2018 11:15:51 PM error: iotedged::windows -- Error while running service. Quitting.
26-07-2018 11:15:51 PM error: edgelet_utils::logging -- Invalid configuration file
26-07-2018 11:15:51 PM error: edgelet_utils::logging --         caused by: while parsing a block mapping, did not find expe...


PS C:\WINDOWS\system32> iotedge list
An error in the management http client occurred.
        caused by: Hyper error
        caused by: No connection could be made because the target machine actively refused it. (os error 10061)
PS C:\WINDOWS\system32>

PS C:\WINDOWS\system32> Start-Service iotedge
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
PS C:\WINDOWS\system32> Stop-Service iotedge -NoWait
Stop-Service : Service 'iotedge (iotedge)' cannot be stopped due to the following error: Cannot stop iotedge service on computer '.'.
At line:1 char:1
+ Stop-Service iotedge -NoWait
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Stop-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand

PS C:\WINDOWS\system32> Stop-Service iotedge -NoWait
Stop-Service : Service 'iotedge (iotedge)' cannot be stopped due to the following error: Cannot stop iotedge service on computer '.'.
At line:1 char:1
+ Stop-Service iotedge -NoWait
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Stop-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand

PS C:\WINDOWS\system32> Stop-Service iotedge -NoWait
Stop-Service : Service 'iotedge (iotedge)' cannot be stopped due to the following error: Cannot stop iotedge service on computer '.'.
At line:1 char:1
+ Stop-Service iotedge -NoWait
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Stop-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand

PS C:\WINDOWS\system32> Start-Service iotedge
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
PS C:\WINDOWS\system32> Get-Service iotedge

Status   Name               DisplayName
------   ----               -----------
Start... iotedge            iotedge

**Comment by dsajanice** [comment]
@ilyas-it83 it looks like there was an error in your configuration file. 

26-07-2018 02:03:58 PM error: edgelet_utils::logging -- caused by: while parsing a block mapping, did not find expe...
26-07-2018 02:03:58 PM error: edgelet_utils::logging -- Invalid configuration file

**Comment by dsajanice** [comment]
@ilyas-it83 the following line is truncated:
26-07-2018 02:03:58 PM error: edgelet_utils::logging -- caused by: while parsing a block mapping, did not find expe...

If you get the full line it should tell you exactly where the problem is in your config file.

**Comment by gauravagarwal28** [comment]
@dsajanice Yes I am running as administrator. 

Get-WinEvent -ea SilentlyContinue `
-FilterHashtable @{ProviderName= "iotedged";
LogName = "application"; StartTime = [datetime]::Now.AddMinutes(-5.0)} |
select TimeCreated, Message |
sort-object @{Expression="TimeCreated";Descending=$false}

Shows no output on my terminal

**Comment by MPapst** [comment]
@gauravagarwal28, note the `[datetime]::Now.AddMinutes(-5.0)` that was my edit to the command from the original documentation. With that it shows only the last 5 Minutes from the Event Log.
You need to adjust that to get a different output. Try `[datetime]::Parse('2018-07-26 14:00:00')` for that specific line.

**Comment by gauravagarwal28** [comment]
There are no logs even after the modifications you suggested.

I even tried to use 172.26.48.1 instead of 10.0.75.1 but to no avail.










PS C:\WINDOWS\system32> Get-Service iotedge

Status   Name               DisplayName
------   ----               -----------
Stopped  iotedge            iotedge


PS C:\WINDOWS\system32> Stop-Service iotedge -NoWait
PS C:\WINDOWS\system32> sleep 5
PS C:\WINDOWS\system32> Start-Service iotedge
Start-Service : Service 'iotedge (iotedge)' cannot be started due to the following error: Cannot start service iotedge
on computer '.'.
At line:1 char:1
+ Start-Service iotedge
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PS C:\WINDOWS\system32> ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::3902:ec8b:9a31:9b8a%4
   IPv4 Address. . . . . . . . . . . : 10.0.75.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::a8f2:5021:f32b:93e0%18
   IPv4 Address. . . . . . . . . . . : 10.9.43.202
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.9.43.1

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::496c:26f8:8f39:337e%10
   IPv4 Address. . . . . . . . . . . : 172.31.89.161
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
PS C:\WINDOWS\system32> hostname
GauravA-PC
PS C:\WINDOWS\system32> notepad C:\ProgramData\iotedge\config.yaml
PS C:\WINDOWS\system32> cat C:\ProgramData\iotedge\config.yaml
###############################################################################
#                      IoT Edge Daemon configuration
###############################################################################
#
# This file configures the IoT Edge daemon. The daemon must be restarted to
# pick up any configuration changes.
#
# Note - this file is yaml. Learn more here: http://yaml.org/refcard.html
#
###############################################################################

###############################################################################
# Provisioning mode and settings
###############################################################################
#
# Configures the identity provisioning mode of the daemon.
#
# Supported modes:
#     manual - using an iothub connection string
#     dps    - using dps for provisioning
#
###############################################################################

provisioning:
  source: "manual"
  device_connection_string: "HostName=testdummyIoTHub.azure-devices.net;DeviceId=GauravWindows;SharedAccessKey=uSgPQ6jZCWCdbiVCl9KRgfxnv1Na4py10sTx133Xgbk="

# provisioning:
#   source: "dps"
#   global_endpoint: "https://global.azure-devices-provisioning.net"
#   scope_id: "{scope_id}"
#   registration_id: "{registration_id}"

###############################################################################
# Certificate settings
###############################################################################
#
# Configures the certificates required to operate the IoT Edge
# runtime as a gateway which enables external leaf devices to securely
# communicate with the Edge Hub. If not specified, the required certificates
# are auto generated for quick start scenarios which are not intended for
# production environments.
#
# Settings:
#     device_ca_cert   - path to the device ca certificate and its chain
#     device_ca_pk     - path to the device ca private key file
#     trusted_ca_certs - path to a file containing all the trusted CA
#                        certificates required for Edge module communication
#
###############################################################################

# certificates:
#   device_ca_cert: "<ADD PATH TO DEVICE CA CERTIFICATE HERE>"
#   device_ca_pk: "<ADD PATH TO DEVICE CA PRIVATE KEY HERE>"
#   trusted_ca_certs: "<ADD PATH TO TRUSTED CA CERTIFICATES HERE>"

###############################################################################
# Edge Agent module spec
###############################################################################
#
# Configures the initial Edge Agent module.
#
# The daemon uses this definition to bootstrap the system. The Edge Agent can
# then update itself based on the Edge Agent module definition present in the
# deployment in IoT Hub.
#
###############################################################################

agent:
  name: "edgeAgent"
  type: "docker"
  env: {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}

###############################################################################
# Edge device hostname
###############################################################################
#
# Configures the environment variable 'IOTEDGE_GATEWAYHOSTNAME' injected into
# modules.
#
###############################################################################

hostname: "GauravA-PC"

###############################################################################
# Connect settings
###############################################################################
#
#
# Configures URIs used by clients of the management and workload APIs
#     management_uri - used by the Edge Agent and 'iotedge' CLI to start,
#                      stop, and manage modules
#     workload_uri   - used by modules to retrieve tokens and certificates
#
# The following uri schemes are supported:
#     http - connect over TCP
#
###############################################################################

connect:
  management_uri: "http://10.0.75.1:15580"
  workload_uri: "http://10.0.75.1:15581"

###############################################################################
# Listen settings
###############################################################################
#
# Configures the listen addresses for the daemon.
#     management_uri - used by the Edge Agent and 'iotedge' CLI to start,
#                      stop, and manage modules
#     workload_uri   - used by modules to retrieve tokens and certificates
#
# The following uri schemes are supported:
#     http - listen over TCP
#
###############################################################################

listen:
  management_uri: "http://10.0.75.1:15580"
  workload_uri: "http://10.0.75.1:15581"

###############################################################################
# Home Directory
###############################################################################
#
# This configures the home directory for the daemon.
#
###############################################################################

homedir: "C:\\ProgramData\\iotedge"

###############################################################################
# Moby Container Runtime settings
###############################################################################
#
# uri - configures the uri for the container runtime.
# network - configures the network on which the containers will be created.
#
###############################################################################

moby_runtime:
  uri: "npipe://./pipe/docker_engine"
  network: "nat"
PS C:\WINDOWS\system32> docker --version
Docker version 18.06.0-ce, build 0ffa825
PS C:\WINDOWS\system32>










And as for the logs (You can see there is no output): 

PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Get-WinEvent -ea SilentlyContinue `
>> -FilterHashtable @{ProviderName= "iotedged";
>> LogName = "application"; StartTime = [datetime]::Now.AddMinutes(-5.0)} |
>> select TimeCreated, Message |
>> sort-object @{Expression="TimeCreated";Descending=$false}
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Get-WinEvent -ea SilentlyContinue `
>> -FilterHashtable @{ProviderName= "iotedged";
>> LogName = "application"; StartTime = [datetime]::Parse('2018-07-26 14:00:00')} |
>> select TimeCreated, Message |
>> sort-object @{Expression="TimeCreated";Descending=$false}
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>

**Comment by veyalla** [comment]
Thanks @gauravagarwal28, I don't see anything wrong with your config file. Right now our install instructions on Windows have a number of manual steps which can be error prone, we're going to update them next week with a script based install that will automate a lot of these. If you want to try an early version to see if it helps, here are the steps.

1. Clean the current setup (you might need to reboot your computer and run the command one more time, the cmdlet will prompt you if this is needed):
```powershell
. { Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
UnInstall-SecurityDaemon -v -Force
```
2. Install security daemon with Linux containers:
```powershell
. { Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Manual
```
The cmdlet will prompt you for a device connection string, paste the connection string *without* any quotes, for example:
![image](https://user-images.githubusercontent.com/22105760/43353068-9c682e18-91e3-11e8-9c17-95fe33e3b771.png)

That's it! Let me know if it works.

If you it still doesn't work for you, please attach the error details along with the output of `Get-ComputerInfo`

**Comment by gauravagarwal28** [comment]
@veyalla 

These instructions worked out for me and I can now see the edgeAgent running when I run the "iotedge list" command.

Thank you for the support 👍
