### ISSUE TITLE
Windows installer script: using -ExistingConfig option with Linux containers does not set environment variable for IOTEDGE_HOST

### ISSUE THREAD

**Issue by veyalla** [Azure/iotedge#805]
## Expected Behavior

Doing a 'lightweight' uninstall (without ```-DeleteConfig``` and ```-DeleteMobyRoot```) and re-installing with ```-ExistingConfig``` option works as like before update.

## Current Behavior

Doing a 'lightweight' uninstall (without ```-DeleteConfig``` and ```-DeleteMobyRoot```) and re-installing with ```-ExistingConfig``` option breaks the iotedge tool. Using -H to explicitly specify the management URI works, so missing env var seems to  be rootcause.

**Comment by myagley** [comment]
Does this only affect linux containers on windows?

**Comment by veyalla** [comment]
Haven't explicitly tested, but I think so, because if env var is not set it defaults to UDS on Windows. @damonbarry can confirm.

**Comment by damonbarry** [comment]
I just tried it on Windows/Windows, and the `iotedge` CLI continues to work after reinstall with `-ExistingConfig`, presumably for the reason @veyalla cites.

An interesting (but unrelated) find: if I reinstall with `-ExistingConfig` but I don't specify `-ContainerOs Windows`, then the container OS defaults to Linux and `iotedge` installs successfully but fails to start. On my machine, I have Docker for Windows installed and set to Linux containers, so that's probably why it made it through the install. But then when iotedge tries to start with the existing config.yaml it falls over somewhere. There's no clear indicator in config.yaml that you're using Windows containers vs. Linux containers. It seems like the value of `-ContainerOs` _ought_ to be inferred when you choose `-ExistingConfig`.

**Comment by veyalla** [comment]
Closing as this does't apply with new .cab based install.
