### ISSUE TITLE
At least once delivery for messages between IotEdge modules?

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iotedge#832]
Is there a "At least once delivery guarantee" for messages between IotEdge modules?
Is the behaviour different for MQTT and AMQP ?  Do any settings have to be adjusted?

We have the following scenario:
The OpcPublisher Module is generating messages with data from a SPS.  The messages are picked up by a customModule A which sends messages to IotHub on one output and sends messages to customModule B on another output.  Custom Module B also sends messages to IotHub.

What happens if Custom Module A crashes?  Will messages send by OpcPublisher during the outage be lost or will they be delivered once Custom Module A is back?

What happens if Custom Module B crashes?  Will it receive all the messages from Custom Module A after it is back?

What happens if the EdgeHub Module crashes?  Will all Inter-Module-Messages be delivered afterwards?

Are messages being delivered after a crash guaranteed to be in the correct order?

I would be grateful for any insight on this matter.

**Comment by myagley** [comment]
By default, the client SDKs and the Edge Hub use QoS level 1 (at least once). When the Edge Hub sends an acknowledgement of the message, it has already saved the message to disk. The Edge Hub keeps track of the message offset for each receiver and will resume from this point. This works because the client SDK by default also uses QoS 1 and must acknowledge processing of the message. (message completion).

Putting these acknowledgements together and the persistent storage of message gets you at least once delivery. Messages are also queued per endpoint and are guaranteed to be delivered in order.

If the Edge Hub fails, then it is expected that the module will continue to retry sending a message. 

Something to be aware of is that messages can be removed from the queue if their TTL expires. This means that all of these retries must complete before the TTL. This TTL value is configurable via the Edge Hub's twin and defaults to 2 hours. For example: 

```json
"$edgeHub": {
  "properties.desired": {
    "schemaVersion": "1.0",
    "routes": {
      "route": "FROM /messages/* INTO $upstream"
    },
    "storeAndForwardConfiguration": {
      "timeToLiveSecs": 7200
    }
  }
}
```

**Comment by BewaControl-ReneDivossen** [comment]
@myagley Thank's for the insight.  You write 

> If the Edge Hub fails, then it is expected that the module will continue to retry sending a message.

I found instructions for setting a retry Policy [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-reliability-features-in-sdks#net-implementation-guidance).  This guide is for the IotHub but I trust it works the same with EdgeHub!?

If in my module I created the client like this:
```
AmqpTransportSettings amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
ITransportSettings[] settings = { amqpSetting };
ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await ioTHubModuleClient.OpenAsync();
```
without calling **SetRetryPolicy** on the client, will there be a default retryPolicy set?  Will it be the one described on the page linked above?

**Comment by myagley** [comment]
Yes, there is a [default retry policy](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/RetryDelegatingHandler.cs#L36) in the C# SDK and it works the same for the Edge Hub as IoT Hub. It is the same policy mentioned in the documentation:

```csharp
IRetryPolicy defaultRetryStrategy = new ExponentialBackoff(
                retryCount: s_retryMaxCount,
                minBackoff: TimeSpan.FromMilliseconds(100),
                maxBackoff: TimeSpan.FromSeconds(10),
                deltaBackoff: TimeSpan.FromMilliseconds(100));
```

**Comment by BewaControl-ReneDivossen** [comment]
@myagley Thank you for the insight.  The issue is solved for me.  You can close it.

**Comment by myagley** [comment]
Thank you!
