### ISSUE TITLE
NotConnectedError: getaddrinfo ENOTFOUND <hostName><hostName>:8883

### ISSUE THREAD

**Issue by AndyChuang1** [Azure/iotedge#867]
## Expected Behavior
I'm using azure-iot-device & azure-iot-device-mqt for azure iot edge right now.
I followed the official docs to create node module.
 Node app connected to the Edge instance successfully that is my expection.
## Current Behavior
Node app always threw this error which is `NotConnectedError: getaddrinfo ENOTFOUND ecs-aplu-ic1 ecs-aplu-ic1:8883`  when node app connected to the Edge instance.

## Steps to Reproduce
```
var Transport = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').ModuleClient;
var Message = require('azure-iot-device').Message;
var moduleClient;
Client.fromEnvironment(Transport, function (err, client)
 {
        if (err) {
            throw err;
        } else {
            moduleClient = client;
            client.on('error', function (err) {
                throw err;
            });
            // connect to the Edge instance
            client.open(function (err) {
                if (err) {
                    throw err;
                } else {
                    console.log('IoT Hub module client initialized');
                    // Act on input messages to the module.
                    client.on('inputMessage', function (inputName, msg) {
                        filterMessage(client, inputName, msg);
                    });
                }
            });
        }
    });
```
Node module try to connect to the Edge instance

### Device (Host) Operating System

Ubuntu 16.04.05.  
### Architecture

amd64
### Container Operating System

Linux containers
#### iotedged

iotedge 1.0.6.1
#### Edge Agent

mcr.microsoft.com/azureiotedge-hub:1.0 
#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0 d
#### Docker

 Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  OS/Arch:          linux/amd64
  Experimental:     false

## Logs

# Console log of the issue:
![Imgur](https://i.imgur.com/1T0IOHp.png)
# My temporary Solution 
My host name is ecs-APLU-IC1, as below:
![Imgur](https://i.imgur.com/ZWyLLY1.png)
If I edit hosts file ,change ecs-APLU-IC1 to ecs-aplu-ic1, this error will not happen.
Is that Case converter issue of SDK ?
## Additional Information

I also posted this issue on [azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node/issues/494)

**Comment by myagley** [comment]
Thanks for the issue. I'm following up on the original issue.

**Comment by darobs** [comment]
From the Node SDK group's investigation, it looks like we should considering not forcing the name to lowercase:

> I managed to repro the problem with an alpine linux container. it seems that node.js is sensitive to whatever resolver is included with the base container image (ubuntu works, alpine doesn't).
> 
> @darobs @myagley I'm not sure if there is a particular reason to lowercase the hostnames but knowing that different resolvers have different behavior, it might be a worth considering not doing that?
> 
> Not sure there's anything we can do on the SDK side at that point.

**Comment by mihainstr** [comment]
*Because the iot node sdk sibling issue was closed I will leave my notes and questions here.*

I ran across a similar issue after upgrading from v1.7.0 to v1.9.4. I am, as described here as well, using node:8-alpine as a basis for the docker image.

**Please not that this issue was not present/observed when running with v1.7.0 !** It worked fine, in that case I observed some other crashes but at least it was working.

The issue is similar:
![image](https://user-images.githubusercontent.com/10221172/54827382-8164b680-4cba-11e9-8db9-31b18956573c.png)

Interestingly in this case there is no case sensitivity issue, as I understood that might have been the reason for the initial post failure:
![image](https://user-images.githubusercontent.com/10221172/54827546-f0daa600-4cba-11e9-8a44-05e3aa4527b4.png)

**I need a possible solution here, would switching to build on top of an ubuntu image solve it ?**
**Any ideas why it was working with previous versions and now it is not working anymore ?**

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
