### ISSUE TITLE
Proxy was working, now cannot find config after WebSocketException

### ISSUE THREAD

**Issue by richardleeaus** [Azure/iotedge#885]
Hello,

Yesterday we did a fresh install of IoT Edge onto Ubuntu 16.04 with little issues. As we are behind a corporate proxy we have to use the proxy.

This was originally no problem, the agent pulled down multiple containers yesterday and one this morning. 

We did one change to the deployment.json, changing the status of a module to "stopped" and the edgeAgent starting reporting this error: `[WRN] - Updating reported properties failed with error Unable to connect to the remote server type System.Net.WebSockets.WebSocketException`. It appeared at this point the deployment was not getting updated.

We rolled back the deployment change, restarted the service, and now instead of the above error we get 
`
2019-02-25 22:30:24.979 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
2019-02-25 22:30:26.845 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
`

We also use a login and encoded password in the proxy URL.

The deployment won't update and all of a sudden it looks like the proxy isn't working.

Any ideas? - This doesn't seem right, and we saw something similar with running Linux on Docker for Windows behind a proxy.

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support

**Comment by richardleeaus** [comment]
It seems adding an additional `http_proxy` variable to the config.yaml and also the deployment.json fixed the problem. I'll monitor this closely.

**Comment by myagley** [comment]
It would be helpful to see more of the Edge Agent logs to understand the sequence of events. Given the few log lines above, it's possible that the root cause is connectivity from the Edge Agent to the proxy.

The "Empty edge agent config" can occur for two reasons: the config is actually empty or there is an underlying connection issue (we are updating this log to remove the ambiguity). The usual culprits of connectivity issues are inability to connect to the IoT Hub or inability to communicate with DNS to resolve the hostname.

The DNS resolution can be made much more stable by configuring the docker engine with a static IP address of your DNS server. This is done through the docker engine's config file. On Ubuntu, this is located in `/etc/docker/daemon.json`. For example:

```json
{
    "dns": ["8.8.8.8"]
}
```

You will want to replace the ip address with your corporate DNS address.

**Comment by richardleeaus** [comment]
Thanks @myagley , i'll try this and see if it gives better reliability. If there is another way to get more verbose logs let me know.

For extra information, I came back into work today with the runtime running for 4+ days and the edgeAgent is producing the below error: `2019-03-03 21:36:18.141 +00:00 [WRN] - Updating reported properties failed with error Operation timeout expired. type System.TimeoutException
2019-03-03 21:36:23.154 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 115`

**Comment by myagley** [comment]
Yes, this is a connection issue, either communicating with DNS or between the Edge Agent and IoT Hub.

**Comment by richardleeaus** [comment]
More errors here: `2019-03-05 04:25:47.282 +00:00 [WRN] - Updating reported properties failed with error Service rejected the message with status: 403 type System.InvalidOperationException`

Edge agent is also not detecting a config change.

Really trying here to get a stable connection, but not getting many wins. Is there more verbose information i can give you?

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
